### ISSUE TITLE
TLS certificate has expired in maven repo

### ISSUE THREAD

**Issue by KPGTB** [andrei1058/BedWars1058#1001]
**Describe the bug**
Your TLS certificate expired few days ago, so we can't use your API (https://repo.andrei1058.dev/releases/)

**Comment by Lsy-291** [comment]
This will probably start between the 14th and 15th

**Comment by KikyoC** [comment]
Same thing on javadoc

**Comment by Lsy-291** [comment]
![image](https://github.com/andrei1058/BedWars1058/assets/68882326/4f7f26f4-6ed9-4571-acd1-f7310e2138e4)
Why is this also affected?

**Comment by itz-rj-here** [comment]
andrei1058 is also no longer found...
he is like gone away

didn't saw him came online for some days

**Comment by itz-rj-here** [comment]
![image](https://github.com/andrei1058/BedWars1058/assets/86042583/037e801c-2dc1-416f-88f9-88eef5f1d5f2)
See...

**Comment by andrei1058** [comment]
I'm paying the ssl right now
