### ISSUE TITLE
1.16.5 bug

### ISSUE THREAD

**Issue by Mvory9** [andrei1058/BedWars1058#1006]
Message from console:
`[BedWars1058] SidebarLib by andrei1058 does not support your server version`

 - OS: Windows 
 - Server software: Paper
 - Server Version: 1.16.5
 - Plugin Version: Last (from 10 December 2023)

**Comment by andrei1058** [comment]
After a [quick look at our pom I can confirm this issue](https://github.com/andrei1058/BedWars1058/blob/3895fd008c08e0ab682899986c46f052f4c07db4/bedwars-plugin/pom.xml#L277). It is compiling the sidebar for R1 instead of R3.
