### ISSUE TITLE
Duplicate sword

### ISSUE THREAD

**Issue by AliiiAm** [andrei1058/BedWars1058#1009]
**Describe the bug**
players can duplicate sword

**To Reproduce**
1. Open Inventory
2. Take the sword and throw it
4. Duplicated
**Expected behavior**
Sword dropped and removed from inventory

**Screenshots**
[ScreenShot](https://cdn.discordapp.com/attachments/348088106546757653/1228274931460997140/image.png?ex=662b732b&is=6618fe2b&hm=f0b8edc1eaafd22dd9ab225e2e9a5efdba7094021263b8ad153152bf5d6cb741&)
[Video](https://cdn.discordapp.com/attachments/348088106546757653/1228265303209939055/bugsword.mp4?ex=662b6a34&is=6618f534&hm=bd6c031b0fe5bbe3d2acc9e2732bd79fb3759f6aa6a8affc9eeeb9d79e2425a5&)

**System (please complete the following information):**
 - OS: Windows Server
 - Server software PandaSpigot
 - Server Version 1.8.8
 - Plugin Version 23.12

**Additional context**
Nothing.

**Comment by Lsy-291** [comment]
![image](https://github.com/andrei1058/BedWars1058/assets/68882326/0b43c7bf-b848-40a2-9021-1bee1282aabf)

**Comment by andrei1058** [comment]
Panda spigot is not officially supported based on our [compatibity ](https://wiki.andrei1058.dev/docs/compatibility/#supported-server-software)guide.

You could try removing all plugins to see if one of them is causing the issue.

**Comment by Lsy-291** [comment]
> Panda spigot is not officially supported based on our [compatibity ](https://wiki.andrei1058.dev/docs/compatibility/#supported-server-software)guide.
> 
> You could try removing all plugins to see if one of them is causing the issue.
No, I don't think this is just a server core issue, I can still see this problem under spigot

**Comment by Lsy-291** [comment]
> Panda spigot is not officially supported based on our [compatibity ](https://wiki.andrei1058.dev/docs/compatibility/#supported-server-software)guide.
> 
> You could try removing all plugins to see if one of them is causing the issue.

No, I don't think this is just a server core issue, I can still see this problem under spigot
