### ISSUE TITLE
背包满的情况下购买物品会消耗资源但不会将物品给予

### ISSUE THREAD

**Issue by hutuyee** [andrei1058/BedWars1058#1014]
背包满的情况下购买商品(Shop)，会花费资源(resource)，但是物品没有给我
**Describe the bug**

**To Reproduce**

**Expected behavior**

写一个判断，判断玩家的背包是否满格，使玩家不会被消耗资源
**Screenshots**

无
**System (please complete the following information):**
 - OS: Windows 10 22H2
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 23.12.2

**Additional context**

无

**Comment by WitheredWinter** [comment]
U should use English to report bug if the repo's owner speaks English!
你应该用英文来向这个插件的作者报告问题
