### ISSUE TITLE
Enchant aqua affinity and respawn cooldown

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#102]
Pls, add the Aqua Affinity enchant right after starting the game and add a cooldown between the player respawn countdown, because the title is RESPAWNED in the last second along with You will respawn in 1 seconds !,
change it to make these titles separat
![Bez tytułu](https://user-images.githubusercontent.com/94638387/142486048-c3f08c0e-9b4b-498e-9c73-2b26bd0c0c4e.png)

**Comment by ajgeiss0702** [comment]
Please open a seperate issue for the respawned issue.

You should make one suggestion/bug report per issue

**Comment by ajgeiss0702** [comment]
It looks like the issue is because the plugin checks if the subtitle message is empty, and if it is, it doesnt send it. However, it only does this in the code for below 1.9. I can fix this once you open another issue
