### ISSUE TITLE
npc bug

### ISSUE THREAD

**Issue by LuizaumOFC** [andrei1058/BedWars1058#1023]
this bug happened when I put an addon on my bedwars1058. It was like this: I restarted the server, started a game to see if it worked and the NPC disappeared

**System
 - OS: Linux
 - Server software spigot
 - Server Version 1.12.2
 - Plugin Version 21.11.2

**Additional context**
This bug happens every time I add an addon

![2024-05-25_14 21 54](https://github.com/andrei1058/BedWars1058/assets/170823201/9819002f-ee15-4b6f-b28d-c8a9d70199bc)

**Comment by andrei1058** [comment]
update bedwars plugin
