### ISSUE TITLE
Bedwars1058 23.3 API 的IArena无法访问

### ISSUE THREAD

**Issue by comicalpixel** [andrei1058/BedWars1058#1034]
服务端核心 Spigot 1.8.8 

试图通过代码private final List<IArena> arenas = new ArrayList<>();保存游戏，编译时提示"无法访问com.andrei1058.bedwars.api.arena.IArena"。不知道是什么问题，在 BW1058 22.3.4 的API中是可以正常使用的。

**Comment by andrei1058** [comment]
l kmniuhiferi uiywe f ewyfweyb  filfwelibfwe libfwe ui
