### ISSUE TITLE
[BUG|1.20.4]Broken features of Dream Defender and BedBugs

### ISSUE THREAD

**Issue by hoiw** [andrei1058/BedWars1058#1038]
**Describe the bug**
After spawning Dream Defender or bedbugs , the mobs you spawn will attack you,no longer disappear in expected time ,and the nametag works not properly.

**To Reproduce**
1. Go to Shop
2. Buy BedBugs and/or Dream Defender
3. Right-Click to spawn mobs
-->

**Expected behavior**
Spawned the BedBugs and / or Dream Defender , then the BedBugs and / or Dream Defender will spawn with their nametags works properly, and fight other teams instead of who spawned it, then disappered in a time.

**Screenshots**
![2024-08-27_20 10 42](https://github.com/user-attachments/assets/99465b4f-515e-4933-9a48-e6f9dd2132b6)

**System (please complete the following information):**
 - OS: Windows 10 IoT LTSC 2021(19044.4780)
 - Server software :spigot-1.20.4 (from getbukkit.org)
 - Server Version :1.20.4
 - Plugin Version 23.12.2

**Additional context**
Installed Plugins:
Multiworld 5.2.8
Bedwars1058 23.12.2
[latest.log](https://github.com/user-attachments/files/16762009/latest.log)

**Comment by Ican-291** [comment]
Related PR has already been merged and should be fixed in the next version
