### ISSUE TITLE
[BedWars1058] I can't run on your version: CraftServer

### ISSUE THREAD

**Issue by QingHeDou** [andrei1058/BedWars1058#1044]
The plugin version is 24.9 and the server core is Purpur1.21. After starting, the plugin informed me that it does not support running this plugin on Catserver. How can I solve this problem

![屏幕截图 2024-09-07 095812](https://github.com/user-attachments/assets/d83d711c-661e-4956-9a8c-a3a3ba85b350)

**Comment by Ican-291** [comment]
You are using an unofficial supported server core

**Comment by QingHeDou** [comment]
> 您正在使用非官方支持的服务器核心

So, which core should I use

**Comment by Ican-291** [comment]
spigot or paper

**Comment by QingHeDou** [comment]
> 水龙头或纸

But I have the same problem when using paper

**Comment by Ican-291** [comment]
send screenshot

**Comment by QingHeDou** [comment]
> 发送屏幕截图

![Uploading 屏幕截图 2024-09-07 100510.png…]()

**Comment by Ican-291** [comment]
It seems that this image was not uploaded correctly

**Comment by QingHeDou** [comment]
> 这张图片似乎没有正确上传

![屏幕截图 2024-09-07 100510](https://github.com/user-attachments/assets/bb64004b-4d83-42cf-bfac-0dba7d61aedf)

**Comment by Ican-291** [comment]
No, provide version information for the server core

**Comment by QingHeDou** [comment]
> 否，请提供服务器核心的版本信息

![屏幕截图 2024-09-07 100950](https://github.com/user-attachments/assets/86ca51fe-ff26-415b-8377-704a19f430ed)

**Comment by Ican-291** [comment]
24.9?

**Comment by QingHeDou** [comment]
> 24.9?

The plugin version has indeed been updated to 24.9

**Comment by Ican-291** [comment]
I don't remember very clearly. There is also a similar situation in dc, which is indeed a supported version, but Spigot hasn't seen it before. You can try it out

**Comment by ArmyFury** [comment]
minecraft 1.21 is not supported yet, and 24.9 is testing version I believe

**Comment by andrei1058** [comment]
support for mc 1.21 is still work in progress
