### ISSUE TITLE
No materials are produced

### ISSUE THREAD

**Issue by swxhzswxhz** [andrei1058/BedWars1058#1047]
No materials are produced

**Comment by Ican-291** [comment]
wdym

**Comment by swxhzswxhz** [comment]
There are no supplies after the opening, the store has no name, and no floating text is displayed when establishing a venue.

**Comment by Ican-291** [comment]
screenshot

**Comment by swxhzswxhz** [comment]
![image](https://github.com/user-attachments/assets/a2d01276-8f37-4d03-98c4-d60b8badd954)

**Comment by swxhzswxhz** [comment]
![image](https://github.com/user-attachments/assets/23fb58a6-4192-4137-90e1-103e31e6a56a)

**Comment by Ican-291** [comment]
You may not have configured it correctly?

**Comment by swxhzswxhz** [comment]
What's the meaning

**Comment by swxhzswxhz** [comment]
![image](https://github.com/user-attachments/assets/55e051ed-44aa-40b3-af4a-3f8760639433)

**Comment by Ican-291** [comment]
https://wiki.andrei1058.dev/docs/BedWars1058/

**Comment by swxhzswxhz** [comment]
Saw it

**Comment by swxhzswxhz** [comment]
I've already seen it

**Comment by itz-rj-here** [comment]
It is necessary to include information about the platform, plugin version, server jar, and other relevant details before describing your problem.

**Comment by swxhzswxhz** [comment]
Plugin 24.9 server 1.8.8
