### ISSUE TITLE
SlimeWorldManager 

### ISSUE THREAD

**Issue by dvn2200** [andrei1058/BedWars1058#105]
currently they should improve the slimeworldmanager adapter due to its high cpu consumption if possible.
![msedge_IQ2I7sUjDS](https://user-images.githubusercontent.com/29668950/142712406-34382022-c8e0-4f1f-9499-4146b1916ed3.png)

**Comment by minhh2792** [comment]
your hardware maybe just overloaded
how many .slime world are currently loaded in your server ?

**Comment by ajgeiss0702** [comment]
This is not a bedwars issue
