### ISSUE TITLE
bedwars

### ISSUE THREAD

**Issue by akillamrck** [andrei1058/BedWars1058#108]
**Describe the bug**
1: in redwars I set the experience per minute to be 0 but the message that it gives 20 experience per minute keeps popping up.

2: Create an arena with group 3v3v3v3 and restarting the server erased all structures.

3: I was playing and I did / stop on the server and the arena did not restart, it stayed as it was when I did / stop

**Expected behavior**
1: I was expecting the message to be removed.

2: I was hoping that the sand would not be completely removed (structures).

3: I was expecting the arena to restart as it did at the beginning.

**System (please complete the following information):**
 - Server software pape
 - Server Version 1.8.9
 - Plugin Version 21.11.1

**Comment by ajgeiss0702** [comment]
What do you mean by "structures"?

In the future, please dont combine multiple things into one issue

**Comment by akillamrck** [comment]
ok then I will dedicate myself to one problem at a time.

what I say is that when I am in a game in bedwars and I put / stop or the server restarts the arena does not restart it stays like this.

**Comment by ajgeiss0702** [comment]
Are there any errors in the console? Are you using SWM? What other plugins do you have?

This seems more like a request for support rather than a bug report. For support, you can join the discord server. Once we narrow down the issue, if it is a bedwars bug, then usually issues are created here.

**Comment by akillamrck** [comment]
if I am using swm there is no error in the console

**Comment by akillamrck** [comment]
i am using these plugins, I already spoke in the discord and they told me to put this here. https://imgur.com/mLj6DlZ

**Comment by ajgeiss0702** [comment]
You were told to create an issue about the experience thing. From what I can see, the other two issues were not mentioned. 

You should edit your issue to only include that one. We can talk about the other issues on discord until we can be more specific on what the issue is.

**Comment by akillamrck** [comment]
it's okay to be talking to you about discord to solve the problems
