### ISSUE TITLE
NullPointerException on PlayerRespawnEvent

### ISSUE THREAD

**Issue by reussy** [andrei1058/BedWars1058#113]
**Describe the bug**
I have installed PowerfulPerms and set a prefix for the groups, when I kill a player in game and it is end kill game the player can reappear again when it should not be like this

It's a bit confusing, it only happens to me when I have PowerfulPerms

**It only happens when it is a final kill
I don't have any chat plugins**

**Stracktrace:** https://paste.md-5.net/lopokohinu.cs

**To Reproduce**
1. Install PowerfulPerms and set prefix for groups
2. Join a game, break a enemy bed and kill him

**Expected behavior**
Winning the game correctly

**Screenshots**
![imagen_2021-11-22_123640](https://user-images.githubusercontent.com/63428864/142916619-9e968d9f-e539-44fb-84d0-d13d11047040.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software PaperSpigot
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Comment by ajgeiss0702** [comment]
I believe this is an issue with PowerfulPerms returning null when it shouldnt. Have you contacted them?

**Comment by reussy** [comment]
> I believe this is an issue with PowerfulPerms returning null when it shouldnt. Have you contacted them?

There is no more support for the plugin, for the moment it can be closed
