### ISSUE TITLE
Fireballs need config and more features

### ISSUE THREAD

**Issue by Sohqil** [andrei1058/BedWars1058#121]
**Is your feature request related to a problem? Please describe.**
Fireballs need a config to edit the knockback cooldown and damage

Currently there is no option for editing this things and it's not available right now!

On Hypixel fireball cooldown is 0.5s and the message is "Please wait 0.5s to use that again!"
I don't exactly know what is the fireball knockback but the damage is current damage / 5 (event.getDamage() / 5)
![2021-11-24_00 14 17](https://user-images.githubusercontent.com/91290611/143131345-354120c7-a05f-430d-8b88-016fe7d15850.png)

**Comment by reussy** [comment]
ajgeiss already made a pr, awaiting for approval. The cooldown is still pending I think

#99

**Comment by ajgeiss0702** [comment]
Added in 21.11.2
