### ISSUE TITLE
Add setRespawnTime() in PlayerReJoinEvent

### ISSUE THREAD

**Issue by Sohqil** [andrei1058/BedWars1058#122]
I would like to set the respawn time to 10 seconds when a player joins the server because on Hypixel rejoin time is 10 seconds

```java
@EventHandler
    public void onPlayerRejoin(PlayerReJoinEvent e) {
        e.setRespawnTime(10);
}
```

**Comment by ajgeiss0702** [comment]
You can change the respawn countdown length in the config

**Comment by Sohqil** [comment]
> You can change the respawn countdown length in the config

The respawn countdown in the config changes all the respawn time. I only want to set the Respawn time when the player reconnects

**Comment by andrei1058** [comment]
Yeah, could be useful.
