### ISSUE TITLE
Multiarena Lobby Scoreboard Problem

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#129]
**Describe the bug**
If you disable the lobby scoreboard on multiarena mode, and you join on arena, leave and join again you will get kicked out from the network. An error on BungeeCord will appear: "Team already exists in this scoreboard"

**To Reproduce**
1. Go to config.yml
2. Set enable-lobby-sidebar: to false
3. Restart the server
4. Join on a random arena
5. Leave the arena
6. Join again on a random arena

**Expected behavior**
You should not get kicked

**Screenshots**
-

**System (please complete the following information):**
 - OS: Debian 10
 - Server software Testerd with paper spigot / ispigot
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Additional context**

**Comment by ProtoGhost** [comment]
having same isssue wating for patch

**Comment by ProtoGhost** [comment]
when this issue will be fixed?

**Comment by andrei1058** [comment]
some team-removal timig issues I guess

**Comment by andrei1058** [comment]
Relates to #211

**Comment by andrei1058** [comment]
Notes:
- PlayerList_<nmsv>#sendRemove action 1
- Siderbar_<nmsv>#playerListCreate must send removal if exists
