### ISSUE TITLE
Potion problem

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#130]
when I have a potion in my hand while buying in the store, it automatically consumes itself in a shorter amount of time.

**Expected behavior**
The potion should not be consumed

 - Server software [spigot]
 - Server Version [1.8.8]
 - Plugin Version [21.10.1]

https://user-images.githubusercontent.com/94638387/143472584-979a5937-28be-40f3-b188-fda3d59e2b01.mp4

.

**Comment by Askarionn** [comment]
Try using 21.11.1

**Comment by Adamek038271** [comment]
I'm wrong I'm using the latest version

**Comment by ajgeiss0702** [comment]
I am unable to reproduce this.

I tried on both 1.8.9 and 1.16.4.

Both times the shop opened without drinking the potion.

This is probably a client issue (as I see you have a modded client)

**Comment by andrei1058** [comment]
What client is that? So we can make a fix testing with it

**Comment by ajgeiss0702** [comment]
Closed because no response
