### ISSUE TITLE
Generators problem

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#131]
diamond generators often do not display holograms

**Screenshots**
![image](https://user-images.githubusercontent.com/94638387/143492814-52d5aaaa-43a7-460e-b7b5-83605e7faa18.png)

 - Server software [spigot]
 - Server Version [1.8.8]
 - Plugin Version [21.10.1]

**Comment by Askarionn** [comment]
Try to use 21.11.1

**Comment by Adamek038271** [comment]
I'm wrong I'm using the latest version

**Comment by andrei1058** [comment]
Try removing any clear-lag related plugin and let us know if it still occurs

**Comment by andrei1058** [comment]
Try removing any clear-lag related plugin and let us know if it still occurs

**Comment by andrei1058** [comment]
Try removing any clear-lag related plugin and let us know if it still occurs

**Comment by ajgeiss0702** [comment]
Closing due to no response (and probably just another plugin messing with bedwars stuff anyway)
