### ISSUE TITLE
Generators stopped by breaking the team bed

### ISSUE THREAD

**Issue by reussy** [andrei1058/BedWars1058#133]
**Reported by Cyborg**

**Describe the bug**
When someones bed gets destroyed their gen stops

**To Reproduce**
1. Use latest bw1058 plugin.
2. Try playing with 2 players because it wont work on single player.
3. destroy other persons bed and their gen would stop working

**Expected behavior**
the generators should still be working when bed gets destroyed (this issue was not there in older versions for me).

**System (please complete the following information):**
 - OS: -
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Comment by TrianglyRU** [comment]
I noticed this behaviour if disable-generator-for-empty-teams is enabled in arena's config. Also could be another bug as the team without the bed shouldn't be counted as non-existent one
