### ISSUE TITLE
Modify the amount of emeralds and diamonds that the generators give

### ISSUE THREAD

**Issue by YuriXD** [andrei1058/BedWars1058#136]
**Is your feature request related to a problem? Please describe.**
I would like to modify the amount of emeralds and diamonds that the generators give in each cycle of time.

**Describe the solution you'd like**
To be able to modify the amount of emeralds and diamonds that the generators give, as in the gold and iron generators

**Comment by Askarionn** [comment]
You already can do that from "generators.yml" file
