### ISSUE TITLE
[BedWars1058] Task #19 for BedWars1058 v${gitVer}21.11.1 generated an exception

### ISSUE THREAD

**Issue by Teals53** [andrei1058/BedWars1058#137]
![image](https://user-images.githubusercontent.com/13446881/143656655-e61e099e-363d-456c-9fd5-3c79f9999536.png)

**Comment by minhh2792** [comment]
please follow the bug report template

**Comment by PikaMug** [comment]
Also getting this on a fresh install.

Likely duplicate of #101

**Comment by Teals53** [comment]
> please follow the bug report template

why its giving this error on a fresh install i not need to do anything for take this error xd

**Comment by andrei1058** [comment]
It happens because 1.17 is not supported yet. sorry

**Comment by Teals53** [comment]
aight thx i thought its supported cuz i see this version in spigot ^^
