### ISSUE TITLE
Team upgrades gui not updating

### ISSUE THREAD

**Issue by FabrisNick** [andrei1058/BedWars1058#14]
**Describe the bug**
When I purchase a team update, the GUI does not update, I have to close and reopen it.

**To Reproduce**
1. Go to the Team Upgrades NPC
2. Purchase an upgrade

**Expected behavior**
I expect the gui to update showing me that I bought the upgrade

**System (please complete the following information):**
 - OS: Windows 11
 - Server software NachoSpigot 
 - Server Version 1.8.8
 - Plugin Version 21.10.1

**Comment by andrei1058** [comment]
Isn't the upgrades thing supposed to close once you buy somethig? Are you using any addons?

**Comment by FabrisNick** [comment]
> 
> 
> Isn't the upgrades thing supposed to close once you buy somethig? Are you using any addons?

Nope, i'm just using BW1058, SWM and TAB

**Comment by minhh2792** [comment]
Same issue, latest BW1058 version with Paper 1.12.2

**Comment by ajgeiss0702** [comment]
Apparently its supposed to stay open when you buy something
