### ISSUE TITLE
Villager Facing Backward

### ISSUE THREAD

**Issue by ThinkGeoduck** [andrei1058/BedWars1058#143]
**Describe the bug**
The items shop's npc faces Backward.

**To Reproduce**
1. Setup an Arena
2. Play that arena using debug or with your friends

**Expected behavior**
The shop villager will be facing backwards whereas the upgrade's villager will face to the front
(IDK I guess its only happening to me)

**Screenshots**
![image](https://user-images.githubusercontent.com/73486733/143992578-c174f113-70ef-4a38-8acb-99880ac8d13f.png)
![image](https://user-images.githubusercontent.com/73486733/143992626-d6035029-84a3-4809-b374-858e90d5f3c2.png)

**System**
 - OS: Windows 10 (Mine)
 - Server software: Spigot, Bukkit
 - Server Version: 1.8.8 [Via Version]
 - Plugin Version: Bedwars-1058 vgit-1d5584be-21.5.3-SNAPSHOT

**Additional context**
none.

**Comment by ajgeiss0702** [comment]
The issue was the old version
