### ISSUE TITLE
Tab sorter

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#146]
**Describe the bug**
Teams are not sorted correctly on tab

**To Reproduce**
1. Join a arena
2. Press tab
3. See error

**Expected behavior**
Teams should be sorted correctly not random

**Screenshots**
https://imgur.com/a/4zlqx02

**System (please complete the following information):**
 - OS: Debian 10
 - Server software Paper
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Additional context**
-

**Comment by ajgeiss0702** [comment]
This is not a bug, this is a feature request

**Comment by andrei1058** [comment]
I'm working on that

**Comment by LeSGYT** [comment]
I hope that this gets fixed soon

**Comment by tomkeuper** [comment]
Closed as merged

**Comment by tomkeuper** [comment]
Mistook a closed for merged

**Comment by andrei1058** [comment]
@tomkeuper but it works by default with the new sitebar lib
