### ISSUE TITLE
Can't take items from generator

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#147]
**Describe the bug**
Sometimes when arena start you can't take the items from generator, you have to kill yourself to be able to take the items.

**To Reproduce**
1. Join a arena
2. Try to take the items from generator
3. See error
4. THE PROBLEM IT'S HAPPENING RANDOM, NOT EVERYTIME

**Expected behavior**
You should be able to take the items from generators

**Screenshots**
https://cdn.discordapp.com/attachments/912821691997122601/914142375402672138/unknown.png

**System (please complete the following information):**
 - OS: Debian 10
 - Server software Paper
 - Server Version 1.8.8
 - Plugin Version 21.11.1

**Additional context**
-

**Comment by ajgeiss0702** [comment]
This is most likely a plugin conflict. In the future, please ask in the discord before creating issues.
