### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by SofyanTauridOdeMadi** [andrei1058/BedWars1058#16]
no, this suggestion is just to add some features and maybe not very important but it would be nice to add.

My suggestion about this form of Animation for Bedwars is starting from the player entering the game and Done

As :

Players join from the arena: there are particles or titles or boost bars
Players leave the arena: there are particles or titles or boosbars
The game starts: there are particles or 5 second healing effect or something
Dead players: there is a dark effect
Respawn players: there is a healing effect
Players kill other players: there is a dark effect
and other animations

**Comment by andrei1058** [comment]
there's a template you must fill in
