### ISSUE TITLE
Bungee utf-8(Chinese) server can't join

### ISSUE THREAD

**Issue by FootClick** [andrei1058/BedWars1058#167]
Describe the bug
I use Chinese server name for bungee config
Bedwarsproxy left click arena connection does not respond. When bungee config is in English, it can be transmitted smoothly

Expected behavior
Chinese servername (bungee config server) cannot be transferred

Screenshots
![20211204121700](https://user-images.githubusercontent.com/95486902/144716113-889bc1a6-4b00-4a88-96a4-10a7b96c642f.jpg)

System (please complete the following information):
 - OS: [Windows]
 - Server software [WaterFall]
 - Server Version [1.8.8]
 - Plugin Version [21.11.2]
 - Plugin BedwarsProxy Version [1.2.4]

Additional context
No

**Comment by ajgeiss0702** [comment]
Can you give an example of a server name that is not working? That way we can reproduce the issue easier

**Comment by FootClick** [comment]
> 你能举一个不工作的服务器名称的例子吗？这样我们就可以更容易地重现问题

Left click cannot be teleport to the arena

**Comment by PikaMug** [comment]
Pretty sure this can be resolved by replacing instances of

`yml = YamlConfiguration.loadConfiguration(config);`

with

`yml = YamlConfiguration.loadConfiguration(new InputStreamReader(new FileInputStream(config), StandardCharsets.UTF_8));`

in ConfigManager.java, but I'd like a second opinion.

**Comment by andrei1058** [comment]
@FootClick can you provide us the Chinese text so we can make some tests?

**Comment by FootClick** [comment]
> @FootClick能否提供中文文本以便我们进行一些测试？
[config.zip](https://github.com/andrei1058/BedWars1058/files/7775415/config.zip)
 Start parameter add -Dfile.encoding=UTF-8

**Comment by andrei1058** [comment]
Have you tried encoding your file in UTF-8 in Notepad++ first? From what I see it should use UTF-8 by default if it was encoded that way. @FootClick 

In alternative add this to your `java -jar` command:
`-Dfile.encoding=UTF-8`

**Comment by PikaMug** [comment]
> In alternative add this to your `java -jar` command: `-Dfile.encoding=UTF-8`

OP was already using -Dfile.encoding=UTF-8 (see their last comment).
