### ISSUE TITLE
Remove loading screen when you died

### ISSUE THREAD

**Issue by SunshroomChan** [andrei1058/BedWars1058#168]
**Is your feature request related to a problem? Please describe.**
Yes because its annoying
**Describe the solution you'd like**
As playing on Minecraft Bedrock Client by using GeyserMC, when you died it always show loading screen and that would make your crash the game on Bedrock Client, wish developer of this plugin fix this!
Thanks
**Describe alternatives you've considered**
No
**Additional context**
No

**Comment by andrei1058** [comment]
HOW AM I SUPPOSED TO REMOVE A RESPAWN SCREEN FOR A CLIENT THIS PLUGIN WASN'T MADE FOR? THIS IS JAVA EDITION! SO IF YOU WANT A FIX FOR THIS REEFER TO YOUR PROCTOCOL COVERTER DEPENDENCY COMMUNITY! THANKS
