### ISSUE TITLE
Spectator can push the iron golem in the game

### ISSUE THREAD

**Issue by minhh2792** [andrei1058/BedWars1058#17]
**Describe the bug**
Spectator can push the iron golem in the game

**To Reproduce**
1. Get killed by a player and then become a spectator
2. Player in the lobby spectate the game

**Expected behavior**
Spectator can't push the iron golem

**System:**
 - OS: Ubuntu 20.04.3 LTS
 - Server software PaperMC
 - Server Version 1.12.2
 - Plugin Version 21.10.1

**Comment by andrei1058** [comment]
You need to configure ViaVersion a bit. Try reading their scoreboard-related documentation.

**Comment by minhh2792** [comment]
How can this related to scoreboard ?

**Comment by andrei1058** [comment]
Because Minecraft sends a team pushing rule packet to the client, and teams are handled on the scoreboard. We've already seen this issue in the past and simply fixed it by configuring collisions. You may also have something in spigot.yml, but check via version configuration first. I will look into that myself later today and I will put it on a FAQ.

**Comment by minhh2792** [comment]
I don't get it, Via Version didn't have any configuration related to scoreboard. I also tried to disable player collisions but I still have the same issue. How do I actually configuring collisions ?
@andrei1058

**Comment by andrei1058** [comment]
Next time inform yourself..

```
auto-team - default: true (Boolean)

Most servers don't use scoreboard plugins, in this case we send our own team to the player to prevent them colliding with other players. If you use a plugin like ColoredTags you should turn this off. Furthermore if you are having issues with Bungee and teams, consider turning it off too.
```
Source: [https://viaversion.atlassian.net/wiki/spaces/VIAVERSION/pages/54100070/Configuration](https://viaversion.atlassian.net/wiki/spaces/VIAVERSION/pages/54100070/Configuration)

If setting this to false does not solve it, put `prevent-collision` on false as well.

**Comment by minhh2792** [comment]
still have the same problem, i tried but it didn't work, maybe Via version issue
