### ISSUE TITLE
SHARED mode but not working and things are coming in other worlds :{

### ISSUE THREAD

**Issue by xmyoard** [andrei1058/BedWars1058#175]
the items like chest and bed not there :<
![2021-12-06_14 05 51](https://user-images.githubusercontent.com/87631878/144816749-746365f8-ebc8-47ea-90cc-cd18f15dc9de.png)

and also when joining a game it kicks and says a message:
![2021-12-06_14 08 01](https://user-images.githubusercontent.com/87631878/144816819-ce85f8c6-8f55-46f1-9023-ba2c98d53efb.png)

**Comment by xmyoard** [comment]
this happens when using SHARED, but in MULTIARENA some other problem is coming

**Comment by ajgeiss0702** [comment]
Shared mode does not have items, only the scoreboard in the lobby world.

As for the other issue, is there an error in the console?

**Comment by Aadi-mone** [comment]
no issues in console

**Comment by xmyoard** [comment]
No, I have set it to shared, and the lobby items comes in worlds like skywars, which it should not be!
please help!

**Comment by andrei1058** [comment]
rename this pls

**Comment by ajgeiss0702** [comment]
Make sure you restarted the server after changing to shared mode, and that you cleared the items out of your inventory.

**Comment by xmyoard** [comment]
Yes I did, but even tho its not working :/

**Comment by andrei1058** [comment]
how do you start playing skywars? or how do you exactly go on a skywars map? any ways to reproduce it? what's your skywars plugin?

**Comment by xmyoard** [comment]
i have set up a command, when we do /hub we gets tp-ed to the hub world, then we'll use a game join gui to join skywars or else `/sw join mapname` but still the bedwars items comes in other worlds
