### ISSUE TITLE
[CRITICAL] Bungee mode memory leaks.

### ISSUE THREAD

**Issue by ItzZisker** [andrei1058/BedWars1058#178]
**Describe the bug**
the isOnABase weakhashmap located at package com.andrei1058.bedwars.arena.upgrades, class BaseListener.java is including objects, which preventing the WorldServer(NMS)/or/CustomWorldServer(SWM) class to being removed after being unloaded, next gc. i tested using sout and added loggers to the plugin, the shocking fact is, the player objects won't being removed when they disconnected, they always stay there, but in multiarena mode, it works with no problems and removed automatically.

**To Reproduce**
so i fixed this myself, by adding a new hashmap, getting the players with their teams, putting them in hashmap, and remove them from isOnABase when the game stops. 

**Expected behavior**
The char[] & byte[] arrays including Chunk data shouldn't be on top usage with 3GB(s) difference, this is probably a memory leak!, this won't happen on multiarena mode.

**Screenshots**
https://media.discordapp.net/attachments/348088106546757653/917719615893807114/Screenshot_20211207_170819.png

**System**
 - OS: Arch Linux (Kernel: 5.14.6-arch1-1)
 - JRE: AdoptOpenJDK-hotspot-jre-8-latest
 - Server software: Spigot, TacoSpigot, PaperSpigot.
 - Server Version: 1.8.8
 - Plugin Version: 21.11.1

**Additional context**
fix:
![Screenshot_20211207_191303](https://user-images.githubusercontent.com/68909399/145027254-24f34215-28af-4cd5-abb4-a7917a72e3f0.png)

**Comment by PikaMug** [comment]
This should be submitted in the form of a Pull Request.

**Comment by ajgeiss0702** [comment]
There is a `destroyData` method in Arena. If you are destroying data for the arena, you should probably put it there.

Also, it looks like it is already cleared when a player exits the arena, but not if they leave mid-game. So the solution would probably also remove it when they leave.

**Comment by ItzZisker** [comment]
> There is a `destroyData` method in Arena. If you are destroying data for the arena, you should probably put it there.
> 
> Also, it looks like it is already cleared when a player exits the arena, but not if they leave mid-game. So the solution would probably also remove it when they leave.

Thank you
