### ISSUE TITLE
Please add the level_up sound that plays when someone is killed or hitted into the void.

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#182]
What can i even say more than this.
If you are not dump you did understand and reply to this thread.
If you are dump see this video-https://youtu.be/2h0tACfsVHQ

**Comment by minhh2792** [comment]
You can use my simple addon https://www.spigotmc.org/resources/bedwars1058-killsound.97743/

(1.12.2+ only, if you want support for 1.8, please clone the source code and change the sound)

**Comment by ghost** [comment]
> You can use my simple addon https://www.spigotmc.org/resources/bedwars1058-killsound.97743/
> 
> (1.12.2+ only, if you want support for 1.8, please clone the source code and change the sound)

Thanks but it would have been cool if it was inbuild then it would have worked in 1.8-1.11
