### ISSUE TITLE
Customizable Tab

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#183]
**Describe the solution you'd need
Please add custom tab support so that there is no need for third party plugins for tab and will work perfectly with Nick plugins and Perms plugin prefix and suffix

**Comment by ghost** [comment]
If this is not enough then what is.
It will be dump if you didn't understand what i am telling

**Comment by ajgeiss0702** [comment]
You already can customize the prefixes and suffixes of players. If you want header/footers, use another plugin for that.
