### ISSUE TITLE
Shop items dont have custom name

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#184]
When an item is configured as With name {color}Compact PopUp Tower it changes to chest after bought from shop.

**Comment by andrei1058** [comment]
You should check it on the Wiki because it doesn't work like this

**Comment by ajgeiss0702** [comment]
You can add custom names in the shop config

**Comment by ghost** [comment]
sorry @ajgeiss0702 I didnt knew that time i was a noob at config
