### ISSUE TITLE
Shout Command Doesn't work

### ISSUE THREAD

**Issue by ErshGem** [andrei1058/BedWars1058#19]
The shout command doesn't work with Essentials, and I need it for my server 

I tried to disable the Essentials shout command, it doesn't work 
Here's a video showing what I'm doing- https://youtu.be/ufskHmiQrbc

**Comment by ItzZisker** [comment]
first, make sure you are running spigot or paper:
open commands.yml in server's root:
edit it like that:

```
aliases:
  shout:
    - essentials:shout $1-
```

that should force the "/shout" command to run as "/essentials:shout"

**Comment by andrei1058** [comment]
Please use the bug template next time. The issue seems to be Essentials though.. because broadcast is from essentials. Have you restarted the server to apply changes?

**Comment by DieselJS** [comment]
As that is the default Essentials broadcast command formatting, I'd assume you haven't removed the Essentials /shout alias for /broadcast. You need to find and remove this alias, or overwrite it to use the BedWars1058 one.
