### ISSUE TITLE
Can't run on v1_18_R1

### ISSUE THREAD

**Issue by aamche** [andrei1058/BedWars1058#192]
[12:08:53] [Server thread/INFO]: [BedWars1058] Loading BedWars1058 v21.11.2
[12:08:53] [Server thread/ERROR]: [BedWars1058] I can't run on your version: v1_18_R1

**To Reproduce**
1. Update to Spigot/Minecraft 1.18.1
2. Plugin version BedWars1058 - OpenSource 21.11.2

Probably needs a compatibility update with the rush release of 1.18.1 due to java log4j vulnerability.

**Comment by ajgeiss0702** [comment]
Bedwars doesn’t support 1.17 or 1.18 yet. Support is in the works (will probably be in the next update)

**Comment by aamche** [comment]
Ah ok, fair enough to close. Worked nicely on 1.17.1 for some reason.
