### ISSUE TITLE
Custom items in inventory after ended game

### ISSUE THREAD

**Issue by NovaPixell** [andrei1058/BedWars1058#200]
**Describe the bug**
The user has several items in their inventory with the name "custom363" or similar, such as iron and gold.

**To Reproduce**
1. According to the user, he was teleported by a user, in a game that just ended.
2. As soon as he was teleported to the lobby, he got this inventory with the random items.

**Expected behavior**
The user has several items in their inventory with the name "custom363" or similar, such as iron and gold.

**Screenshots**
![2fe5025cf5ba3527cd1d150bdd3c85d6](https://user-images.githubusercontent.com/55632135/146379881-dacda41c-4ae9-4aff-8a43-c263e9f6d885.png)

**System (please complete the following information):**
 - OS: Linux
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 21.11.2 - MULTI ARENA

**Comment by ajgeiss0702** [comment]
Can you send the log from when this happened? (Obviously redact sensitive information such as IPs)

**Comment by NovaPixell** [comment]
> Can you send the log from when this happened? (Obviously redact sensitive information such as IPs)

Unfortunately I don't know how to find the log. I have seen this problem during the first opening with almost 200 users.
What can I look for in the log file?

**Comment by andrei1058** [comment]
I don't think you are using spigot as server software :) send us an output of /version

**Comment by ajgeiss0702** [comment]
Closing because of no response
