### ISSUE TITLE
SQL time out issue

### ISSUE THREAD

**Issue by MherZaqaryan** [andrei1058/BedWars1058#21]
**Describe the bug**
SQL time out issue on MySQL
LOG: https://sourceb.in/S2Pnkxf107

**To Reproduce**
1. Join the server
2. Leave from the server.
3. See an error https://sourceb.in/S2Pnkxf107

**Expected behavior**
No error on the console and the data should be saved!

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.8.9
 - Plugin Version 21.10.1

**Comment by andrei1058** [comment]
That's MySQL

**Comment by HEMO313** [comment]
> That's MySQL

i have the same problem
