### ISSUE TITLE
Team RandomlyPending already exists in this scoreboard 1.18

### ISSUE THREAD

**Issue by mgmadnesstv** [andrei1058/BedWars1058#211]
**Describe the bug**
I setup the BedWars Arena. When we go to Play the game will Start, but will then kick us straight to the Hub server of my Network. 

**To Reproduce**
1. Setup an Arena
2. Start Join the game
3. Wait for the game to start or Forcestart it. 
4. You will see the bug

**Expected behavior**
I expect the game to Start with no issue.

**Screenshots**
Video: https://www.youtube.com/watch?v=RMEGgPw0t2M
Screenshot of Console: http://images.envysmp.net/images/r8zng.png

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.18.1
 - Plugin Version 21.12.1

**Additional context**
From what it looks like in the Screenshot it looks like the world is failing to load but I could be wrong

**Comment by mgmadnesstv** [comment]
Tried running this on a local Machine. Same setup. Server works fine.. could it be something to do with Bungee?

**Comment by mgmadnesstv** [comment]
There seems to be errors in the Proxy console too when a player gets kicked. Only just realised this today https://pastebin.com/p1iWXms0

**Comment by andrei1058** [comment]
it's the minecraft version. avoid using 1.17 and 1.18 for now

**Comment by andrei1058** [comment]
Relates to #129

**Comment by andrei1058** [comment]
From what I can see it was a bad implementation on 1.18

**Comment by mgmadnesstv** [comment]
Okay, will this be patched in the next update?

**Comment by andrei1058** [comment]
just finished the sidebar patch. contact me on discord to get the fixed jar
