### ISSUE TITLE
Bridge egg cooldown

### ISSUE THREAD

**Issue by FootClick** [andrei1058/BedWars1058#212]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like
Add cooldown to the bridge egg like a fireball.

Describe alternatives you've considered
No. like a hypixel

Additional context
I didn't find the picture

**Comment by andrei1058** [comment]
What's the cooldown on HP?

**Comment by FootClick** [comment]
> HP的冷却时间是多少？

1s

**Comment by FootClick** [comment]
![20211225114345](https://user-images.githubusercontent.com/95486902/147376889-7948693d-b430-4441-a485-5870ef606624.png)
