### ISSUE TITLE
Fireball not working on 1.12

### ISSUE THREAD

**Issue by minhh2792** [andrei1058/BedWars1058#214]
**Describe the bug**
Fireball didn't work on version 21.12.1, when I right click it didn't even destroy block or deal damage to player

Here is the video: https://youtu.be/ZmcrdrcJSHo

**To Reproduce**
1. Install BedWars1058 21.12.1 (Downloaded from Polymart)
2. Join a game
3. Buy fireball from shop
4. Facing this issue

**Expected behavior**
Fireball should work fine

**System (please complete the following information):**
 - OS: Ubuntu 
 - Server software: PaperMC
 - Server Version: 1.12.2
 - Plugin Version: 21.12.1

**Comment by ajgeiss0702** [comment]
What plugins do you have?

**Comment by minhh2792** [comment]
> What plugins do you have?

I have Viaversion, placeholder api, holographic display, gensplit addon

**Comment by ajgeiss0702** [comment]
Are you sure those are the only plugins you have?

**Comment by minhh2792** [comment]
> Are you sure those are the only plugins you have?

Yeah I'm sure

**Comment by FabrisNick** [comment]
From what I see in the video you also have Essentials, so I don't think those are the only plugins you have

**Comment by ajgeiss0702** [comment]
Please send the output of /plugins and /version

**Comment by ghost** [comment]
Actually I too have this problem

**Comment by ajgeiss0702** [comment]
> Actually I too have this problem

Can you send your /plugins and /version?

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
FastAsyncWorldEdit, Essentials, SlimeWorldManager, EssentialsChat, PlaceholderAPI, PlugMan, ViaVersion, Vault, ViaBackwards, ProtocolLib, ViaRewind, WorldEdit, OldCombatMechanics, Parties, BedWars1058, BedWars1058-GenSplit, BedWars1058-Sponge, BedWars1058-Compass, BedWars1058-ArenaSetup, BedWars1058-TeamSelector

**Comment by ghost** [comment]
spigot version 1.12.2
plugin version 21.12.1

**Comment by minhh2792** [comment]
> From what I see in the video you also have Essentials, so I don't think those are the only plugins you have

Essentials did nothing so I think it's not necessary, I also tested with out Ess

**Comment by ajgeiss0702** [comment]
Try with __only__ bedwars1058

**Comment by reussy** [comment]
It's work fine for me without Essentials

**Comment by minhh2792** [comment]
> Try with **only** bedwars1058

I still have the same problem

**Comment by ghost** [comment]
This problem exists for server version 1.12.2
No other version has this problem

**Comment by minhh2792** [comment]
Oh god

**Comment by ajgeiss0702** [comment]
I am able to reproduce this on a 1.12.2 paper server with only bedwars. Ill investigate more

**Comment by minhh2792** [comment]
Thank you

**Comment by minhh2792** [comment]
Clean server with Papermc 1.12.2, only Bedwars1058 and fireball still don't work
![image](https://user-images.githubusercontent.com/63439671/147404863-d9be30c1-57cb-4dd1-a353-4b3f7c759236.png)
