### ISSUE TITLE
Bridge Egg Not Working

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#216]
**Describe the bug**
The Bridge Egg just works like a normal egg

**To Reproduce**
1.Run spigot 1.12.2
2.Bedwars1058-21.12.1
3.Join a game
4.Buy bridge egg
5. throw it
6. you see the bug

**Expected behavior**
Make a bridge

**Screenshots**
None

**System (please complete the following information):**
 - OS: Windiws
 - Server software Spigot
 - Server Version 1.12.2
 - Plugin Version 21.12.1

**Additional context**
PLEASE FIX IT!!!!!!!!!!!!!!

**Comment by andrei1058** [comment]
provide a video

**Comment by ghost** [comment]
Ok i will provide video

**Comment by ghost** [comment]
https://youtu.be/heileGepow0 here is the video

**Comment by ajgeiss0702** [comment]
The video is private

**Comment by ghost** [comment]
Now its public

**Comment by ghost** [comment]
Hello

**Comment by ajgeiss0702** [comment]
Works fine for me. try with __only__ bedwars1058 installed

**Comment by ghost** [comment]
Then my Hypixel remake wont work perfectly
also use 1.12 or lower version it has bug

**Comment by ajgeiss0702** [comment]
bedwars1058 doesnt require anything so the game will still start.
I've tested on both 1.12 and 1.8 and on both the bridge egg worked fine

**Comment by ghost** [comment]
stilll but i will assume it wont be fixed XD

**Comment by ajgeiss0702** [comment]
Why do you assume that?

**Comment by ghost** [comment]
IDK XD

**Comment by ghost** [comment]
Now the bridge egg just comes in middle way.
like i mean the bridge egg makes a bridge like 10-20 blocks far from thrower

**Comment by tomkeuper** [comment]
Is this still happening on the latest version?
