### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#223]
**Describe the bug**
After setting up an arena and restarting it my server crashes.
After the second restart, the server does not crash, it just blocks the ability to send chat messages and prints the same errors as during the crash

**To Reproduce**
1. Setup a new arena
2. Restart the server
3. Join the server
4. See server crash report
5. Restart the server again
6. Join the server
7. See stacktraces

**Expected behavior**
Not crashing and printing stacktraces?

**Screenshots**
![image](https://user-images.githubusercontent.com/69810642/147167036-76b09356-bb80-4edb-b3ca-ac3162c1e4bb.png)

**System (please complete the following information):**
 - OS: Linux (Ubuntu Server 21.10)
 - Server software Purpur (switched to Paper, but nothing has changed)
 - Server Version 1.18.1
 - Plugin Version `${gitVer}21.12.1`

**Additional context**

Crash report: https://mclo.gs/TTzZC7m
Console stacktrace: https://mclo.gs/R6LNs3m
After second restart (without crash): https://mclo.gs/SNYuOCP

**Comment by andrei1058** [comment]
Thanks for reporting this! It is related to my sidebar library which was not tested yet on 1.17 and 1.18. We're working on it!

**Comment by hmmm3e3r** [comment]
> Thanks for reporting this! It is related to my sidebar library which was not tested yet on 1.17 and 1.18. We're working on it!

For mee to,so is this bug soon fixed??? or what can i do to fix it

**Comment by andrei1058** [comment]
provide your lobby items configuration from config.yml

**Comment by andrei1058** [comment]
Relates to #210

**Comment by jeslinmx** [comment]
> > Thanks for reporting this! It is related to my sidebar library which was not tested yet on 1.17 and 1.18. We're working on it!
> 
> For mee to,so is this bug soon fixed??? or what can i do to fix it

In config.yml, find all instances of `material: PLAYER_HEAD` and change it to another item. Since by default it's used to show player stats, I've opted to temporarily change it to book and quill (`material: WRITABLE_BOOK`).

@andrei1058 I guess until this PR makes it into a release, we can't use player heads as icons (and even then we should avoid it, since from your code I'm seeing that it's just a hotfix with the risk of rate limitation)?
