### ISSUE TITLE
Chat format in spectator didn't work

### ISSUE THREAD

**Issue by minhh2792** [andrei1058/BedWars1058#224]
**Describe the bug**
Chat format in spectator didn't work, it become the minecraft default format

**To Reproduce**
1. Join a game
2. Break someone bed and kill them
3. That player will now in spectator mode
4. That player gonna chat something

**Expected behavior**
Chat format should work fine

**System:**
 - OS: Ubuntu
 - Server software: PaperMC 1.12.2
 - Server Version: 1.12.2
 - Plugin Version: 21.12.1

**Additional context**
Error in the console
![image](https://user-images.githubusercontent.com/63439671/147208847-cc248ec5-c5dd-4a8c-9c4e-a68eb061bcdf.png)

Player "CursedKiwi2792" is in spectator mode, getting this error after sending message

I also look at PlayerChat.java:78 and I found this but don't know what `%2$s` mean
![image](https://user-images.githubusercontent.com/63439671/147209019-f42ffc06-b220-4e50-b71c-62c43f9ddc87.png)

**Comment by andrei1058** [comment]
Provide server log and plugin list

**Comment by minhh2792** [comment]
Still having this issue so I have to reopen it, here is the plugin list.
I tested with Paper 1.12 and still facing the same problem, same error log above.
Older version also having this problem.

![image](https://user-images.githubusercontent.com/63439671/147436784-11d464fa-ca7c-4dcb-939c-0ff298272cd3.png)

**Comment by minhh2792** [comment]
Update: PlaceholderAPI issue
If you are having this problem, try downgrade the placeholderapi plugin
