### ISSUE TITLE
PAPI and bug!!!

### ISSUE THREAD

**Issue by dyslmj** [andrei1058/BedWars1058#226]
希望能增加竞技场状态的运算符
Would like to add the arena state operator and Fireballs do not propel or break blocks in spigotmc 1.8.8. in the BedWars-21.11.2 version if it breaks the blocks but the explosion was not propelling.
The following variables are very unstable and error prone in TRHD!

'&e1. &b%ajleaderboards_board_bw1058_player_level_raw_1_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_1_value%'
'&e2. &b%ajleaderboards_board_bw1058_player_level_raw_2_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_2_value%'
'&e3. &b%ajleaderboards_board_bw1058_player_level_raw_3_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_3_value%'
'&e4. &b%ajleaderboards_board_bw1058_player_level_raw_4_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_4_value%'
'&e5. &b%ajleaderboards_board_bw1058_player_level_raw_5_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_5_value%'
'&e6. &b%ajleaderboards_board_bw1058_player_level_raw_6_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_6_value%'
'&e7. &b%ajleaderboards_board_bw1058_player_level_raw_7_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_7_value%'
'&e8. &b%ajleaderboards_board_bw1058_player_level_raw_8_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_8_value%'
'&e9. &b%ajleaderboards_board_bw1058_player_level_raw_9_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_9_value%'
'&e10. &b%ajleaderboards_board_bw1058_player_level_raw_10_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_10_value%'

**Comment by ajgeiss0702** [comment]
Fireballs are being looked into (#214)
If you have an issue with ajLeaderboards, ask their support

**Comment by dyslmj** [comment]
> 正在研究火球 ( #214 ) 如果您对 ajLeaderboards 有疑问，请寻求他们的支持
Would like to add the arena state operator!

**Comment by dyslmj** [comment]
and I am spigot 1.8.8
