### ISSUE TITLE
Leather Cap add Aqua Affinity enchanting

### ISSUE THREAD

**Issue by FootClick** [andrei1058/BedWars1058#227]
Is your feature request related to a problem? Please describe.
Yes

Describe the solution you'd like
Add Aqua affinity 1 enchant attribute to the starting equipment Leather Cap

Describe alternatives you've considered
No like a hypixel

Additional context
![20211225113336](https://user-images.githubusercontent.com/95486902/147378545-2e4af4aa-3f7d-4245-9243-d5147298bae2.png)

**Comment by andrei1058** [comment]
You can do that by adding an enchantment to your desired item: https://gitlab.com/andrei1058/BedWars1058/-/wikis/shop
