### ISSUE TITLE
Stacktrace + dropping all inventory items on the ground

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#236]
**Describe the bug**
When a player dies, their items, such as colored armor, drop to the ground.
There is a stacktrace in the console.

**To Reproduce**
1. Start the game
2. Die
3. See dropped items and the stacktrace

**Expected behavior**
Not dropping all items and no stacktrace

**Screenshots**
![image](https://user-images.githubusercontent.com/69810642/147423247-4ac62702-9ef8-4ff8-ad55-c4b1c2808c03.png)

**System (please complete the following information):**
 - OS: Ubuntu Server 21.04
 - Server software: Paper 1.18.1 (build 1449)
 - Server Version 1.18.1
 - Plugin Version 21.11.1

**Additional context**
Stacktrace content: https://mclo.gs/LbT95Lm

**Comment by andrei1058** [comment]
The guy that made the pull request for body arrows did not test it on 1.18 from what I can see

**Comment by FabrisNick** [comment]
> The guy that made the pull request for body arrows did not test it on 1.18 from what I can see

I had written in the PR the versions in which I had tested it... In 1.18 the games did not start due to the NBT bug

**Comment by andrei1058** [comment]
Your server is freezing due to bad data watcher on clearing arrows from players body and not NBT

**Comment by TheSkilledCat** [comment]
Maybe that's not a bug...
Check arena config and make sure that `vannila-death-drops` is set to `false`
Then again I have no clue what it could be from if it's not this 😂😂

**Comment by FabrisNick** [comment]
I think i have fixed this issue, but i can't test it due to an issue...

Stacktrace: https://pastebin.com/raw/BJGVdDiN

**Comment by ghost** [comment]
I made my own fork of Bedwars1058 and surrounded ```((CraftLivingEntity) player).getHandle().ai().a(new DataWatcherObject<>(12, DataWatcherRegistry.b), -1);``` with empty try-catch block so it looks not like that:
```
try {
    ((CraftLivingEntity) player).getHandle().ai().a(new DataWatcherObject<>(12, DataWatcherRegistry.b), -1);
} catch (Exception exception) {}
```
I no longer have a problem with items dropping on the ground.
So we can conclude that `clearArrowsFromPlayerBody` method is responsible for the existence of the problem.

**Comment by FabrisNick** [comment]
Can you try removing the try-catch and replace the code with 

`((CraftLivingEntity) player).getHandle().ai().b(new DataWatcherObject<>(12, DataWatcherRegistry.b), -1);`

**Comment by nicegamer7** [comment]
That fixes it for me.
