### ISSUE TITLE
Fireballs 

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#237]
**Describe the bug**
Fireballs dont break player blocks

**To Reproduce**
1. Install NachoSpigot & Bedwars1058 v21.12.1

**Expected behavior**
I bought fireballs and shots, nothing changed

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Server software NachoSpigot
 - Server Version 1.8.8
 - Plugin Version 21.12.1

**Additional context**

**Comment by ajgeiss0702** [comment]
Duplicate

**Comment by TheWylot** [comment]
actually why in 1.8.8 ?

**Comment by andrei1058** [comment]
Try reproducing this issue using paper and let us know if it still occurs.
