### ISSUE TITLE
Gensplit Bugs

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#238]
**Describe the bug**
I enable stack items on generators
since that gen split dont work

**To Reproduce**
i'm using bedwars1058-gensplit addon too, idk why it is bug

**System (please complete the following information):**
 - OS: [Windows Server 2019]
 - Server software [Paper]
 - Server Version [1.8.8]
 - Plugin Version [21.12.1]

**Comment by andrei1058** [comment]
English please? If you have issues with an addon this is not the right place to report it.

**Comment by TheWylot** [comment]
hey @andrei1058 , i unloaded BedWars1058-GenSplit addons, and turned the stack items on generators.yml on
after that, i dont have split feature anymore

**Comment by TheWylot** [comment]
i turned on it for preventing additional ticks on my server

**Comment by TheWylot** [comment]
in the config.yml on bedwars1058 gen split feature is true

**Comment by ajgeiss0702** [comment]
If you have an issue with an addon, go to the dev of that addon
