### ISSUE TITLE
mysql error no scoreboard no tab and cut map

### ISSUE THREAD

**Issue by ezVelar** [andrei1058/BedWars1058#243]
Hello I configured the bw with bwproxy and bw1058 but when I enter the game from an error and does not generate the scoreboard and the suffixes and prefixes in the tab, it generates the map in pieces a few times, does not give the objects of the waiting lobby. Sending the error thanks a thousand to those who respond
the error gives it from version 21.10.1 to 21.12.1
i use bedwarsproxy 
**update**
when i use mysql db the problem recurs while if i deactivate it everything works as before

Please fix soon

OS: Centos
ds: Mysql
Server software Spigot
Server Version 1.8.8
Plugin Version 21.12.1

https://pastebin.com/kEmrd8q7

**Comment by ajgeiss0702** [comment]
Show your levels config
