### ISSUE TITLE
Error on spectator chat

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#244]
**Describe the bug**
https://pastebin.com/sPyQabxe
Also the chat format is not working for spectator because of the error

**To Reproduce**
1. Type something in chat as a spectator
2. See error

**Expected behavior**
It shouldn't throw the error

**Screenshots**
https://pastebin.com/sPyQabxe

**System (please complete the following information):**
 - OS: Linux
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version 21.12.1

**Additional context**

**Comment by ajgeiss0702** [comment]
Update PAPI
