### ISSUE TITLE
Unbreakable Items In Shop Config

### ISSUE THREAD

**Issue by TheSkilledCat** [andrei1058/BedWars1058#245]
You can add a features that lets you add a `unbreakable: true` tag in shop.yml so that swords and tools become unbreakable.

It is easy to add because spigot and minecraft already give a way to do that and it could be fixed with small piece of code.

Thank You and I hope this feature will be added :...)

**Comment by rcubedev** [comment]
any update on this? @andrei1058

**Comment by ajgeiss0702** [comment]
If there was, there would be something here. I believe the shop is getting a rework at some point, so this might go with that.

**Comment by tomkeuper** [comment]
Note to self: Any upgraded tool will take damage over time. Make it configurable or just unbreakable

**Comment by tomkeuper** [comment]
Working on it

**Comment by tomkeuper** [comment]
Refresh the config OR add 'is-unbreakable: true' to melee items
![image](https://user-images.githubusercontent.com/29728836/220200227-43a09cad-f712-4ed5-84a1-29cba051594a.png)
