### ISSUE TITLE
Fireballs and TNTs do not affect blocks.

### ISSUE THREAD

**Issue by TheSkilledCat** [andrei1058/BedWars1058#246]
I'm pretty positive that fireball bug has already been reported but today I somehow managed to deal with a bug that didn't let TNT to damage blocks.

It was a bit strange because it did damage to wool of color of the player who placed the tnt but not anything else, and sometimes it worked properly.

And.. Also knockback and explosion range issued and players could be hit from more than 20 blocks while the range was configured to be 6 blocks.

Thank You and I hope this was useful :..)

**Comment by FabrisNick** [comment]
I think it's fixed in PR #241, which has not yet been merged in master
