### ISSUE TITLE
Build Issues On Debian

### ISSUE THREAD

**Issue by terrified9** [andrei1058/BedWars1058#25]
**Describe the bug**
Basically building (`mvn install` or `mvn clean install`) results in an error that references to 1.17.1 support. I'm using AdoptOpenJDK Java 8 on machine, running Debian 10, if that matters. 

**To Reproduce**
1. Get the source of the plugin on linux/debian.
2. Try building it with `mvn install` or `mvn clean install` using Java 8
3. It will result in an error.
4. The error: 

**Expected behavior**
The plugin should build normally.

**Screenshots**

**System (please complete the following information):**
 - OS: Debian 10
 - Server software: None
 - Server Version: None
 - Plugin Version: Latest Source

**Additional context**
Nope

**Comment by dhiepp** [comment]
try building with java 16

**Comment by ItzZisker** [comment]
hmm maybe there is an issue with nms classes, compile using java 11, as it said "Class file has wrong version", i hope that helps. make sure your jdk path is set correctly "update-alternatives --config java"

**Comment by andrei1058** [comment]
Maven version?

**Comment by terrified9** [comment]
> Maven version?

3.6.0

**Comment by andrei1058** [comment]
Try with maven 3.6.3. also next time don't say "latest version". Always provide a version or latest commit hash.
