### ISSUE TITLE
Please add new per group stats like the one hypixel has please @andrei1058

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#250]
This is a feature request asking for all these things in the /bw stats for players ease of access
https://www.google.com/url?sa=i&url=https%3A%2F%2Fhypixel.net%2Fthreads%2Fwhat%25E2%2580%2599s-your-tournament-stats.1987798%2F&psig=AOvVaw3zeNkbFENycm56u3CwCkun&ust=1641408193875000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKDrpo_gmPUCFQAAAAAdAAAAABAJ
https://www.google.com/url?sa=i&url=https%3A%2F%2Fhypixel.net%2Fthreads%2Fstats-gone-help.3761182%2F&psig=AOvVaw3zeNkbFENycm56u3CwCkun&ust=1641408193875000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKDrpo_gmPUCFQAAAAAdAAAAABAQ

**Comment by ajgeiss0702** [comment]
Duplicate
