### ISSUE TITLE
Please Fix This

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#253]
**To Reproduce**
1.Use any version of spigot
2. Join an arena
3. Start the game with 2 or more
4.See the error

**Expected behavior**
See R for Red B for Blue G For Green and vice versa

**Screenshots**
https://media.discordapp.net/attachments/348088106546757653/928274186068176916/unknown.png

**System (please complete the following information):**
 - OS: Windows
 - Server software: spigot
 - Server Version: 1.8.8
 - Plugin Version: 21.11.2

**Additional context**
Please fix this the full thingy is given above

**Comment by ajgeiss0702** [comment]
This is not a bug. You can change this in the language file.
