### ISSUE TITLE
Custom XP Rewards multiplyer like that of hypixel

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#254]
Old XP System
![image](https://user-images.githubusercontent.com/93807992/148271710-1ceef1a4-c867-4192-9861-5c5f3c2860d2.png)
The New System like multiply system
![image](https://user-images.githubusercontent.com/93807992/148272116-ef7932d9-7ab2-446c-bb74-0a5b7bff062e.png)

**Comment by ghost** [comment]
Also please change the experience to &b instead of &6

**Comment by Xxyuri2005xX** [comment]
this is really easy to do, you can customize XP messages with Language File

**Comment by ghost** [comment]
No,I mean I want it so that different player gets different amount of xp with the permission
