### ISSUE TITLE
why spectators can hit the person playing

### ISSUE THREAD

**Issue by woupine** [andrei1058/BedWars1058#255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. MacOS, Windows Server, Linux]
 - Server software [e.g. spigot, paper]
 - Server Version [e.g. 1.8.8]
 - Plugin Version [e.g. 21.11.2]

**Additional context**

**Comment by ajgeiss0702** [comment]
You did not fill out the template
