### ISSUE TITLE
Party + ArenaSelector problems

### ISSUE THREAD

**Issue by Drizz1** [andrei1058/BedWars1058#259]
When LegacySelector is on:

Example:
Mode: 2v2v2v2
Players in game: 4
Teams created: YES YES YES YES | (BUG)
Players in teams 1 1 1 1 | BUG

Should be: 2 2 NO NO

Parties: Good

--------------------------------------

When LegacySelector is off:

Example:
Mode: 2v2v2v2
Players in game: 4
Teams created: YES YES NO NO
Players in teams 2 2 0 0

Is good: 2 2 NO NO

Parties: BUG! When you are in party you aren't with your friend in team (Always)

-----------------------------------------

Fix party when LegacySelector is off / Fix teams when LegacySelector is on

 - OS: Linux
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version  21.11.2

**Comment by tomkeuper** [comment]
Duplicate of #179
