### ISSUE TITLE
Void kill

### ISSUE THREAD

**Issue by xFedeT** [andrei1058/BedWars1058#260]
Andrebbe Fatto in Modo che quando si finisce nel Void non Si vede l'animazione della Morte (cosa che non si può disabilitare anche se si imposta la gamerule), faccio un esempio Hypixel e Coral, quando cadi nel vuoto, vieni portato nel punto degli spettatori senza nessuna animazione di morte, ne di respawn!

**Comment by ajgeiss0702** [comment]
Use the issue template
