### ISSUE TITLE
Death system

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#261]
Please introduce another death function in a game like a hypixel, e.g. when we fall into void there should be no sound of death and also a death screen thanks to which death will be smooth.

**Comment by ghost** [comment]
Ya please make a new deadth system+add new sound to sounds.yml that plays when a player kills other player

**Comment by reussy** [comment]
You could make a more elaborate enhancement, since not everyone plays Hypixel 24/7 it is difficult to know what exactly you mean

**Comment by ghost** [comment]
I guess he is trying to describe
1 When a player falls into the void he hears a deadth sound thats by default the death sound of everyting.I guess Hypixel has no self deadth sound.
2 Remove the Deadth Screen.There is a deadth screen when the player dies to void if its fixed thr bedwars plugin will be better than ever

**Comment by ajgeiss0702** [comment]
There isn’t a death screen on death. I would know, I’ve killed myself in-game literally hundreds of times testing things lol

If you have a death screen, try with no other plugins

**Comment by ghost** [comment]
Maybe My potato pc problem with rtx3070

**Comment by leeteral** [comment]
Still death screen showing for a split second after dying from void.
