### ISSUE TITLE
Cross Killing

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#265]
**Describe the bug**
please fix cross killing in bedwars1058.
**To Reproduce**
1. Play a game
2. make a bridge
3. go to opponent
4. try pvping causes both the player to die at the same time sometimes.

**Expected behavior**
Player should kill other player on 0 heart

**Screenshots**
Dont have screen shots currently

**System (please complete the following information):**
 - OS: Windows
 - Server software: Spigot
 - Server Version: 1.8.8
 - Plugin Version: 21.12.2

**Additional context**

**Comment by ajgeiss0702** [comment]
Can you record a video of the issue? Because from this it sounds like you are trying to say that being able to kill other teams is a bug..

**Comment by ghost** [comment]
No I mean when we PvP both the player dies to eachother at the sametime.
Instead of killing other by some heart differences
