### ISSUE TITLE
Custom Placeholder Support in scoreboard

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#268]
This is a feature request for adding custom placeholders to the plugin like loot chest: &6%plceholder_loot_chest%

**Comment by reussy** [comment]
Use PlaceholderAPI instead

**Comment by ghost** [comment]
Does the plugin support PAPI In the inbuilt scoreboard??
like maybe %eazynick_chat_prefix%

**Comment by reussy** [comment]
> Does the plugin support PAPI In the inbuilt scoreboard?? like maybe %eazynick_chat_prefix%

Yes, the scoreboard supports PlaceholderAPI
Try it

**Comment by ghost** [comment]
Thx

**Comment by reussy** [comment]
> Thx

You can close this
