### ISSUE TITLE
Inbuilt Toggleable LeaderBoard from Ajgeiss LeaderBoards

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#269]
Please add inbuilt LeaderBoard that uses ajleaderboards v2 and someother holo plugin to make toggleable leaderboards then the plugin would be better/easier for the users.

**Comment by ghost** [comment]
Toggleable means It can be cycled between daily weekly montly lifetime etc like on hypixel

**Comment by minhh2792** [comment]
No, we can just use external plugin for that
