### ISSUE TITLE
Xp reward configuration

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#27]
**Is your feature request related to a problem? Please describe.**
So basically we need to disable xp reward if it is set to 0 and maybe add other xp-reward opportunities?!

**Describe the solution you'd like**
Code

**Describe alternatives you've considered**
Be lazy

**Additional context**

**Comment by bahadirkaratas** [comment]
Hi @andrei1058,
First of all I must say that I am a complete beginner when it comes to open source. I really would like to handle this issue but I am worried that I might fail. If it is possible, I would appreciate any kind of help and support. I have couple of questions:

1) by "xp reward" do you mean the procedure at the PerMinuteTask.java ? 
2) how can a player  set the xp reward to 0 ?

**Comment by andrei1058** [comment]
@Xxyuri2005xX questa roba mi ricordo che l'avevi implementata te, vero?

**Comment by Xxyuri2005xX** [comment]
@andrei1058 avevo implementato il give dell'xp per la final kill, kill normale e letto distrutto con la possibilità di disattivazione se era 0, gli altri avevano già la possibilità di esser disattivati se erano 0.

For our non italian speaking (By MrCeasar):
I had implemented the xp give for the final kill, normal kill and destroyed bed with the possibility of deactivation if it was 0, the others already had the possibility of being deactivated if they were 0.
