### ISSUE TITLE
Vault support missing! message when i kill a player or win a game.

### ISSUE THREAD

**Issue by ralemac7** [andrei1058/BedWars1058#271]
**Describe the bug**
I have not installed Vault on my bedwars server, because i don't want players to get money rewards, but i updated the plugin recently and now that error appears.

**To Reproduce**
1. Start a BedWars game
2. Kill a player, or win a game
3. See the "Vault support missing!" message (error) on chat.

**Expected behavior**
A message on chat that says "Vault support missing!" appears.

**System (please complete the following information):**
 - OS: Ubuntu 20.04 (running server in Pterodactyl panel)
 - Server software: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT
 - Server Version: 1.8.8
 - Plugin Version:

**Comment by zNotRafa** [comment]
I forgot to say the version of the plugin i am running is the latest available on polymart, 21.12.1.

**Comment by Xxyuri2005xX** [comment]
Do you have Vault and economy plugin with support to Vault?

**Comment by zNotRafa** [comment]
> Do you have Vault and economy plugin with support to Vault?

I only have Vault installed, but i don't have an economy plugin installed, because i don't wan't players to get money rewards, the think i wan't is to remove that message.

**Comment by Xxyuri2005xX** [comment]
Mhhh, try settimg money rewards to 0 by config

**Comment by zNotRafa** [comment]
> Mhhh, try settimg money rewards to 0 by config

in wich file i can find that setting?

**Comment by Xxyuri2005xX** [comment]
Rewards

**Comment by zNotRafa** [comment]
So, my file should look like this?

money-rewards:
  per-minute: 0
  per-teammate: 0
  game-win: 0
  bed-destroyed: 0
  final-kill: 0
  regular-kill: 0

**Comment by Xxyuri2005xX** [comment]
ye
