### ISSUE TITLE
Hardcore hearts after bed destroy

### ISSUE THREAD

**Issue by xcoolerboy** [andrei1058/BedWars1058#281]
Hey soo i have little suggestion that when team beds was destroyed, players in team change into hardcore mode like Hypixel

**Comment by ajgeiss0702** [comment]
Does hypixel do this? From what I can see only mods can do this.

I've also looked into some protocol stuff, it looks like its impossible to show hardcore hearts, and its only possible to tell the client to show the hardcore hearts on join.

Re-open if I'm wrong
