### ISSUE TITLE
A Modest Proposal

### ISSUE THREAD

**Issue by dyslmj** [andrei1058/BedWars1058#282]
Adds invisibility to bystanders!!!!!pease!!!!
Would like to add the arena state operator and Fireballs do not propel or break blocks in spigotmc 1.8.8. in the BedWars-21.11.2 version if it breaks the blocks but the explosion was not propelling!!!!!!!!

**Comment by ghost** [comment]
21.12.2 not 21.11.2
use latest dumpoo
