### ISSUE TITLE
Please add a placeholder which returns the color+level+star from the level config without the brackets

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#285]
![image](https://user-images.githubusercontent.com/93807992/149352433-49b0d80e-572b-4aa9-9409-4ca1225382aa.png)
![image](https://user-images.githubusercontent.com/93807992/149352495-46b3216e-b7ac-443b-8784-c5ccef01779d.png)
See the difference Those two stars are different from each other[In The Sense Color]
I just wanna tell That I want a placeholder which returns The ColorCode+LevelNumber+Star without the bracket.
The placeholder can be something like %bw1058_stats_level_color% or something

**Comment by ItsFantom** [comment]
you can customize that in levels.yml

**Comment by ghost** [comment]
Nope not perfectly

**Comment by ItsFantom** [comment]
> Nope not perfectly

yes you can. remove brackets from levels and use it like that
