### ISSUE TITLE
Better Leveling system like hypixel[Prestiges]

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#286]
@andrei1058  I just wanna tell that it would've been better if there was Per-Player prestige,Per-Level Prestige,Per-Group Prestigue etc like hypixel.I dont know much about it but as per my knowledge from google.
This is what i meant
![image](https://user-images.githubusercontent.com/93807992/149354103-244b8a1b-6883-448d-81af-66d0409f1877.png)
![image](https://user-images.githubusercontent.com/93807992/149354146-edd5d6f2-c5c4-4768-a3be-0dfb53f088a6.png)
I dont have Minecraft Account So I Dont have much knowledge about it.
The things that i know are the things that i see on youtubers videos

**Comment by ghost** [comment]
Hypixel stars-
1. ✫
2.  ✪
3.  ⚝

**Comment by ItsFantom** [comment]
You can customize that in levels.yml

**Comment by ghost** [comment]
No i was just telling about making it default.
