### ISSUE TITLE
Please add this XP Multiplyer

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#288]
![Screenshot_2022-01-13-22-08-18-72_f9ee0578fe1cc94de7482bd41accb329.jpg](https://user-images.githubusercontent.com/93807992/149371334-f2ae98eb-26f4-42a1-83d9-9db448ccbcba.jpg)

**Comment by ItsFantom** [comment]
This isn't bedwars feature on hypixel. This is shown because of Triple XP + Coins event.

**Comment by ghost** [comment]
I just want that even on bedwars 1058

**Comment by Xxyuri2005xX** [comment]
I think you can use Levels & Arena APIs for doing it, if player is in game and has an active multiplyer you get double or triple xp or what you want in base od the choosen on, juat getting the per-minute xp and doing xp*number

**Comment by ghost** [comment]
> 

Bruh I Am not a code nor i want to be.
