### ISSUE TITLE
Player XP (Formatted) Problem.

### ISSUE THREAD

**Issue by MVPFizzy** [andrei1058/BedWars1058#297]
**Describe the bug**
**Hey. So i have this Player XP Bug on the lobby scoreboard.
When I add Placeholder for Player XP (Formatted). It doesn't work.
So like for example: It should be 1.6k/2k but even with the placeholder it shows 1.615k/2k,
So the placeholders or bedwars plugin problem. Doesn't work at all. U should fix it**

**To Reproduce**

**Expected behavior**

**Screenshots**
![2022-01-14_15 26 53](https://user-images.githubusercontent.com/97798480/149628657-15a802c3-b12f-4a62-8ace-523850254db9.png)
![Screenshot (464) (1)](https://user-images.githubusercontent.com/97798480/149628658-16e38aae-aecc-4557-809a-82a29aeefeca.jpg)

**System (please complete the following information):**
 - OS: [e.g. MacOS, Windows Server, Linux]
 - Server software [e.g. spigot, paper]
 - Server Version [e.g. 1.8.8]
 - Plugin Version [e.g. 21.11.2]

**Additional context**

**Comment by ghost** [comment]
I have this problem too.
When i do /bw level setLevel addXP <player> 5000
It just glitches as 5k/2k
When i am on 1 star account
