### ISSUE TITLE
Make the /bw stats default to this.

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#299]
![image](https://user-images.githubusercontent.com/93807992/149644052-b4f2485a-eae8-4513-b75e-83c7a848f3ff.png)
Please Make the /bw stats look like the image that you see abive with per group stats. etc.
I dont have Mc account or i wouldve given a detailed Description of what i want to say.

**Comment by ItsFantom** [comment]
So hypixel style?

**Comment by ghost** [comment]
ya

**Comment by DeusDrizzyy** [comment]
Separating the stats for each game mode would be really interesting. The same could be done with papi hook, changing "%bw1058_stats_kills%" to "%bw1058_stats_kills_[groupName]%".

**Comment by ghost** [comment]
Ya
