### ISSUE TITLE
Implement Floodgate GUI support for shops.

### ISSUE THREAD

**Issue by marioded** [andrei1058/BedWars1058#3]
Add support to Floodgate Forms to allow players who enter through Geyser to be able to open the menus of the upgrade and the item shop through the new menus of the bedrock edition.

**Comment by andrei1058** [comment]
Please provide more information.

**Comment by marioded** [comment]
@andrei1058

**Comment by andrei1058** [comment]
we're going to keep open #37 since it is more detailed. if you want that feature vote with reactions.
