### ISSUE TITLE
Don't split teams evenly

### ISSUE THREAD

**Issue by DeusDrizzyy** [andrei1058/BedWars1058#307]
**Is your feature request related to a problem? Please describe.**
Currently if 4 players then in a doubles match, 2 players will be on team X, 1 on team Y and one on team Z.

**Describe the solution you'd like:**
The amount of players remaining that exceeds the "maxInTeam" of the configuration, instead of going to different teams, could very well complete another team. As shown in the example above, instead of 1 player going to team X and another to team Z, both should only be on team X.

**Comment by ghost** [comment]
Not only that if i force start doubles with 2 player then both the player gets added in one team instead of splitting to other teams

**Comment by terrified9** [comment]
> Not only that if i force start doubles with 2 player then both the player gets added in one team instead of splitting to other teams

yep same

**Comment by Drizz1** [comment]
same https://github.com/andrei1058/BedWars1058/issues/259
