### ISSUE TITLE
Play Again

### ISSUE THREAD

**Issue by DeusDrizzyy** [andrei1058/BedWars1058#309]
It would be very good if there was a command that the player can use if he is a spectator, something like "/bw join new", when using this the player will enter another match of the same group of the current arena he is in... Por For example, an item would be added to "spectator-items", when clicking on this item, if the player is in a doubles match he would enter another doubles match and so on. This would make life easier for players who would no longer have to leave the match they are viewing, go to the lobby and only then be able to enter another doubles match.

**Comment by ghost** [comment]
It should be like /bw playagain in game or /bw joinagain
or maybe it should be [/bw join] inself in-game

**Comment by DeusDrizzyy** [comment]
Something like that...

**Comment by andrei1058** [comment]
Implementing it on multi area wouldn't take much effort, but we need to bring it to bungee mode as well. Basically I won't add it until we find a good way to make it work on bungee Mode.

**Comment by FantonFancy** [comment]
> Implementing it on multi area wouldn't take much effort, but we need to bring it to bungee mode as well. Basically I won't add it until we find a good way to make it work on bungee Mode.

Afaik Mher Zaqaryan had it on one of his plugins For Bungee mode

**Comment by ghost** [comment]
https://polymart.org/resource/bedwars1058-play-again-addon.1946
