### ISSUE TITLE
looks like u got it

### ISSUE THREAD

**Issue by xmyoard** [andrei1058/BedWars1058#31]
looks like u got many pull requests and issues, and I hope after finishing it the final version will come in the spigot page.

waiting for it!!

**Comment by minhh2792** [comment]
imagine open an issue just for this

**Comment by xmyoard** [comment]
xdd

**Comment by andrei1058** [comment]
We're going to release a new update soon. Next time please use git issues for a more detailed feedback. For basic chats please join our discord ✌️

**Comment by xmyoard** [comment]
yeah sure, I don't have discord and I can't use it for some reason. but sure I can use git.
