### ISSUE TITLE
Please increase the spectator invisibility effect

### ISSUE THREAD

**Issue by dyslmj** [andrei1058/BedWars1058#310]
(I don't speak English, so I'm a machine translator)
**Describe the bug**
It doesn't work in 1.8!
**To Reproduce**
Please increase the spectator invisibility effect
It doesn't work in 1.8!!!!!!!!!!!!!!!!!!!!!!
**Expected behavior**
The player can become invisible after death
Bystanders can also be invisible
**Screenshots**
![@4~3RJ${U3QX%`)%4}W13(N](https://user-images.githubusercontent.com/95755417/150623166-51f43152-c5bb-4d8b-b806-07a13ccd3645.png)
System
windows server 2019
Spigot
1.8.8
21.12.1

**Comment by DeusDrizzyy** [comment]
This is not a bug, you may not have the invisibility effect you know, but the players in the match cannot see you. 😂
