### ISSUE TITLE
Beds keep getting dropped when you break them.

### ISSUE THREAD

**Issue by goosBanny** [andrei1058/BedWars1058#311]
**Describe the bug**
When an enemy player breaks your bed, it will drop. The players will be able to pick it up.

**To Reproduce**
1. Destroy Enemy Bed

**Expected behavior**
In most plugins, the bed will normally disappear if broken. In BW1058, it drops instead of disappearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/74544572/150671049-a4b3ea08-e306-4f14-8198-aac147ae829a.png)

**System (please complete the following information):**
 - OS: Linux
 - Server software Purpur 
 - Server Version: 1.16.5 Build 1171
 - Plugin Version: 21.12.1

**Additional context**
No Extra Info

**Comment by ajgeiss0702** [comment]
This is intended, as it used to be like that on hypixel. In the future, it will be configurable.

**Comment by ghost** [comment]
> This is intended, as it used to be like that on hypixel. In the future, it will be configurable.

May be hypixel didnt knew how to fix it that time XD

**Comment by pukislukis** [comment]
> > This is intended, as it used to be like that on hypixel. In the future, it will be configurable.
> 
> May be hypixel didnt knew how to fix it that time XD

The dropped bed item will not be able to be picked up
