### ISSUE TITLE
Bungee Mode Connection

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#314]
**Describe the bug**
Sometimes on bungee-mode auto-scale mode, players are not teleported in arena, and they are teleported just on main server world (in my case "world" world). The players are connected to arenas using just BedWars commands. The problem is happening sometimes and random.

**To Reproduce**
1. Use /bw join MODE or /bw join random
2. See error (the problem it's not happening everytime)

**Expected behavior**
-

**Screenshots**
https://cdn.upload.systems/uploads/hXPbPAax.png

**System (please complete the following information):**
 - OS: Linux
 - Server software: Paper
 - Server Version 1.8.8
 - Plugin Version 21.12.1

**Additional context**
-

**Comment by andrei1058** [comment]
you should increase the tolerance for connection: `bwp-time-out`

**Comment by Askarionn** [comment]
it's ok if it set it to 10000? default is 5000

**Comment by tomkeuper** [comment]
closed due to being stale
