### ISSUE TITLE
New sound in sounds.yml aka player kill-sound

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#315]
Play a sound when player got a kill in game.
The sound
1.8: ORB_PICKUP
1.9-1.18: ENTITY_EXPERIENCE_ORB_PICKUP
pitch: 1
volume: 1

This is what i mean
https://www.youtube.com/watch?v=oT4RkP5sFY8&t=88

**Comment by ghost** [comment]
Woulve been cool

**Comment by ajgeiss0702** [comment]
> Woulve been cool

Don’t get a reply for a week and you suddenly assume it will never be added?

**Comment by ghost** [comment]
0K

**Comment by ajgeiss0702** [comment]
Why did you close it? I think it’s a good suggestion and I’ll probably do it if I have time at some point

**Comment by ghost** [comment]
oh ok
