### ISSUE TITLE
Not able to pick up items, and cant hit nor get hit by other players

### ISSUE THREAD

**Issue by Cryptics1999** [andrei1058/BedWars1058#317]
Download Bedwars 1058 (21.12.1) on your server

Play game, and its a chance of this happening.

System:
Linux
FoxSpigot
Serverversion: 1.8.8
Plugin Vr: 21.12.1

https://media.discordapp.net/attachments/896711320706105354/935989510058176522/unknown.png?width=2000&height=837

**Comment by DeusDrizzyy** [comment]
This has happened to me too... It seems like a random event, but it's happening!

**Comment by ajgeiss0702** [comment]
See the compatibility page on the wiki

**Comment by Cryptics1999** [comment]
But im able to pick up items normaly, it happend suddenly.
