### ISSUE TITLE
Map who disappeared

### ISSUE THREAD

**Issue by Psykonoff** [andrei1058/BedWars1058#320]
**Describe the bug**
The map when launching the game disappears

**Screenshots**
![image](https://user-images.githubusercontent.com/98184477/151415849-b214a225-a42b-4dc7-9c50-a017c75e92b7.png)
![image](https://user-images.githubusercontent.com/98184477/151415989-1d01e654-c4af-4124-a1a3-b611ca2cac61.png)

**System (please complete the following information):**
 - Windows Server
 - spigot
 - Server Version 1.18
 - Plugin Version 21.12.1

**Comment by ajgeiss0702** [comment]
Remove the map from multiverse
