### ISSUE TITLE
Inventory bug at lobby when a server stops and starts

### ISSUE THREAD

**Issue by GreenArrowlol** [andrei1058/BedWars1058#321]
**Describe the bug**
When you're in the middle of a game and the server stops and starts and you join the server, your inventory at lobby breaks. You basically have the items from the game

**To Reproduce**
N/A

**Expected behavior**
Player Inventory shouldn't have the items from their previous game after the server `stops` and `starts`
**Screenshots**
N/A 

**System (please complete the following information):**
 - OS: [Linux (Using pterodactyl panel)]
 - Server software [paper]
 - Server Version [1.8.8]
 - Plugin Version [21.12.1]

**Additional context**

**Comment by ajgeiss0702** [comment]
Duplicate

**Comment by GreenArrowlol** [comment]
> Duplicate

was there already someone who reported the same issue?

**Comment by ajgeiss0702** [comment]
Yes. #298
