### ISSUE TITLE
Pls Fix other worlds still have the stats, arena chest, and bed to tp back to lobby pls. Also in spigot 1.8.8

### ISSUE THREAD

**Issue by DaveHehe** [andrei1058/BedWars1058#322]
Pls Fix Pls I just want my server to be cool
i cant put a server selector and lobby setter so it will be a perfect server 
pls fix this bug
also am using the open source bedwars1058 plugin

**Comment by ajgeiss0702** [comment]
There’s so many things wrong with this issue…

1. that’s not a bug, that’s a feature request
2. This isn’t the plugin to add a server selector/lobby selector. This is a minigame plugin, not a lobby plugin
3. Use the template. It’s there for a reason, don’t just remove it
