### ISSUE TITLE
Lobby issue

### ISSUE THREAD

**Issue by WaifChan** [andrei1058/BedWars1058#328]
my plugin not delete all block in arena lobby when i play a game
picture here:
![error](https://user-images.githubusercontent.com/93257883/152129793-3b9a866b-deab-4208-98a1-fc6a7e5a2703.png)
my plugin version is 22.01 ( idk 22.01 is real or fake, i find it here https://ci.codemc.io/job/andrei1058/job/BedWars1058/ )
Server type : paper
Version : 1.8.8

**Comment by ghost** [comment]
Its Waiting Spawn Not Lobby.
Lobby the the world which is used to select maps.
I also have the problem with 21.12.2 even after selecting like 10 to 20 blocks further away from the waiting spawn.

**Comment by tomkeuper** [comment]
This is either caused by incorrect setup of the lobby coordinates or viaversion not sending the packets properly.
