### ISSUE TITLE
Server problem 

### ISSUE THREAD

**Issue by Adamek038271** [andrei1058/BedWars1058#331]
**Describe the bug**
I have a problem when I start the minecraft server, my maps do not load and I write that they do not exist, even though I have all the files

**Expected behavior**
all maps should load

**Screenshots**
https://cdn.discordapp.com/attachments/938402114558898197/938482149210873876/unknown.png

**System (please complete the following information):**
 - OS: [Windows Server]
 - Server software [spigot]
 - Server Version [e.g. 1.8.8]
 - Plugin Version [e.g. 21.12.1]

**Comment by ajgeiss0702** [comment]
Please join discord for support
