### ISSUE TITLE
Bring back player-head texture on 1.18

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#333]
Since my last hotfix player-head textures do not appear on 1.18 because I still do not know what mojang changed. It could be a spigot issue as well but I can't putt texture on heads the old way.

**Comment by tomkeuper** [comment]
Item meta gets reset when an NMS copy is made.

**Comment by tomkeuper** [comment]
I dont think anything changed, there was no function actually changing the meta data of the item :)
