### ISSUE TITLE
Fix arena (Linux)

### ISSUE THREAD

**Issue by cemcrid** [andrei1058/BedWars1058#339]
Describe the bug:
bedwars1058 plugin has arena error when running on linux operating system (Ubuntu) it doesn't support slimeworld and messes up arena

Logs

https://ghostbin.com/iYzXT

OS: Linux
Server software: NachoSpigot
Server Version: 1.8.8
Plugin Version: 22.2

**Comment by ajgeiss0702** [comment]
It looks like your arena world doesn’t exist.

**Comment by cemcrid** [comment]
> 

lol i have 70 arenas but i cant load

**Comment by cemcrid** [comment]
> It looks like your arena world doesn’t exist.

in windows operating system i can load all arena, but when i put it in vps with linux operating system, it can't load arena
