### ISSUE TITLE
Fix Arena Load (Linux) #2

### ISSUE THREAD

**Issue by cemcrid** [andrei1058/BedWars1058#346]
Describe the bug:
bedwars1058 plugin has arena error when running on linux operating system (Ubuntu) it doesn't support slimeworld and messes up arena

in windows operating system i can load all arena, but when i put it in vps with linux operating system, it can't load arena

Logs

https://ghostbin.com/iYzXT

OS: Linux
Server software: NachoSpigot
Server Version: 1.8.8
Plugin Version: 22.2

**Comment by ItsFantom** [comment]
Never faced that problem i use Ubuntu and SWM but never had loading problem 🤷🏼

**Comment by ajgeiss0702** [comment]
As I said before, your arena isnt there.
Make sure you also transferred the arena when uploading to the server.

If you continue making issues about this, any of your future issues in the future will be immediately closed. If you need support, go to discord.
