### ISSUE TITLE
Better Scoreboard System for <1.13

### ISSUE THREAD

**Issue by arttwart** [andrei1058/BedWars1058#36]
**Is your feature request related to a problem? Please describe.**
Firstly I want to point out, I couldn't try if this works. Because I couldn't make BedWars1058 work and I've an issue report. If it doesn't exist, it is releated to a problem. I'm using 1.17.1 server, and you know, there was scoreboard system changes in 1.13. So, players with 1.7.2 - 1.12.2 see the scoreboard glitchy. 

**Describe the solution you'd like**
If scoreboards for 1.7.2 - 1.12.2 players work alternatively, they would see the scoreboard normal.

**Describe alternatives you've considered**
If there are placeholders for in-game statuses such as Blue Team's bed status, final kill count for that game etc., I can use a plugin called "AnimatedScoreboard". It has that feature. There is an option for players below 1.13 can see scoreboard normal even if your server core above 1.13.

**Comment by andrei1058** [comment]
Provide some screenshots please.
