### ISSUE TITLE
Tab in game not working

### ISSUE THREAD

**Issue by WaifChan** [andrei1058/BedWars1058#367]
**Describe the bug**
Tab in game not show team and change player name to team color only show health

**To Reproduce**
1. Play one game 
2. Press "tab"
3. and see error

**Expected behavior**
Tab working normal again
**Screenshots**
![image](https://user-images.githubusercontent.com/93257883/152682167-727a1fed-0be8-4bf9-ad69-422e08e13f6d.png)

**System**
 - OS: Windows 11
 - Server software: paper
 - Server Version 1.8.8
 - Plugin Version 22.2

**Comment by ghost** [comment]
Hey dum dum. You need to config it in tab config.
Cuz tab is the one dealing with prefix sort of stuffs when it is enabled not bedwars1058.

**Comment by ghost** [comment]
btw if you need help here you go

**Comment by ghost** [comment]
go to /plugins/TAB/groups.yml and change all the tab tabprefix and tagprefix to this- %bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color%  |for all the groups including _DEFAULT_

**Comment by ghost** [comment]
Owner:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
Admin:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
mod:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
youtube:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
mvpplusplus:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
mvpplus:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
mvp:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
vipplus:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
vip:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
default:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
_OTHER_:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  
example_group:
  header:
    - "This is an example of per-group header/footer"
  footer:
    - "applied to a group"

_DEFAULT_:
  tabprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  tagprefix: "%bw1058plus_team_color%&l%bw1058plus_team_letter%&f%bw1058plus_team_color% "
  customtabname: ""
  customtagname: "" 
  tabsuffix: ""
  tagsuffix: ""

per-world:
  world:
    _DEFAULT_:
      tabprefix: "%vault-prefix% "
      tagprefix: "%vault-prefix% "
      customtabname: ""
      customtagname: "" 
      tabsuffix: " %vault-suffix%"
      tagsuffix: " %vault-suffix%"

**Comment by ghost** [comment]
just paste this in your groups.yml in /TAB folder in /plugins

**Comment by ghost** [comment]
Also it Would've been cool if it was per-implemented with TAB support so that people don't need to mess with it

**Comment by ajgeiss0702** [comment]
If you use a tab plugin, you’ll either need to configure TAB or remove it for bedwars worlds so it can let bedwars do it
