### ISSUE TITLE
Unbreakable Sword

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#370]
**Describe the bug**
In simple terms, All the other sword otherthan wooden sword breaks when its durability is over.

**To Reproduce**
1. Start server
2. Join a game
3. Collect resources
4. buy any sword greater than wood
5. You see the swords durability
6. After the durability is over the sword breaks

**Expected behavior**
The sword should not break

**Screenshots**
Don't have currently

**System (please complete the following information):**
 - OS: Windows[Local Host]
 - Server software: Spigot
 - Server Version: 1.8-1.18
 - Plugin Version: 22.2

**Additional context**
Nothing more

**Comment by andrei1058** [comment]
just set it to permanent in shop :)

**Comment by ghost** [comment]
> just set it to permanent in shop :)

Won't it just make the item permanent fro the player even after death

**Comment by tomkeuper** [comment]
duplicate of #245
