### ISSUE TITLE
Popup-Tower

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#371]
**Is your feature request related to a problem? Please describe.**
Please add popup tower in-buit to the plugin

**Describe the solution you'd like**
I want The Bedwars1058 plugin  to have Popup Tower In-Built because why not.

**Describe alternatives you've considered**
I can consider The Popup Tower add-on but its not working for newer versions like 1.17-1.18

**Additional context**
Would Have Been Easier and Cooler If It was Inbuilt

**Comment by sreyas0001** [comment]
Bruh @Ghost Thats an OG name

**Comment by sreyas0001** [comment]
> **Is your feature request related to a problem? Please describe.** Please add popup tower in-build to the plugin
> 
> **Describe the solution you'd like** I want The Bedwars1058 plugin to have Popup Tower In-Built because why not.
> 
> **Describe alternatives you've considered** I can consider The Popup Tower add-on but its not working for newer versions like 1.17-1.18
> 
> **Additional context** Would Have Been Easier and Cooler If It was Inbuilt

You can add popup tower with add-on but it is hard to use.
Would be a great update though. ;)
