### ISSUE TITLE
Parse PlaceholderAPI in all messages

### ISSUE THREAD

**Issue by EndMoyu** [andrei1058/BedWars1058#373]
**Is your feature request related to a problem? Please describe.**
Add PlaceHolder support in all message
I tried to put %vault_rank_color% in cmd-join-sucess , but it didn't work

**Describe the solution you'd like**
I can use some PlaceHolderAPI in all message

**Describe alternatives you've considered**
Well.It's look like can use {vPrefix} to replace
but It's show up with rank

**Additional context**
If it appears, it will be easier to look like a large network.

**Comment by ajgeiss0702** [comment]
Note that the placeholders would parse for the player viewing the message, so if you used the prefix papi placeholder, it would just show the prefix of the player viewing the message.

If the vPrefix or vSuffix placeholders are missing where they should be, please open a seperate suggestion issue about that.
