### ISSUE TITLE
Inventroy does not reset in bungee mode

### ISSUE THREAD

**Issue by EndMoyu** [andrei1058/BedWars1058#374]
**Describe the bug**
Inventroy does not reset in bungee mode
When the game starts, the inventroy resets

**To Reproduce**
1. Use BungeeMode
2. Join the game
3. Start the Game
4. Get some item
5. Then Disconnect
6. Join same Arena

**Expected behavior**
When I join same Arena Waitlobby item will not appear again

**Screenshots**
Currently Not

**System (please complete the following information):**
 - Windows Server 2016
 - Paper1.8.8-445
 - 1.8.8
 - 22.2

**Additional context**
Although it's a small problem, it's more perfect if it fixed

**Comment by ajgeiss0702** [comment]
Can you record a video of the issue?

**Comment by EndMoyu** [comment]
> Can you record a video of the issue?

https://youtu.be/BZ6Trgl9JT0
/hub = back to server hub
You can use /stop instead.Rejoining same server has the same effect
I also used SlimeWorldManager
Sorry for my poor English.It's not my mother tongue

**Comment by EndMoyu** [comment]
When I configure pre-game-items in config.yml, the problem is solved.
