### ISSUE TITLE
Players can throw lobby items.

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#375]
**Describe the bug**
When you are in Lobby and press Q then it drops the item on ground.

**To Reproduce**
1. Start the server
2. setLobby
3. reconnect
4. you see lobby items
5. scroll to any one of them
6. click Q on keyboard

**Expected behavior**
The Item Should not be moveable or Dropable

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Server software: spigot
 - Server Version: 1.12.2
 - Plugin Version: 22.2

**Additional context**

**Comment by ajgeiss0702** [comment]
works fine on my server. try reproducing with only bedwars1058 installed

**Comment by ghost** [comment]
I still have problem with 1.8-1.12 bruh

**Comment by pukislukis** [comment]
> I still have problem with 1.8-1.12 bruh

if you have bedwars1058 arena setup. delete it.

**Comment by ghost** [comment]
> > I still have problem with 1.8-1.12 bruh
> 
> if you have bedwars1058 arena setup. delete it.

ok i will

**Comment by tomkeuper** [comment]
Closed due to the issue being stale, reopen if needed.
