### ISSUE TITLE
Add  total kills placeholder to bedwarsproxy

### ISSUE THREAD

**Issue by FootClick** [andrei1058/BedWars1058#376]
Is your feature request related to a problem? Please describe.
Add the total kills placeholderAPI to Bedwarsproxy

Describe the solution you'd like
Get a player's kills. (regular + final).
Placeholder: %bw1058_stats_total_kills% add to bedwarsproxy.

Describe alternatives you've considered
none

Additional context
none

**Comment by ajgeiss0702** [comment]
This is bedwars1058, not bedwarsproxy
