### ISSUE TITLE
Lose tool When rejoining

### ISSUE THREAD

**Issue by EndMoyu** [andrei1058/BedWars1058#385]
**Describe the bug**
When the player reconnects, the tool will be lost

**To Reproduce**
1. Join any Arena
2. Buy any tool
3. Then Discoonect
4. Rejoin Arena

**Expected behavior**
When reconnecting, have purchased tools

**Screenshots**
Currently Not

**System (please complete the following information):**
 - OS: Windows Server 2016
 - Paper
 - 1.8.8
 - 22.2

**Comment by tomkeuper** [comment]
Is this still accurate with the latest version?

**Comment by EndMoyu** [comment]
Yeah. I tried that @ 23.2.1 and it still not working.Still haven't given me tools after reconnecting :P

**Comment by tomkeuper** [comment]
What kind of tools are we talking about then? Items marked as `is-permanent: true` should be kept after rejoin, havent tested it myself tho but can you make sure this is true?

**Comment by EndMoyu** [comment]
> What kind of tools are we talking about then? Items marked as `is-permanent: true` should be kept after rejoin, havent tested it myself tho but can you make sure this is true?

I mean tools similar to picks axes or shears. And I have set `is-permanent: true`.

**Comment by tomkeuper** [comment]
what happend was that the plugin checked if an item was downgradeable or not, meaning if a tool could be downgraded it wouldnt add it to the list of items that would be given back to the player after a rejoin. 

In my opinion a rejoin is the same as a death so it would take 1 level of that item and then just respawn with all items that have `is-permanent: true`

**Comment by tomkeuper** [comment]
Will be fixed in the next release

**Comment by tomkeuper** [comment]
no clue why i reopened this...
