### ISSUE TITLE
Disconnecting Mid-game Deletes The Map

### ISSUE THREAD

**Issue by Xephyrose** [andrei1058/BedWars1058#389]
**Describe the bug**
When I join a game and then disconnect mid-game, it deletes the entire map and it becomes unrecoverable.

**To Reproduce**
1. Join the server
2. Right click the arena selector item in the fifth hotbar slot
3. Click the map you want to play (issue occurs with every map on my server)
4. Play the map for any amount of time
5. Disconnect from the server (not quite sure if all players need to leave or just one)
6. Bug occurs, stopping the server or rejoining it will still cause the issue

**Expected behavior**
Disconnecting will either eliminate you from the bedwars game or instead just cause you to respawn

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: [e.g. MacOS, Windows Server, Linux]
Windows 10 Home Edition
 - Server software [e.g. spigot, paper]
Paper
 - Server Version [e.g. 1.8.8]
1.8.8
 - Plugin Version [e.g. 21.11.2]
22.2

**Additional context**
Other than this issue the plugin works perfectly, I haven't installed SlimeWorldManager like it suggests and this was my first experience with the plugin. Other than this, amazing

**Comment by ajgeiss0702** [comment]
Do you have multiverse or any other world management plugin?

**Comment by Xephyrose** [comment]
Yes I have multiverse

**Comment by ajgeiss0702** [comment]
> Yes I have multiverse

Make sure multiverse doesn’t load arena worlds
Use /mv remove <map>
this command will remove the world from the multiverse configs, but will not delete the map files itself

bedwars1058 loads the maps itself, so if something else loads the maps, this can happen

**Comment by Xephyrose** [comment]
oh wow I didn't really think about that, thanks!

**Comment by ajgeiss0702** [comment]
> oh wow I didn't really think about that, thanks!

You’re welcome, and in the future please use discord first before opening a bug report ;)
