### ISSUE TITLE
Placeholder that counts the players of the groups

### ISSUE THREAD

**Issue by samupro-dev** [andrei1058/BedWars1058#392]
**Is your feature request related to a problem? Please describe.**
Add a placeholder that tells you how many players are currently playing in that group. Like `%bw1058_group_count_[group]%`

**Describe the solution you'd like**
Add the placeholder `%bw1058_group_count_[group]%`

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by Xxyuri2005xX** [comment]
On the wiki you can find a Placeholders List, already exits this placeholder.

**Comment by samupro-dev** [comment]
@Xxyuri2005xX could you write me the placeholder or tell me where this placeholder is?

**Comment by Xxyuri2005xX** [comment]
https://gitlab.com/andrei1058/BedWars1058/-/wikis/papi-hook
Next time i suggest you reading the Wiki

**Comment by samupro-dev** [comment]
@Xxyuri2005xX I read that section there, you can see that it escaped me, in fact I also went to see the list of placeholders on the papi github
In any case, thanks anyway
