### ISSUE TITLE
Bedwars1058 doesn't work on PaperSpigot 1.18.1

### ISSUE THREAD

**Issue by SpiziTV** [andrei1058/BedWars1058#393]
New version doesn't work with PaperSpigot 1.18.1.
I've got an issue with bedwars1058, here are the logs https://pastebin.com/nrQJUsQ7
[17:27:24] [Server thread/ERROR]: Error occurred while enabling BedWars1058 v22.2 (Is it up to date?)

**Comment by tomkeuper** [comment]
https://wiki.andrei1058.dev/docs/BedWars1058/compatibility
