### ISSUE TITLE
fireballs have fire when make-fire is false

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#396]
**Describe the bug**
im using bedwars v22.2 and bungee mode, my fireballs have fire 

**To Reproduce**
1. Go to a bedwars match
2. buy a fireball and shoot it

**Screenshots**
(https://cdn.discordapp.com/attachments/908744965008547891/944682231270613102/2022-02-19_12.45.53.png)

**System (please complete the following information):**
 - OS: [Windows Server 2019]
 - Server software [PAPER]
 - Server Version [1.8.8]
 - Plugin Version [22.2]

**Comment by TheWylot** [comment]
@ajgeiss0702 i think just u can help me cause you remade fireball system

**Comment by ghost** [comment]
He Fixed it and will be implemented in the next update.lol

**Comment by ajgeiss0702** [comment]
Yep it’s already fixed ;)
