### ISSUE TITLE
SQL time out issue

### ISSUE THREAD

**Issue by HEMO313** [andrei1058/BedWars1058#41]
Describe the bug
SQL time out issue on MySQL
LOG: https://sourceb.in/S2Pnkxf107

To Reproduce

Join the server
Leave from the server.
See an error https://sourceb.in/S2Pnkxf107
Expected behavior
No error on the console and the data should be saved!

Screenshots

System (please complete the following information):

OS: Linux
Server software Paper
Server Version 1.8.9
Plugin Version 21.10.1

**Comment by andrei1058** [comment]
It has been already fixed. Next time you want to report sonething try using the search feature to check if you're not making a duplicate. The update will be released soon.
