### ISSUE TITLE
Add configurable generator-protection setting

### ISSUE THREAD

**Issue by SameshB** [andrei1058/BedWars1058#411]
**Is your feature request related to a problem? Please describe.**
Most servers have generator protection: 3, with spawn-protection: 0, so blocks can be placed in the team islands easily with this setting, which makes it easier for players to block trap their enemies or just placing blocks in general is useful to escape from the enemies when low health or for other purposes.

**Describe the solution you'd like**
Add generator-protection config in generators.yml, config.yml or individual arenas config.

**Describe alternatives you've considered**
I mean, the current alternative is that you can set the spawn-protection to 1, but it isn't as good as setting the generator prote
ction to 3 and spawn protection to 0.

**Additional context**
Might also want to change the default value for generator-protection to 3 and spawn protection to 0, I think that's better. Just a suggestion. Because, with this config, the players spawn point has to be set exactly 3 blocks away from the generator, if players set spawn point further than that, then players will be able to completely enclose enemies in a 1x1x3 cage. 

Image: Currently, the default generator-protection is 1, and not configurable.
![image](https://user-images.githubusercontent.com/48585698/155745007-7d455a7d-db83-4eb7-8344-5b41a0b97ece.png)

**Comment by ajgeiss0702** [comment]
> Because, with this config, the players spawn point has to be set exactly 3 blocks away from the generator, if players set spawn point further than that, then players will be able to completely enclose enemies in a 1x1x3 cage.

Thats what spawn protection is for 😉
