### ISSUE TITLE
Duo, Trio, Quad - Tablist format problem.

### ISSUE THREAD

**Issue by MVPFizzy** [andrei1058/BedWars1058#415]
**Describe the bug**

It's a bug in bedwars DUO Gamemode tablist.

**To Reproduce**

**Expected behavior**

This is how it should be:
![2022-02-27_16 37 37](https://user-images.githubusercontent.com/97798480/155888397-66669913-f83c-4411-876f-3046fdd317af.jpg)

And This is what I have:
![2022-02-26_21 13 41](https://user-images.githubusercontent.com/97798480/155889407-3853f64a-2b35-4811-83ab-f9b319d8f1f4.png)

**Screenshots**

**System (please complete the following information):**
 - OS: Server hosted on hosting Revivenode.
 - Server software paper
 - Server Version 1.12.2
 - Plugin Version 22.2

**Additional context**

You should fix the DUO, TRIO, QUAD Problem in tablist.

**Comment by ajgeiss0702** [comment]
#146
