### ISSUE TITLE
Team Text is bugging on Tab

### ISSUE THREAD

**Issue by HooneyCloud** [andrei1058/BedWars1058#424]
In game on tab the prefix have a space, sometimes its Red not the R letter

**Expected behavior**
Like on hypixel, no additonal spaces, and prefixes bugging
Hypixel Screenshot:
![Bez tytułu](https://user-images.githubusercontent.com/80839020/156435611-d6822467-7234-449d-b957-e39ec1ed3938.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/80839020/156435035-195dbf41-3531-4d97-9d20-8ee6dee5b43f.png)
![image](https://user-images.githubusercontent.com/80839020/156435147-68c64d30-7fdf-4d58-bb3e-6a92d22e5168.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Server software Paper
 - Server Version 1.8.9
 - Plugin Version 21.11.2

**Comment by ajgeiss0702** [comment]
You can change it in the language file
