### ISSUE TITLE
Leave game item not working when looking on a block.

### ISSUE THREAD

**Issue by itzdrli** [andrei1058/BedWars1058#429]
**Describe the bug**
Leave game item not working when looking on a block.

**To Reproduce**
1. Join the arena
2. right click the item names Back to lobby
3. if you are looking on a block, its not working
4. if i am looking at nothing, it will be work
-->

**Expected behavior**

**System (please complete the following information):**
 - OS: Linux, ubuntu20.04
 - Server software NachoSpigot
 - Server Version 1.8.8
 - Plugin Version 22.2

**Comment by reussy** [comment]
It works for me, what item do you have on?
It doesn't make much sense 😅
