### ISSUE TITLE
all players in same team if online players <= 1 team's max players

### ISSUE THREAD

**Issue by itzdrli** [andrei1058/BedWars1058#434]
when players join like 2 players and one team's max players are 4, then all players will be in the same team.and the game will be end till some left(except spec.)

**System (please complete the following information):**
 - OS: ubuntu20.04
 - Server software nachospigot
 - Server Version 1.8.8
 - Plugin Version 22.2

**Comment by MherZaqaryan** [comment]
You can fix this, if you set `minPlayers` 4 or higher
