### ISSUE TITLE
An option to change the shop & upgrades title and slots

### ISSUE THREAD

**Issue by PersianDevs** [andrei1058/BedWars1058#437]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to change the shop & upgrades title and slots

**Describe alternatives you've considered**

**Additional context**

**Comment by sreyas0001** [comment]
WDYM?
I am interested to know

**Comment by reussy** [comment]
You can change the title at messages_**<*language*>**.yml

The slots I think it's not possible to add, the menus are sorted based on default slots

**Comment by ajgeiss0702** [comment]
You can customize the slots in the shop in shop.yml, and you can change names/titles/lore in the language files
