### ISSUE TITLE
Arena selector item ids not supported

### ISSUE THREAD

**Issue by Trinchezito** [andrei1058/BedWars1058#443]
On server 1.16, 1.17, 1.18+ this appears when you open a gui arena menu. 

![image](https://user-images.githubusercontent.com/98068350/158259875-8670ae2e-ad03-4403-9501-1e98bc11b9cf.png)
![image](https://user-images.githubusercontent.com/98068350/158259927-8d163c72-e4b6-4a4e-91d2-457ff2d9fd97.png)

**Comment by ajgeiss0702** [comment]
Config issue. Answered on discord
