### ISSUE TITLE
Maven repo and Javadocs not working

### ISSUE THREAD

**Issue by KadTheAad** [andrei1058/BedWars1058#444]
**Describe the bug**

It just isnt loading
**To Reproduce**

**Expected behavior**

View website
**Screenshots**

<img width="1136" alt="Screen Shot 2022-03-15 at 10 36 45 AM" src="https://user-images.githubusercontent.com/69099988/158320826-267da2c3-fa20-4fb2-aec1-73bca85f3c30.png">
**Additional context**

**Comment by Xxyuri2005xX** [comment]
Andrei changed domain and he is working for updating them, on discord server aj gave a temp javadocs
