### ISSUE TITLE
Unknown error shutting down server/plugin.

### ISSUE THREAD

**Issue by EvilG-MC** [andrei1058/BedWars1058#457]
**Describe the bug**
"Random" error or so I think, it only appears when the server stops.

**To Reproduce**
Well I just downloaded the latest version and got that error when the server went down.

**System:**
 - OS: Ubuntu
 - Server software: Paper Spigot
 - Server Version: 1.17.1
 - Plugin Version: 22.3.4

**Additional context**
Server logs: [here](https://www.toptal.com/developers/hastebin/caxorewate.yaml)
Error: [here](https://www.toptal.com/developers/hastebin/suweweceha.properties) or see in the image
![image](https://user-images.githubusercontent.com/71156616/160044737-66afe5b6-2865-44fd-bd32-7237cf989693.png)

**Comment by JT122406** [comment]
Can you post a paste.gg of our full server log from start to end

**Comment by EvilG-MC** [comment]
> Can you post a paste.gg of our full server log from start to end

Sure https://paste.gg/p/anonymous/161b5699936049639a087b59645f3a14
