### ISSUE TITLE
When placing the TNT an error appears on the console.

### ISSUE THREAD

**Issue by EvilG-MC** [andrei1058/BedWars1058#459]
**Describe the bug**
When placing the TNT to break some bed or do tnt jump, it does not push, and it does too much damage, when it should not damage or at least not too much.

**To Reproduce**
1. Enter a BW Game
2. Get a TNT
3. Put the TNT

**Expected behavior**
I guess not going down all health and pushing the player, which is not currently the case.

**Screenshots**
![image](https://user-images.githubusercontent.com/71156616/160149375-03579b94-3b23-4f3e-aa7b-ee4faef0d5b4.png)
![image](https://user-images.githubusercontent.com/71156616/160149433-e93df404-b899-452a-9326-8141a3e6db47.png)

**Aditional Context**
I don't know if it is due to some configuration since I am using the one I made in version 22.2 so I don't know if it can be, I tried with version 22.2 and the same error occurs.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Server software: Paper Spigot
 - Server Version: 1,17.1
 - Plugin Version: 22.3.4

**Video**

https://user-images.githubusercontent.com/71156616/160149846-1d31a5d0-19ac-4c1b-a12b-6f20bbe9170e.mp4

**Comment by Xxyuri2005xX** [comment]
1.17 is still experimental.

**Comment by EvilG-MC** [comment]
> 1.17 is still experimental.

Well, previously it did not happen and I thought it was a problem with the plugin.

**Comment by ajgeiss0702** [comment]
> > 1.17 is still experimental.
> 
> Well, previously it did not happen and I thought it was a problem with the plugin.

Did it not happen on 22.2? (still on 1.17)

**Comment by EvilG-MC** [comment]
> > > 1.17 is still experimental.
> > 
> > 
> > Well, previously it did not happen and I thought it was a problem with the plugin.
> 
> Did it not happen on 22.2? (still on 1.17)

When I tried a few months ago no, when the first releases of 1.17.1 came out, now when trying the same error happens.
I guess something changed in some update.

**Comment by ajgeiss0702** [comment]
> > > > 1.17 is still experimental.
> > > 
> > > 
> > > Well, previously it did not happen and I thought it was a problem with the plugin.
> > 
> > 
> > Did it not happen on 22.2? (still on 1.17)
> 
> When I tried a few months ago no, when the first releases of 1.17.1 came out, now when trying the same error happens. I guess something changed in some update.

Thats weird, it doesn't look like anything with that part of the code has changed since 1.17 support came out in bedwars.

Are you sure nothing else other than updating bedwars has changed? Have you used a different mc version, different fork, etc

**Comment by EvilG-MC** [comment]
> Thats weird, it doesn't look like anything with that part of the code has changed since 1.17 support came out in bedwars.
> 
> Are you sure nothing else other than updating bedwars has changed? Have you used a different mc version, different fork, etc

Well, I updated BedWars yesterday and those errors started, and no, I haven't used another version or fork of paper, I've used paper for a long time.

**Comment by ajgeiss0702** [comment]
> > Thats weird, it doesn't look like anything with that part of the code has changed since 1.17 support came out in bedwars.
> > Are you sure nothing else other than updating bedwars has changed? Have you used a different mc version, different fork, etc
> 
> Well, I updated BedWars yesterday and those errors started, and no, I haven't used another version or fork of paper, I've used paper for a long time.

And 22.2 worked fine on 1.17.1?

**Comment by EvilG-MC** [comment]
> > > Thats weird, it doesn't look like anything with that part of the code has changed since 1.17 support came out in bedwars.
> > > Are you sure nothing else other than updating bedwars has changed? Have you used a different mc version, different fork, etc
> > 
> > 
> > Well, I updated BedWars yesterday and those errors started, and no, I haven't used another version or fork of paper, I've used paper for a long time.
> 
> And 22.2 worked fine on 1.17.1?

Well, even what I tried if it worked, until today.

**Comment by ava852546** [comment]
The same problem occurs in paper 1.18.1

**Comment by tomkeuper** [comment]
Duplicate of #395 
TNT rework is also comming up. This issue will be linked to the original post incase we need more info.
