### ISSUE TITLE
Generator issue on win 

### ISSUE THREAD

**Issue by NeosKing108** [andrei1058/BedWars1058#463]
**Describe the bug**
When you win a game and enter the generator, you collect the materials left over from the game and they have custom names such as custom0, custom1, etc.

Youtube video: https://youtu.be/1lMN5DCsBbE

**To Reproduce**
1. Join a game
2. Win the game
3. Uncollected items remain in the generator
4. When you pickup them they have custom names like custom0, etc

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software: Paper
 - Server Version: 1.8.8
 - Plugin Version: Bedwars1058 22.3.4
**Additional context**

**Comment by ajgeiss0702** [comment]
This is a feature request, not a bug

**Comment by NeosKing108** [comment]
I have not seen the feature request
I'll open suggestion on github rn

**Comment by NeosKing108** [comment]
i opened it: #464
