### ISSUE TITLE
Heal pool upgrades

### ISSUE THREAD

**Issue by SpiziTV** [andrei1058/BedWars1058#466]
**To see what i'm talking about**
1. Join a Bedwars arena
2. Start a game
3. Buy heal pool upgrade
4. Look at the effect given it's "Regeneration II"

**Expected behavior**
I expect that the effect which is gived to the player is "Regeneration I" like Hypixel

**Bedwars upgrades config**
upgrade-heal-pool:
  tier-1:
    currency: diamond
    cost: 1
    display-item:
      material: BEACON
      data: 0
      amount: 1
      enchanted: false
    receive:
    - 'player-effect: REGENERATION,1,0,base'

It's already set on "1" but it give Regen II
I've try with 0 but with 0 it give me no effect

**System**
 - OS: Debian 10
 - Server software: Spigot
 - Server Version: 1.8.8
 - Plugin Version: 22.3.4

**Comment by MherZaqaryan** [comment]
This is a wrong section to report kind of issue, use [this](https://gitlab.com/bedwars-addons/bedwars1058-healpool/-/issues?sort=created_date&state=opened) instead.
