### ISSUE TITLE
PvP and Crosskill

### ISSUE THREAD

**Issue by CyriacF** [andrei1058/BedWars1058#47]
**Describe the bug**
On the BedWars1058 plugin the pvp is not fluid and you can crosskill too easily

**To Reproduce**
Play and see that there is a gap in the moves given by the players

**Expected behavior**
there is a lag on the moves in PvP, as if the moves were processed then executed on the server, which makes it possible to crosskill too easily

**System (please complete the following information):**
 - OS: Debian 10
 - Server software Paper
 - Server Version 1.8.9
 - Plugin Version 21.7.2

**Comment by termanator1128** [comment]
WTF does "crosskill" mean? And the plugin does not mess with PVP at all so that is an issue with your server.

**Comment by CyriacF** [comment]
> WTF does "crosskill" mean? And the plugin does not mess with PVP at all so that is an issue with your server.

On my server it's the only plugin that creates a lag in pvp, people kill each other way too easily and the pvp is a bit laggy, it's weird

**Comment by kimoVoid** [comment]
This issue is definitely caused by your plugins, ping, or hardware. BW1058 does not modify PvP at all. This should be a suggestion to implement a crosskill fix as a feature, not a bug.
