### ISSUE TITLE
Shop Items disappearing about shift+click

### ISSUE THREAD

**Issue by ExceptedPrism3** [andrei1058/BedWars1058#471]
**Describe the bug**
**To Reproduce**
1. Shift-click an item in the shop

**Expected behavior**
You should see a ghost item in your hot-bar and then a glass covering the original item in the shop

**Screenshots**
https://cdn.discordapp.com/attachments/670955085521616896/947486351534719036/unknown.png
https://cdn.discordapp.com/attachments/670955085521616896/947486351870271488/unknown.png

**System (please complete the following information):**
 - OS: Linux
 - Server software: Paper
 - Server Version: 1.8.8
 - Plugin Version: Latest

**Comment by sreyas0001** [comment]
Its What is called Quick Buy
Its a Feature Not a bug lol.
Close This or be dump.
You just normally click

**Comment by ExceptedPrism3** [comment]
> Its What is called Quick Buy Its a Feature Not a bug lol. Close This or be dump. You just normally click

What feature are you talking about?

Try it first before speaking

**Comment by Eradiator** [comment]
> > Its What is called Quick Buy Its a Feature Not a bug lol. Close This or be dump. You just normally click
> 
> What feature are you talking about?
> 
> Try it first before speaking

Actually Lolfin is right it not a bug lol😂

**Comment by Eradiator** [comment]
> > Its What is called Quick Buy Its a Feature Not a bug lol. Close This or be dump. You just normally click
> 
> What feature are you talking about?
> 
> Try it first before speaking

Its called Quick Buy Layout changer though

**Comment by ExceptedPrism3** [comment]
> > > Its What is called Quick Buy Its a Feature Not a bug lol. Close This or be dump. You just normally click
> > 
> > 
> > What feature are you talking about?
> > Try it first before speaking
> 
> Actually Lolfin is right it not a bug lol😂

How come it happens in my case? What's causing it?

**Comment by Eradiator** [comment]
> > > > Its What is called Quick Buy Its a Feature Not a bug lol. Close This or be dump. You just normally click
> > > 
> > > 
> > > What feature are you talking about?
> > > Try it first before speaking
> > 
> > 
> > Actually Lolfin is right it not a bug lol😂
> 
> How come it happens in my case? What's causing it?

Its a feature lmao...
Just dont use shift while clicking......
Just try same on hy....
