### ISSUE TITLE
大厅物品开关

### ISSUE THREAD

**Issue by wordangyou** [andrei1058/BedWars1058#477]
**Is your feature request related to a problem? Please describe.**
大厅物品无法自主删除

**Describe the solution you'd like**
在config.yml添加开启关闭选项：选择器，返回大厅，战绩

**Describe alternatives you've considered**
在config.yml添加开启关闭选项

**Additional context**
![image](https://user-images.githubusercontent.com/54358153/162253181-cf674865-f563-4505-96db-d38960f1abcf.png)

**Comment by ajgeiss0702** [comment]
Please use english
