### ISSUE TITLE
Genarator spawnlimit not working

### ISSUE THREAD

**Issue by FawnDuck** [andrei1058/BedWars1058#481]
**To Reproduce**

**System (please complete the following information):**
 - OS:

**Comment by ajgeiss0702** [comment]
You provided almost no information. I just tested it on my server and it works fine

**Comment by JT122406** [comment]
Does it always not work or only certain area groups or?

**Comment by SainteKhalifa** [comment]
![image](https://user-images.githubusercontent.com/61852144/163288059-ab52f189-f3a3-4455-ab1a-84abf177e949.png)
Same bug Solo, 4 teams, start game with one player minimum.
Bug work only on my team when i play solo for test.
![image](https://user-images.githubusercontent.com/61852144/163288020-cd3440cf-9216-403a-91c9-4096f7024f12.png)

**Comment by SainteKhalifa** [comment]
I checked, the problem appears when we improve the forge, there is no more item spawn limit.

**Comment by tomkeuper** [comment]
Is it still relevant? Does it happen on the latest version? please provide a server log if thats the case

**Comment by FawnDuck** [comment]
No not really
