### ISSUE TITLE
New suggestions, the first suggestion: make on respawning mode in invis effect

### ISSUE THREAD

**Issue by ItzSuolis** [andrei1058/BedWars1058#504]
Hello, I have 2 suggestions for the next update for the bedwars1058 plugin to make it like hypixel more!
The first suggestion: Make the respawing mode to be in invis effect like this 
![Screenshot_4](https://user-images.githubusercontent.com/104707665/166132617-ad6e4668-eedc-4150-866b-3fd2eea43cad.png)
Not like this 
![Screenshot_3](https://user-images.githubusercontent.com/104707665/166132624-1df96233-379f-4645-8483-dad19fe4e96f.png)

I hope you accept them if u accepted them this will make ur plugin the best hypixel free bedwars plugin in the world

Regards, ItzSuolis

**Comment by ajgeiss0702** [comment]
Re-make with 2 seperate issues for each suggestion
