### ISSUE TITLE
Error upon joining with a Party with Parties by Alessio

### ISSUE THREAD

**Issue by itsWarHammer** [andrei1058/BedWars1058#510]
**Describe the bug**
Error when joining an arena with a party from Parties by Alessio

**To Reproduce**
1- Make a party
2- have the other player accept
3- join any arena
4- error pops up in chat
https://bin.bloom.host/efutukinir.properties

**Expected behavior**
No error

**Screenshots**
None

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.8.8
 - Plugin Version: 22.3.4

**Additional context**
This is with BedWars Proxy and Parties on Bungee mode, The error appears only on the first time you join an arena, if you click again, it will let you in with your members

**Comment by ajgeiss0702** [comment]
This is for bedwars1058, not bedwarsproxy
