### ISSUE TITLE
<Bug> Death cause end of the game

### ISSUE THREAD

**Issue by IceCubeFr** [andrei1058/BedWars1058#515]
Hello
I'm devlopping my server in Spigot 1.8.9, bedwars V22.3.4 and I have a problem
When someone dies, the game ends like the player didn't have bed
The problem is the player had a bed
he is teleported in a mi,echafts with french text
I think the problem come from MultiverseCore because there is this message in console : 
> [15:14:32 WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
> [15:14:32 WARN]: [Multiverse-Core] To let Multiverse know about it, use:
> [15:14:32 WARN]: [Multiverse-Core] /mv import solo NORMAL
Is it possible to have more informations in how to disable this please
Thanks very much

**Comment by ajgeiss0702** [comment]
It’s not a bug. It’s most likely a plugin teleporting the player to the spawn on death

Then bedwars removes them from the game because they were teleported outside the arena

**Comment by IceCubeFr** [comment]
Okay but how can I stop that ?

**Comment by ajgeiss0702** [comment]
Find the plugin causing it
