### ISSUE TITLE
Bedwars1058-Fireball Jump Config

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#52]
1.Hey @andrei1058 Can you please add fireball damage and kb config to your plugin so that we can reduce the amount of plugins that we use for the server and the fireball jump addons only supports 1.8.8 not 1.16 or 1.17 so it would be helpful if you add it to the config file of the plugin like tnt jump.

**Comment by andrei1058** [comment]
Use the proper issue template.
