### ISSUE TITLE
Invisibility potion not functioning

### ISSUE THREAD

**Issue by hugeBlack** [andrei1058/BedWars1058#522]
**Describe the bug**
Invisibility potions only makes yourself invisible, instead of you and your armor
**To Reproduce**
1. You and your friend join an arena in different teams
2. buy an invisible potion and drink it.
3. You friend can still see your armor.

**Expected behavior**
The player as well as his armors become invisible.

**System (please complete the following information):**
 - OS: Windows
 - Server software Paper
 - Server Version 1.18.1
 - Plugin Version 22.3.4
 - 
**Additional context**
It seems that the potion listener is not properly registered.
I'll try to fix this in my pull request.

**Comment by andrei1058** [comment]
Will be fixed in the next release

**Comment by tomkeuper** [comment]
Can this be closed?

**Comment by tomkeuper** [comment]
Closed because merged
