### ISSUE TITLE
When there is TNT in the player's backpack, a red particle effect appears on the top of the player's head

### ISSUE THREAD

**Issue by BingYanchi** [andrei1058/BedWars1058#525]
**Is your feature request related to a problem? Please describe.**
When there is TNT in the player's backpack, a red particle effect appears on the top of the player's head

**Describe the solution you'd like**
When a player's backpack contains a TNT, there will be a red particle effect on the top of the head to remind other players to pay attention.

**Describe alternatives you've considered**
no

**Comment by reussy** [comment]
it's already in the plugin
#270

**Comment by BingYanchi** [comment]
> it's already in the plugin #270

Does it work in version `22.3.4`? I can't to see it. I am using `Paper 1.13.2`
