### ISSUE TITLE
I cant leave bedwars !

### ISSUE THREAD

**Issue by Kinsley12off** [andrei1058/BedWars1058#526]
**I cannot exit a bedwars game when i wait**

**Screenshots**
![image](https://user-images.githubusercontent.com/90274285/170102009-bb86ee1b-58ff-46c9-b5c3-c8d6739ba3f8.png)

**System (please complete the following information):**
 - OS: Windows11
 - Server software paper
 - Server Version 1.18.1
 - Plugin Version 21.11.2

**Comment by ajgeiss0702** [comment]
Update bedwars and try again
