### ISSUE TITLE
During Sudden Death, generators are filled with air

### ISSUE THREAD

**Issue by BingYanchi** [andrei1058/BedWars1058#529]
**Describe the bug**

I don't know why, the generators are filled with air during the Sudden Death phase.

**To Reproduce**
1. Wait for Sudden Death
2. Look generators

**Expected behavior**

**Screenshots**

![2022-05-28_00 37 07](https://user-images.githubusercontent.com/36477925/170749178-4318c2a5-b0d4-4e07-857e-01ceccc28be5.png)
![2022-05-28_00 37 30](https://user-images.githubusercontent.com/36477925/170749234-a72a0bac-e111-4827-afb6-bf1f9d978b16.png)

**System (please complete the following information):**
 - OS: Windows Server 2021
 - Server software paper
 - Server Version 1.18.1
 - Plugin Version 22.3.4

**Additional context**

**Comment by hugeBlack** [comment]
看了眼代码好像就是这么设计的（
你可以看 https://github.com/andrei1058/BedWars1058/blob/98cfa34e3fed2e4106cd4228af7269b08938e6d2/bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/tasks/GamePlayingTask.java#L145 145到158行（

**Comment by BingYanchi** [comment]
> 



> 看了眼代码好像就是这么设计的（ 你可以看
> 
> https://github.com/andrei1058/BedWars1058/blob/98cfa34e3fed2e4106cd4228af7269b08938e6d2/bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/tasks/GamePlayingTask.java#L145
> 
> 145到158行（

奇妙，不理解为什么这么设计

**Comment by andrei1058** [comment]
Why you taxting in chinese guys? I do not understand it. Also this is the correct behaviour accoring to hypixel.

**Comment by BingYanchi** [comment]
请耐心等待加载完毕...

**Comment by tomkeuper** [comment]
I am not really sure if this is actually correct behaviour. when the dragons are out generators normally still work. Not sure about diamond and emerald gen tho

**Comment by hugeBlack** [comment]
> Why you taxting in chinese guys? I do not understand it. Also this is the correct behaviour accoring to hypixel.

I recently played a bedwar game in Hypixel. During the deathmatch, generators kept working even if dragons destroyed the blocks under them. So, I believe this behavior is not corresponded to Hypixel. Maybe you can provide a switch in config file to decide whether the generators should be destroyed during deathmatch?

**Comment by BingYanchi** [comment]
> I am not really sure if this is actually correct behaviour. when the dragons are out generators normally still work. Not sure about diamond and emerald gen tho

Blocks below generators will be filled with air

**Comment by EndMoyu** [comment]
> I am not really sure if this is actually correct behaviour. when the dragons are out generators normally still work. Not sure about diamond and emerald gen tho

FALSE. In Hypixel, Blocks below generators will NOT be filled with air.Including diamond and emerald.
When the blocks below the generators are destroyed by dragon. the generators works normally

**Comment by tomkeuper** [comment]
Closing as completed
