### ISSUE TITLE
Stats by arena type

### ISSUE THREAD

**Issue by Heazzz** [andrei1058/BedWars1058#532]
Hello,

Would it be possible to obtain stats according to the mode (solo, duos, etc...)

To get more placeholders on bw1058 & bw1058proxy: %bw1058_stats_kills_\<mode>%

Thanks you guys.
Your plugin is good work!

**Comment by Heazzz** [comment]
Don't working bungeecord, but he work in Multiarena

**Comment by Xxyuri2005xX** [comment]
#568
