### ISSUE TITLE
Silverfish not spawning! 

### ISSUE THREAD

**Issue by navin-hariharan** [andrei1058/BedWars1058#539]
SILVERFISH NOT SPAWNING

**Describe the bug**

**To Reproduce**
Launch Minecraft 1.18.2! Server version paper 1.8 
The silverfish do not spawn

**Expected behaviour**
Silverfish should spawn with the team name

**Screenshots**
![image](https://user-images.githubusercontent.com/42506955/172257215-872fc392-1f3d-439d-a86b-f79bf901778a.png)

**System (please complete the following information):**
 - OS: Windows Server, Linux
 - Server software Paper
 - Server Version 1.18
 - Plugin Version 22.3.4
 

**Additional context**
The fish spawns but is not visible

I am using ViaVersion

**Comment by JT122406** [comment]
This is a Viaversion issue and is not fixable on the plug-in side

**Comment by navin-hariharan** [comment]
> This is a Viaversion issue and is not fixable on the plug-in side

Acknowledging this! I have removed ViaVerrsion from my server but I still face the same issue

**Comment by navin-hariharan** [comment]
![image](https://user-images.githubusercontent.com/42506955/172296176-370d869d-a986-4c15-87f7-fe19d8675690.png)

**Comment by hugeBlack** [comment]
1.18 support is buggy in version 22.3.4 and this is one of the bugs it has. I've fixed the bugs I had encountered in my fork, so you can try to build from my pr #509

**Comment by navin-hariharan** [comment]
Thankyou @hugeBlack

**Comment by andrei1058** [comment]
The pull request might be implemented in a future update. Please dich multiverse!
