### ISSUE TITLE
Database not working

### ISSUE THREAD

**Issue by LeafPlays** [andrei1058/BedWars1058#543]
**Describe the bug**
Client does not support authentication protocol requested by server; consider upgrading MySQL client

**To Reproduce**
Fill up database information

**Expected behavior**
Should work

**Screenshots**
![image](https://user-images.githubusercontent.com/65165819/174476125-726bd867-fe00-4aaf-98e2-a2c812532d88.png)

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.8.8
 - Plugin Version 22.34

**Additional context**
Using the latest version of MySQL

**Comment by RinR1nMC** [comment]
All minecraft plugins now support only mysql 5.7.So you should uninstall mysql 8 and install 5.7 version

**Comment by LeafPlays** [comment]
oh alright thanks
