### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by 80486gx2** [andrei1058/BedWars1058#544]
PLS

**Comment by RinR1nMC** [comment]
shut the fuck up.1.19 is trash

**Comment by Eradiator** [comment]
> shut the fuck up.1.19 is trash

I would never use any versions higher than 1.16.5 or to be more accurate 1.12+

**Comment by Eradiator** [comment]
but some people may be running the server along with Their survival servers

**Comment by RinR1nMC** [comment]
But why must andrei need to update 1.19?

**Comment by Eradiator** [comment]
> But why must andrei need to update 1.19?

it feels more attractive when a plugin supports the latest version rather than support of old version

**Comment by 80486gx2** [comment]
For me it's nice to be able to run one server with all of my plugins instead of having different ones for different versions. He updated it to 1.18.2 why can't he update it to 1.19?

**Comment by ajgeiss0702** [comment]
> For me it's nice to be able to run one server with all of my plugins instead of having different ones for different versions. He updated it to 1.18.2 why can't he update it to 1.19?

He actually isn’t even finished 1.18.2 support, he’s kinda MIA

**Comment by Eradiator** [comment]
i think he is travelling outside his country or something

**Comment by lunoxxofficial** [comment]
> For me it's nice to be able to run one server with all of my plugins instead of having different ones for different versions. He updated it to 1.18.2 why can't he update it to 1.19?

1.18.2 Support is totally unstable and full of errors  . I prefer using 1.8 or 1.12.2 
1.16.5 is the stable version for every plugin imo .

**Comment by 80486gx2** [comment]
@andrei1058

**Comment by RinR1nMC** [comment]
Stop using 1.18 version above

**Comment by 80486gx2** [comment]
If you don't like 1.19, you can stop posting in this thread.

**Comment by tomkeuper** [comment]
added in latest updates
