### ISSUE TITLE
Versionsupport_v1_19_R1

### ISSUE THREAD

**Issue by navin-hariharan** [andrei1058/BedWars1058#550]
When PLAYERS with the 1.19 version fall into the VOID they lose connection! Please fix this!

I Run a survival server too! Therefore most clients use 1.19!

**Comment by Memexurer** [comment]
any errors in console?

**Comment by navin-hariharan** [comment]
> any errors in console?

No errors in console

**Comment by navin-hariharan** [comment]
@andrei1058 Can you please take a look at this?

**Comment by andrei1058** [comment]
1.19 is not officially supported yet!
