### ISSUE TITLE
Everyone is in the same team

### ISSUE THREAD

**Issue by 7AGAM** [andrei1058/BedWars1058#551]
**Describe the bug**

When you start a round and after the countdown ends, every player gets on the same team. That means you have no opponents and you only play in pairs on the same team.
**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 22.3.4

**Additional context**

**Comment by xyantoaster** [comment]
Add a player limit to each team and set it to 1/2/3/4 depending on the gamemode. You can set a player limit by going to Plugins > Bedwars1058 > Arenas > (arenaName).yml > Line 6: maxInTeam : 1/2/3/4

EDIT: To avoid having to set the max players to a team every time you create an arena, use the command /bw setType (solo,doubles,3v3v3v3,4v4v4v4) to automatically set the max players.

**Comment by andrei1058** [comment]
the author is inactive
