### ISSUE TITLE
BedWars1058 is overriding world files

### ISSUE THREAD

**Issue by xyantoaster** [andrei1058/BedWars1058#552]
**Describe the bug:**
When I try to set up an arena that already exists to change something with it, instead of going to the world file, it overrides it with a void world.

**To Reproduce**
1. Execute the command /bw setupArena (world)
2. When teleporter to the world, even though the world file already exists and has builds in it, it gets overridden with a void world.

**Expected behavior**
Go to the world file that already exists.

**Screenshots**

**System (please complete the following information):**
 - OS: Unknown (Likely Linux, as it is an Aternos server.)
 - Server software: PaperSpigot
 - Server Version 1.18
 - Plugin Version 22.3.4

**Additional context**
None

**Comment by Memexurer** [comment]
```
- you can now create empty maps by using /bw setupArena and paste your own schematic
```
https://github.com/andrei1058/BedWars1058/blob/master/CHANGELOG
lol

**Comment by andrei1058** [comment]
I guess it happens because 1.18 is not supported yet.
