### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#558]
**Describe the bug**

Allocolated 6GB Ram to a Arena Server, After 6h, its using 10GB MAX

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version

**Comment by andrei1058** [comment]
you need to provide more details if you want us to take this in consideration

**Comment by Memexurer** [comment]
maybe provide some heap dumps...

**Comment by TheWylot** [comment]
@andrei1058 its just for SWM & Autoclone, the world unload system after end game is not working ok, that cause a memory leak on the arena servers after a time

**Comment by andrei1058** [comment]
I do not work with speculations. sorry.
