### ISSUE TITLE
Issue with luckperms

### ISSUE THREAD

**Issue by RAFAELESPADA** [andrei1058/BedWars1058#564]
**Describe the bug**

The bug occours randomly and disconnects everyone from the bedwars game. Also the console gives this error when attempting to join the game https://pastes.dev/4nvZbdBsHW and the game continue to occour with nobody. appear it is a issue with luckperms and your plugin
**To Reproduce**
Occours randomly when i playing bedwars in the server
-->

**Expected behavior**

Just the game occour normally without issues
**Screenshots**

plugin list: https://prnt.sc/zQWf1DSVlaMe
**System (please complete the following information):**
 - OS: 
 - Linux
 - Server Version 
 - 1.8.8 
 - Plugin Version 
 - 22.3.4

**Additional context**

**Comment by tomkeuper** [comment]
Is this still accurate with the latest version?

**Comment by tomkeuper** [comment]
Closing due to being stale
