### ISSUE TITLE
problem with map randomization

### ISSUE THREAD

**Issue by haroldrc** [andrei1058/BedWars1058#571]
**Describe the bug**
I have a bungee mode server, but the maps are not random (the same map can happen 5 times in a row)

**To Reproduce**
1. download bedwars proxy and bedwars
2. set the mode to bungee

**Expected behavior**
random maps

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version bedwars proxy: 1.2.4 - bedwars1058: 22.3

**Additional context**

**Comment by andrei1058** [comment]
I guess this is a bedwarsproxy issue and you should report it on the other repository.

https://github.com/andrei1058/BedWarsProxy
