### ISSUE TITLE
Scoreboard weird bug

### ISSUE THREAD

**Issue by tuxymuxy** [andrei1058/BedWars1058#572]
**Describe the bug**

The scoreboard is bugged.
**To Reproduce**
1. Go to the server.
2. Join a game,
3. Start the game.

**Expected behavior**

The scoreboard works as normal
**Screenshots**

![image](https://user-images.githubusercontent.com/96945391/180943945-d32d931c-165e-491d-9b02-f3743bd5de85.png)

**System (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - Server software : Paper
 - Server Version 1.16.5
 - Plugin Version 22.3.4

**Additional context**

**Comment by andrei1058** [comment]
this is not a bug, it's a beginner mistake and bad configuration. if you lazy just replace existing text with {team}
