### ISSUE TITLE
Invisibility not working correctly

### ISSUE THREAD

**Issue by passsssssssss** [andrei1058/BedWars1058#573]
**Describe the bug**

Invisibility doesn’t work correctly. Player is invisible, but the armor is still visible to others (not just teammates)

**To Reproduce**
1.  Run Bedwars1058 on a Paper 1.12.2 server
2. Join a game and drink an invisibility potion

**Expected behavior**
Be invisible to others

**System (please complete the following information):**
 - OS: Linux, Ubuntu 20.04.4 LTS
 - Server software: PaperMC
 - Server Version: 1.12.2
 - Plugin Version: 22.7

**Comment by haroldrc** [comment]
me too

**Comment by andrei1058** [comment]
it was fixed and will be available in the next update

**Comment by tomkeuper** [comment]
Closed because merged
