### ISSUE TITLE
%bw1058_elapsed_time% Doesnt work

### ISSUE THREAD

**Issue by RinR1nMC** [andrei1058/BedWars1058#574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Windows Server 
 - Server software Paper 
 - Server Version 1.12.2
 - Plugin Version 21.11.2

**Additional context**

It is show nothing when i add %bw1058_elapsed_time% in tab config

**Comment by tomkeuper** [comment]
Will be fixed in the next release
