### ISSUE TITLE
shop problem

### ISSUE THREAD

**Issue by haroldrc** [andrei1058/BedWars1058#575]
**Describe the bug**
when I open the shop and click on my inventory, I can purchase the items in the shop from my inventory

**To Reproduce**
1. get into the game
2. open the shop
3. click in your inventory

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software  paper
 - Server Version 1.8.8
 - Plugin Version 22.3-SNAPSHOT

**Additional context**

**Comment by Xxyuri2005xX** [comment]
clone of #490

**Comment by andrei1058** [comment]
we are aware of that, but it is not a blocking issue

**Comment by andrei1058** [comment]
also it looks like it was fixed and will be availalble in the next update

**Comment by tomkeuper** [comment]
Does this need to stay open?

**Comment by Xxyuri2005xX** [comment]
issue got fixed with #590
