### ISSUE TITLE
Cloning arenas doesn't work

### ISSUE THREAD

**Issue by haroldrc** [andrei1058/BedWars1058#577]
**Describe the bug**
I have a bungee mode server, arenas are not cloned (I have configured everything, everything works but arenas are not cloned)

**To Reproduce**
1. download bedwars proxy and bedwars
2. set the mode to bungee
3. occupy all created arenas

**Expected behavior**
duplication of the map when they are full

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version: bedwars proxy: 1.2.4 - bedwars1058: 22.3

**Additional context**

**Comment by lunoxxofficial** [comment]
You can clone arena from the arena servers not in the lobby server, you'll have to be in arena server to clone them

**Comment by haroldrc** [comment]
don't they duplicate automatically when arenas are full? I am using "BUNGEE" mode.

**Comment by UnknownKeeper88888** [comment]
I have a similar issue. My lobbies clone but they don't reload. So when all arenas were played there is no more arenas

**Comment by haroldrc** [comment]
news?

**Comment by ghost** [comment]
Hello, I created my arena, all the commands are done but when I finish and I have to enable the arena they tell me 'Sapin' name of my arena don't exist why?

**Comment by andrei1058** [comment]
There is a setting for clone limit which I believe was reached, so if you have 30 instances and your games-before-restart setting is 30 the plugin will no longer clone games.

**Comment by haroldrc** [comment]
when an arena is full, it is not cloned. they are never cloned.

**Comment by tomkeuper** [comment]
Latest version doesnt have any auto scale issues as far as I know. If this issue still hapens feel free to reopen and make sure to post a full server log
