### ISSUE TITLE
Chat formatting bug

### ISSUE THREAD

**Issue by rastiqdev** [andrei1058/BedWars1058#578]
**Describe the bug**
The colon punctuation is not appearing between the usernames and the messages (spectators' messages don't have the bug)

**To Reproduce**
1. Go on a Bedwars game with BedwarsProxy
2. Type a message
3. See the error

**Expected behavior**
The colon being between the username and the message.

**Screenshots**
No screenshot needed

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Server software Spigot
 - Server Version 1.8.9 from GetBukkit
 - Plugin Version 22.3.4

**Comment by andrei1058** [comment]
I'm not sure what this is about. you should send screenshots. we lazy

**Comment by tomkeuper** [comment]
Closed due to inactivity

**Comment by rastiqdev** [comment]
just saw back this issue, it was just a typo in my lang file -_-
