### ISSUE TITLE
Tab format in language file shows abnormally/and customization doesn't work

### ISSUE THREAD

**Issue by zzj2039** [andrei1058/BedWars1058#579]
displayed in the tab as:
![uTools_1659983142785](https://user-images.githubusercontent.com/98182517/183489606-0dd23a3f-a6bf-4c6d-8da7-6564876ca307.png)
in the chat box as:
![uTools_1659983153400](https://user-images.githubusercontent.com/98182517/183489783-a378a103-1308-4eee-b211-5b7cbebe3fe6.png)

The first problem: the prefix and player name cannot be fully displayed in the tab

`format-sb-tab-suffix:
  restarting: '{vSuffix}&7[无公会]'
  playing: '{vSuffix}&7[无公会]'
  starting: '{vSuffix}&7[无公会]'
  waiting: '{vSuffix}&7[无公会]'
  lobby: '{vSuffix}&7[无公会]'`

I added some characters to the language file and it doesn't show up in the tab list suffix

 - OS: Windows Server 2012 R2
 - Server software spigot
 - Server Version 1.12.2
 - Plugin Version 22.3.4

**Comment by andrei1058** [comment]
I think there is a char limit to this. Could be fixed in a few weeks when we'll deploy the new sidebar system

**Comment by tomkeuper** [comment]
Is this issue fixed with the latest build? You could also test the latest dev build in discord if you are having issues

**Comment by tomkeuper** [comment]
closed due to being stale
reopen if needed
