### ISSUE TITLE
Bedwars1058 Levels Update

### ISSUE THREAD

**Issue by Xxyuri2005xX** [andrei1058/BedWars1058#58]
**Is your feature request related to a problem? Please describe.**
Bedwars1058 has an internal levelling system, but it is not complete

**Describe the solution you'd like**
Adding the Level rewards for Player Kill, Final kills, and Bed destroyed with the Customization in the file levels.yml and messages in the language file.

**Comment by Endernik** [comment]
Use Alonso levels! Have more functions.
