### ISSUE TITLE
Armor still visible for everyone after drink invisible postion

### ISSUE THREAD

**Issue by Varga-Levente** [andrei1058/BedWars1058#586]
Invisible potion not hide the armor. The click on the armor in the inventory triggers something and after it works until a death.
Video: https://streamable.com/3ahdwq
Plugin list:
![unknown](https://user-images.githubusercontent.com/47919682/185370366-b0bfe2c0-f741-4bf6-9ce5-ed07f2355caa.png)
Latest log: https://controlc.com/14cbe23c

**Comment by andrei1058** [comment]
Will be fixed in the next update
