### ISSUE TITLE
1.17 Error

### ISSUE THREAD

**Issue by unicoodev** [andrei1058/BedWars1058#589]
I Use PaperMC 1.17
but it's not working when i just issue the command: /pl
it just show me My other plugins in green and BedWars in red please fix this bug soon as possible >_<
and also please add a configurable scoreboard

**Comment by OlekAleksander** [comment]
No logs, you can edit the scoreboard in the language files...

**Comment by OlekAleksander** [comment]
No logs, you can edit the scoreboard in the language files...

**Comment by OlekAleksander** [comment]
No logs, you can edit the scoreboard in the language files...

**Comment by andrei1058** [comment]
1.17 is not supported
