### ISSUE TITLE
Economy Bugs

### ISSUE THREAD

**Issue by Xxyuri2005xX** [andrei1058/BedWars1058#59]
**Describe the bug**
I downloaded the Latest Bedwars1058 version and tested the Economy on the server, but i found some bugs.

**To Reproduce**
Kill a player and will give you money and send a red message where says: "Vault support missing"
Play for some minutes and will not send Message with the amount of coins.
There is no a placeholder for the Money counter in scoreboard

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Minecraft host (i think is Linux)
 - Server software: Spigot
 - Server Version 1.8.8
 - Plugin Version 21.11

**Additional context**

**Comment by ajgeiss0702** [comment]
Vault is required for the coins, aswell as an economy plugin

**Comment by manaspros** [comment]
this happen to me also i have vault and powerpoint for economy ,
idk why it happening

**Comment by ajgeiss0702** [comment]
This is addressed in #109

**Comment by manaspros** [comment]
It got fixed as i tryed essential x
