### ISSUE TITLE
player velocity error 

### ISSUE THREAD

**Issue by ProtoGhost** [andrei1058/BedWars1058#592]
https://pastebin.com/WzP76zDg
![image](https://user-images.githubusercontent.com/67905221/185925686-307404f7-1c76-4765-8af1-446de23c255e.png)

**System**

OS: Linux
Server software paperspigot
Server Version git-PaperSpigot-2894af04d (MC: 1.8.8)
Plugin Version bedwars-plugin-22.01

**Comment by andrei1058** [comment]
This is caused by yout tnt jump configuration. Player velocity is multiplied by the force you configured.
https://github.com/andrei1058/BedWars1058/blob/3324a181af7ce04d48dde24a67d8881e14358d63/bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/DamageDeathMove.java#L198

**Comment by tomkeuper** [comment]
Closed due to inactivity
