### ISSUE TITLE
Could not pass event UpgradeBuyEvent

### ISSUE THREAD

**Issue by ProtoGhost** [andrei1058/BedWars1058#593]
[07:53:40] [Server thread/ERROR]: Could not pass event UpgradeBuyEvent to BedWars1058 v22.01
--
894 | org.bukkit.event.EventException: null
895 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-2894af04d]
896 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-2894af04d]
897 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-2894af04d]
898 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-2894af04d]
899 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-2894af04d]
900 | at com.andrei1058.bedwars.upgrades.menu.MenuBaseTrap.onClick(MenuBaseTrap.java:275) [bedwars-plugin-22.01.jar:?]
901 | at com.andrei1058.bedwars.upgrades.listeners.InventoryListener.onInventoryClick(InventoryListener.java:50) [bedwars-plugin-22.01.jar:?]
902 | at jdk.internal.reflect.GeneratedMethodAccessor235.invoke(Unknown Source) ~[?:?]
903 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
904 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
905 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [server.jar:git-PaperSpigot-2894af04d]
906 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [server.jar:git-PaperSpigot-2894af04d]
907 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-PaperSpigot-2894af04d]
908 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-2894af04d]
909 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-2894af04d]
910 | at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [server.jar:git-PaperSpigot-2894af04d]
911 | at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-PaperSpigot-2894af04d]
912 | at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-PaperSpigot-2894af04d]
913 | at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-2894af04d]
914 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
915 | at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
916 | at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-2894af04d]
917 | at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-2894af04d]
918 | at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-2894af04d]
919 | at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-2894af04d]
920 | at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-2894af04d]
921 | at java.lang.Thread.run(Thread.java:833) [?:?]
922 | Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
923 | at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
924 | at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
925 | at com.andrei1058.bedwars.arena.upgrades.BaseListener.onUpgradeBuy(BaseListener.java:124) ~[?:?]
926 | at jdk.internal.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?]
927 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
928 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
929 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-2894af04d]
930 | ... 26 more

System

OS: Linux
Server software paperspigot
Server Version git-PaperSpigot-2894af04d (MC: 1.8.8)
Plugin Version bedwars-plugin-22.01

**Comment by tomkeuper** [comment]
Is this still up to date? If so try using the latest version

**Comment by tomkeuper** [comment]
Closed due to inactivity
