### ISSUE TITLE
maps are not filled

### ISSUE THREAD

**Issue by haroldrc** [andrei1058/BedWars1058#597]
**Describe the bug**
I have a bungee mode server, maps are not filled, players enter random maps without filling one.

**To Reproduce**
1. download bedwars proxy and bedwars
2. set the mode to bungee

**Expected behavior**
that players enter the map with multiple players waiting

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software paper (windspigot)
 - Server Version 1.8.8
 - Plugin Version bedwars proxy: 1.2.5 - bedwars1058: 22.7

**Additional context**

**Comment by Askarionn** [comment]
having the same issue

**Comment by tomkeuper** [comment]
Try latest version, and provide server log and preferabbly a little more detailed steps to reproduce

**Comment by tomkeuper** [comment]
Closed due to inactivity/ no info
