### ISSUE TITLE
Generating dirt screen as loading screen on both Bedrock and Java client

### ISSUE THREAD

**Issue by SunshroomChan** [andrei1058/BedWars1058#598]
**Describe the bug**
The plugin generating dirt screen as loading screen on Java but it not annoying while on Bedrock/GeyserMC the plugin making dirt screen more at least 5 second after that,  which is annoying for Bedrock players, compare to other Bedwars plugin it doesn't have that dirt screen as well

**To Reproduce**
1. Using latest Geyser version
2. Download Bedwars latest plugin and add-on

**Expected behavior**
When you died by killed by another player, died on void, etc...
Updated: Do /kill (player) on Lobby will be have same issue!

**Screenshots**
Video lead to bug:
https://drive.google.com/file/d/1S-B8qMgp0SLfvflQeg0e9_lBc-PDMaMn/view?usp=sharing
(Updated) Comparing to MBedwars (Marcely's Bedwars):
https://drive.google.com/file/d/16zjoZjkBXePwuEmJtEkqVOFNyoa_hU6o/view?usp=sharing

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.12.2
 - Plugin Version: Bedwars1058 22.7, GeyserMC latest

**Additional context**

**Comment by BlueTree242** [comment]
I would guess this is because you die, which causes client to do that (happens on vanilla), so maybe replacing death with teleport, clear health inventory would work?

**Comment by SunshroomChan** [comment]
> I would guess this is because you die, which causes client to do that (happens on vanilla), so maybe replacing death with teleport, clear health inventory would work?

maybe it will work like that, just known the plugin will not have generating world screen as well

**Comment by SunshroomChan** [comment]
> I would guess this is because you die, which causes client to do that (happens on vanilla), so maybe replacing death with teleport, clear health inventory would work?

Can you define where the code is, i think i can code it myself

**Comment by SunshroomChan** [comment]
> I would guess this is because you die, which causes client to do that (happens on vanilla), so maybe replacing death with teleport, clear health inventory would work?

Another thing i found out that it is when i do /kill (player) on Lobby it generating loading screen same

**Comment by BlueTree242** [comment]
That means im right

**Comment by SunshroomChan** [comment]
> That means im right

i will closed this issue due to on Spigor 1.12.2 when you died anyware it will generating that and on 1.16.5 the plugin no more that issue anymore
