### ISSUE TITLE
Spanish error

### ISSUE THREAD

**Issue by craciu25yt** [andrei1058/BedWars1058#599]
There's a error in the Spanish language. In the armours, at the end says "ellas" but in that case its "ellos" (In all the armors, chainmail, iron and diamond)

**Comment by Xxyuri2005xX** [comment]
You can easily fix by editing the file

**Comment by andrei1058** [comment]
Will be fixed in the next update!
Notice that you'll have to manually correct them or delete the entire file to generate the updated one.

**Comment by tomkeuper** [comment]
closed as implemented
