### ISSUE TITLE
Player Health Under Name

### ISSUE THREAD

**Issue by SoheylRF** [andrei1058/BedWars1058#601]
**Is your feature request related to a problem? Please describe.**
It would be better if the Health thing under the name were not be show.

**Describe the solution you'd like**
so it can be better just showing the health symbol instead of me seeing a green text

![image](https://user-images.githubusercontent.com/113312862/191097315-9b40e086-07ff-44d4-bc53-8c6c036f9cf8.png)

**Comment by Xxyuri2005xX** [comment]
Language file you can fix
