### ISSUE TITLE
Sword with durability

### ISSUE THREAD

**Issue by ezVelar** [andrei1058/BedWars1058#603]
Hi, the sword in the shop in Iron, gold and diamond are with durability
i try to set "permanent" the item in shop.yml but whe i death the sword remain in my inventory and the most of player doesn't want this
please can fix this? thank you very much!

Server version: Spigot 1.8.8
Client version: 1.8.9
OS: Ubuntu 20.04
Plugin version: 22.7

**Comment by porudev** [comment]
+1

**Comment by tomkeuper** [comment]
Duplicate of #245 
Will be fixed in new release
