### ISSUE TITLE
Stats system update!

### ISSUE THREAD

**Issue by ezVelar** [andrei1058/BedWars1058#604]
Hi !, I wanted to ask you to add a very requested feature that is to be able to see the stats of other players with the command /stats <playername> would be a very convenient thing and then to add a command like bw stats reset <playername> to reset again the stats of a player would it be possible to add it?, thank you very much

**Comment by tomkeuper** [comment]
I dont see this as a much requested feature. You can already change/reset player stats when using an external database.
