### ISSUE TITLE
add team color in teleporter bw

### ISSUE THREAD

**Issue by ezVelar** [andrei1058/BedWars1058#605]
Hi !, I wanted to ask if it was possible to add the fact of being able to see the color of the player from which to go in the bw spectator teleporter gui!
for example:
if velar is on the blue team

automatically its name will be blue

p.s I have already tried to put the placeholder in front of the teamcolor, but it doesn't work

Thank you very much!

**Comment by wizzoh** [comment]
+1

**Comment by tomkeuper** [comment]
I am not quite sure what you mean, can you provide a screenshot?

**Comment by andrei1058** [comment]
@tomkeuper there's a teleporter GUI while spectating with alive players. Items  are player heads with their names but without colors. We could add a team color placeholder for that.

**Comment by ezVelar** [comment]
> @tomkeuperc'è una GUI di teletrasporto mentre assisti a giocatori vivi. Gli oggetti sono teste di giocatori con i loro nomi ma senza colori. Potremmo aggiungere un segnaposto del colore della squadra per questo.

Exactly i mean this
