### ISSUE TITLE
Regenerate Beds if Unintentionally Broken

### ISSUE THREAD

**Issue by CoderQCYT** [andrei1058/BedWars1058#606]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I'm always frustrated when a plugin or an addon accidentally sets the block of where the bed is to air, and the bed is gone. The bed is still there for the plugin, so the team is unbeatable.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
I'd the plugin to check if the bed block isn't there, and if the bed wasn't destroyed by a player, automatically replace the bed blocks.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
I've tried editing plugins that have these issues, but since they usually depend on Bedwars1058, it creates a lot of errors. I cannot contact the person who made the Bedwars PopupTowers Plugin as I cannot review it on Spigot.

**Additional context**
_Add any other context or screenshots about the feature request here._
A screenshot of what currently happens using /setblock
![image](https://user-images.githubusercontent.com/73763394/192654494-2870e9e5-ba19-4339-9f0e-c866c7287aeb.png)

**Comment by CoderQCYT** [comment]
whoops i chose the wrong template i guess it works here too.

**Comment by andrei1058** [comment]
I don't see an optimal way of doing this to prevent it from happening. Addons must check where they are placing or removing blocks..

**Comment by tomkeuper** [comment]
I agree, Its the responsibility of the addon to check if blocks/entities can be broken or not.
