### ISSUE TITLE
Mysql don't get connect

### ISSUE THREAD

**Issue by FrancyPro** [andrei1058/BedWars1058#611]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 

**Additional context**

**Comment by FrancyPro** [comment]
hi, i have a problem with bw1058's mysql.  In a nutshell I use bwproxy and bw1058 for bungee support but when I connect it to my db it gives me error compared to other plugins.  i use ubuntu 20.04 and i use the latest version of mysql.  how to solve?

**Comment by FrancyPro** [comment]
The versione of bw1058 is 22.3.4 with pandaspigot 1.8.

Lobby: sportpaper with last version of bwproxy

**Comment by tomkeuper** [comment]
Use the discord server https://discord.gg/Zk6sDk9T

**Comment by tomkeuper** [comment]
This issue can be closed

**Comment by andrei1058** [comment]
> This issue can be closed

how did you fix it?

**Comment by tomkeuper** [comment]
Magic fix im guessing.
