### ISSUE TITLE
[BUG] Can't pick items

### ISSUE THREAD

**Issue by craciu25yt** [andrei1058/BedWars1058#619]
**Describe the bug**
sometimes, when a game starts you can't pick any item. It happens in a past but I was thinking it was fixed

**To Reproduce**
Start a game
Try to pick items

**Expected behavior**
just pick them

**System (please complete the following information):**
 - OS: Windows
 - Server software Flamepaper
 - Server Version 1.8.8
 - Plugin Version 22.7

**Comment by tomkeuper** [comment]
Try the latest version. And provide server log etc

**Comment by tomkeuper** [comment]
Closed due to inactivity
