### ISSUE TITLE
[Bug] Team balancer not working

### ISSUE THREAD

**Issue by craciu25yt** [andrei1058/BedWars1058#622]
**Describe the bug**
I started a 3v3v3v3 with a player and we are in the same team

**To Reproduce**
join to a game
wait the time (or in that case I used /bw start, but the countdown already started)

**Expected behavior**
to be in different teams

**Screenshots**
![image](https://user-images.githubusercontent.com/48807342/208246577-f74f20bd-a887-42b4-97ed-65d50a349eb3.png)

**System (please complete the following information):**
- OS: Windows
- Server software Flamepaper
- Server Version 1.8.8
- Plugin Version 22.7

**Comment by HeamTag** [comment]
+1

**Comment by EvilG-MC** [comment]
+1

**Comment by porudev** [comment]
+1

**Comment by tomkeuper** [comment]
Can you try the latest version and let us know if this issue still persists?

**Comment by tomkeuper** [comment]
Duplicate of #179
