### ISSUE TITLE
[Bug] Support Advance SlimeWorldManager error

### ISSUE THREAD

**Issue by HeamTag** [andrei1058/BedWars1058#624]
Hey i found an issues when i install advanced slimeworldmanager, and when i start a server - bw1058 is not working bw gives error: 
(https://user-images.githubusercontent.com/98354429/209342812-d0058a6f-b9af-4c12-b599-119adcdd966a.png)
pls fix it

**Comment by JT122406** [comment]
Yes Known issue due to changes in modern versions of aswm where they moved a dependency out of the plugin I have been looking into fixes

**Comment by andrei1058** [comment]
I wouldn't say it's a bug. We do not support aswm yet and that's all.

**Comment by andrei1058** [comment]
dependency added
