### ISSUE TITLE
Fast iron maps

### ISSUE THREAD

**Issue by RylanPro** [andrei1058/BedWars1058#627]
Hey i was wondering if there was any way to make fast iron maps i tried editing the generator speed for each map but it dosent seem to work the best 

i hope this can be added in an update

**Comment by tomkeuper** [comment]
This is only possible with BUNGEE mode and using a seperate server. Generator settings are server specific and cannot be changed per map.
You could create a seperate server for fast iron maps etc and access them thru the bw proxy plugin
