### ISSUE TITLE
Change the default bed item

### ISSUE THREAD

**Issue by Arqsz** [andrei1058/BedWars1058#635]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to change the default bed item to another item in the config

**Describe alternatives you've considered**
None

**Additional context**
N/a

**Comment by andrei1058** [comment]
We used to have that a few years ago but it didn't seem a good idea. What are you going to replace it with? Also "bed" is mentioned in announcements, stats and other messages.

**Comment by Arqsz** [comment]
User replaced this plugin with another. Issue not relevant anymore
