### ISSUE TITLE
22.9 Join Arena Bug(Went DoWn)

### ISSUE THREAD

**Issue by huazhuchi** [andrei1058/BedWars1058#637]
lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

1.Bungee Mode 2 PayerJoin Arena 
2.Paper1.8.8
3.Player Will Went DoWn

**Comment by tomkeuper** [comment]
Not enough information.

**Comment by huazhuchi** [comment]
> 

add info

> 信息不足。



> 信息不足。

**Comment by huazhuchi** [comment]
> 信息不足。

Add

**Comment by JT122406** [comment]
Update to latest version and see if issue still exists
