### ISSUE TITLE
only one person can enter the map

### ISSUE THREAD

**Issue by escalde** [andrei1058/BedWars1058#64]
After configuring the arena correctly, putting the beds etc, I try to enter the map with a friend and it does not teleport him to the bedwars map lobby and I try to give the / bedwars command
force start and I get an error

 - OS: Windows
 - Server software paper
 - Server Version 1.17.1
 - Plugin Version bedwars-plugin-21.10.1-SNAPSHOT
 - SHARED plugin option

**Comment by ajgeiss0702** [comment]
What is the error you get? Is the max players for the arena correct? What does your friend get when he tries to join?

**Comment by ajgeiss0702** [comment]
Closing because of no response
