### ISSUE TITLE
Map gets completely wiped after game

### ISSUE THREAD

**Issue by Dominik159E0** [andrei1058/BedWars1058#652]
**Describe the bug**
After the game the map disapears into void

**To Reproduce**
1. start a game
2. end it
3. map gets wiped

**Expected behavior**
Refresh the map

**Screenshots**
![obrázok](https://user-images.githubusercontent.com/90928810/215340278-e6939671-9c91-4bb1-a221-8c2f54591b4d.png)

**System (please complete the following information):**
 - OS: <Windows 10>
 - Server software purpur
 - Server Version 1.18.2
 - Plugin Version 23.1.1

**Additional context**

**Comment by 1RLGS** [comment]
I have the same issue, but on 1.19.3

**Comment by andrei1058** [comment]
A full server log would be more usefull

**Comment by tomkeuper** [comment]
Also multiverse is not supported.

**Comment by 1RLGS** [comment]
> Also multiverse is not supported.

Despite if multiverse is installed or not, the issue still occurs

**Comment by tomkeuper** [comment]
Still waiting on full log, I cannot replicate this issue myself

**Comment by Dominik159E0** [comment]
[latest.log](https://github.com/andrei1058/BedWars1058/files/10715676/latest.log)

Sorry for the delay, i didn’t check my mail.

**Comment by tomkeuper** [comment]
For the sake of making it as clean as possible, are you able to make sure multiverse is completely removed and then provide the log? Because eventhough you can say it still happen without multiverse I would like to see it myself.

Not trying to be painfull just want to rule out any other possibilties

**Comment by tomkeuper** [comment]
bump

**Comment by tomkeuper** [comment]
Issue is stale, closing
 It might be a corrupted map
