### ISSUE TITLE
Bedwars1058 make carsh my server 

### ISSUE THREAD

**Issue by LanassPresh** [andrei1058/BedWars1058#653]
So, when i put the plugins in my server, and i start my server, he crash and say that the java version inst valid, but if i delete the plugins he instantly work.
For info : (i tried to delete other plugins and don't work) Heberger : Falixnodes

**To Reproduce**
1. Start server w/ the plugin
2. Wait for the crash
3. See error
-->

**Expected behavior**
Start without crashing 

**Screenshots**
![log-error](https://user-images.githubusercontent.com/124085848/215867412-7902f376-939d-4bf1-a36c-e39b43070722.PNG)
![Javaver-error](https://user-images.githubusercontent.com/124085848/215867376-7a40b044-4290-4ecf-9938-034606b80dc6.PNG)

**System (please complete the following information):**
 - OS: Windows 10
 - Server software spigot
 - Server Version 1.8.8
 - Plugin Version 23.1.1

**Additional context**

**Comment by tomkeuper** [comment]
Are you on the latest version of spigot? Otherwise you should try to use a server jar compiled with java 11

**Comment by andrei1058** [comment]
I see you have BedWarsRel and Multiverse as well. What are you trying to do here?

**Comment by tomkeuper** [comment]
BTW I see you put the OS as windows but pterodactyl doesnt run on windows only Linux. 
I just tested the latest release on a 1.8.8 server and it works for me. Make sure you have Java 11 selected and you could try to set use-native-transport: false in server.properties if it doesnt work.
