### ISSUE TITLE
{wins} Placeholder in bedwars lobby not working

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#658]
**Describe the bug**

**To Reproduce**
1. Install bedwars1058 23.2 with the default config.
2. Go to the server and look at the scoreboard.
3. Look at the Total Wins and see {wins}

**Expected behavior**

Expected the {wins} placeholder to parse to show my number of wins.
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216912751-6f5d3a58-34f1-4345-a842-37d744675185.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur
 - Server Version: 1.19.3 
 - Plugin Version: 23.2 

**Additional context**

**Comment by tomkeuper** [comment]
Will be fixed in the next release. Thanks for reporting!
