### ISSUE TITLE
Scoreboard animations not working

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#660]
**Describe the bug**

Scoreboard animations not working using the default config
**To Reproduce**
1. Install bedwars1058 23.2 with the default config.
2. Go to the server and look at the scoreboard.
3. Look at the top of the scoreboard and see the BedWars,BedWars,BedWars,BedWars,

**Expected behavior**

Expected the BedWars on the scoreboard to animate like in bedwars 22.7.
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216917735-dcfbc0a0-36f6-47c0-93e7-4eac12a7a529.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur 
 - Server Version: 1.19.3 
 - Plugin Version: 23.2 

**Additional context**

**Comment by tomkeuper** [comment]
Will be fixed in the next release. Thanks for reporting!
