### ISSUE TITLE
In-game arena Scoreboard lines in the wrong spot

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#662]
**Describe the bug**

In-game arena scoreboard lines in the wrong spot. Default lang file, the IP address is on line 3, the events and timer is on line 14.
**To Reproduce**
1. Install bedwars1058 23.2 with the default config.
2. Go to the server and join arena
3. Start arena and look at the scoreboard

**Expected behavior**

Expected the scoreboard to show correctly whats in the language file.
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216920842-5c0ea843-7346-405e-bb1d-80f9f2920716.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur 
 - Server Version: 1.19.3 
 - Plugin Version: 23.2 

**Additional context**

Edit: tested with Multiarena mode and it seems to happen to the waiting lobby too when coming from the bedwars lobby.

**Comment by 1RLGS** [comment]
Have the same problem

**Comment by tomkeuper** [comment]
I have not been able to replicate this issue. can you give some more info? and maybe provide a full server log?

**Comment by cjtganzon** [comment]
I used bungeecord but it's still there without it. I don't know what other info I can give.
I attached my log.
[latest.log](https://github.com/andrei1058/BedWars1058/files/10714934/latest.log)

**Comment by tomkeuper** [comment]
Can you attach config and language file used, and maybe try on a clean server? (only bw)
dont forget to remove sensitive info from config

**Comment by joohnaquino** [comment]
This could be caused by your lang file, check if the scoreboard lines have '
like in this example:
![image](https://user-images.githubusercontent.com/120399502/219740593-54c67976-6bc7-4c0d-a651-279829d0ee75.png)

**Comment by andrei1058** [comment]
You're not using the latest version

**Comment by cjtganzon** [comment]
I am using the latest version (23.2). I created this issue on a clean server with regenerated config and language files.
[config.txt](https://github.com/andrei1058/BedWars1058/files/10771532/config.txt)
[messages_en.txt](https://github.com/andrei1058/BedWars1058/files/10771533/messages_en.txt)

**Comment by tomkeuper** [comment]
Try use this version
https://discord.com/channels/201345265821679617/1074361958876315698/1076238139397521418

**Comment by andrei1058** [comment]
Where did you get v23.2 from? this issue used to happen in early builds

**Comment by cjtganzon** [comment]
I have both of them from spigot and poly and tested them both. I also tested with the latest beta build, but no luck.

**Comment by tomkeuper** [comment]
I just tested it with only bedwars and can confirm this issue. It only seems to happen on 1.19 servers and when you join the scoreboard is fine, the lines increment correctly but as soon as the scoreboard changes all lines get value 0 causing the scoreboard to loose format during countdown and also in game
