### ISSUE TITLE
Add ability to auto-equip elytra

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#663]
**Is your feature request related to a problem? Please describe.**
I can add the elytra to the armor shop with auto-equip enabled, but it does not auto-equip and shows up in my inventory when bought.

**Describe the solution you'd like**
When buying the Elytra, I would like for it to replace the equipped chestplate.

**Describe alternatives you've considered**
There is no alternative

**Additional context**
Probably a bug for the elytra, but I assume that it wasn't planned so I put this as a feature request.

**Comment by andrei1058** [comment]
This was not implemented at all. We still need to add support for elytra and that's because we've been always focused on 1.8.8 and not took in consideration mc newer features. I think @tomkeuper is working on it

**Comment by tomkeuper** [comment]
wasnt planning on but its an easy feature. Its added now. Should be in the next release

**Comment by andrei1058** [comment]
This was implemented
