### ISSUE TITLE
Upgrades placeholders & lore messages are incorrect (or works not as it expected to)

### ISSUE THREAD

**Issue by VladOliinyk** [andrei1058/BedWars1058#668]
**Describe the bug**

In a localisation file (f.e. `messages_en.yml`) the `upgrades-upgrade-lore-forge-tier-1` placeholders are set in the incorrect places, AND the placeholders logic there is not quite perfect.

First of all, the `{cost}` and `{currency}` placeholders should be on the level of the tier that you are buying.
`upgrades-upgrade-lore-forge-tier-1` - correct
`upgrades-upgrade-lore-forge-tier-` 2nd, 3rd and 4th - incorrect

But the main thing: the cost of upgrades is hardcoded right now. 

_Mr. Ceasar once said:_
> Maybe I can try and make it all sync from the config with some new placeholders like: {tier_1_color}, {tier_1_cost}, {tier_1_currency} making it easier to update new prices and also automatically sync them across different languages
> Because it looks like that with the current method you would have to change each and every language file if a price is changed.

*in [discord](https://discord.com/channels/201345265821679617/348088106546757653/1074358340970365008)

**Screenshots**
https://cdn.discordapp.com/attachments/348088106546757653/1074349862302265465/image.png

**Plugin version:** v23.1.1

**Comment by joohnaquino** [comment]
I had this problem initially, but I don't really remember if it was the price, or the fact that it shows the wrong level, or like, I buy the last upgrade, and there's still one more in there (being that there are only 4)

A solution I did for this was to turn the level 1 into 0, 2 into 1, 3 into 2, and 4 into 3, but only in the lang, I also removed the {cost} leaving only the value there. It can be a bit of work if you intend to use multi langs

**Comment by andrei1058** [comment]
@tomkeuper is working on it

**Comment by tomkeuper** [comment]
Closed as implented
