### ISSUE TITLE
Players can collect drop while waiting respawn after death

### ISSUE THREAD

**Issue by VladOliinyk** [andrei1058/BedWars1058#669]
**Describe the bug**
After a player dies, he becomes in ~spectator mode and flies for a few seconds while waiting for respawn.
And if during this time the player flies up to a resource spawner (emeralds or diamonds) ((or any other drop that might be on the ground)), the player can pick it up BEFORE respawning. 

It feels like when respawning the player FIRSTLY becomes "a player" (from ~spectator mode to survival mode), and then teleports to his spawn. And just between the time when the player is "alive" and before he is teleported to his spawn - he picks up that drop. 
Video: https://youtu.be/8N__Jl4EcBI

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure the emeralds or diamond has drop, (or there are any other drop near the spectator-spawn point)
2. Make sure your bed are not destroyed (obviously)  
3. Die (as a player)
4. While respawn-counter, fly as fast as possible to the drop on a ground
5. Wait for respawn and you'll respawn with items picked up. 

**Expected behaviour**
The player who is waiting for respawn in spectator mode can not pick up drop while respawning :) 

I guess it could be solved just by changing the order of the events: 
- first: tp player to his spawn point,
- second: change player mode from spectator to survival

**Screenshots**
Video: https://youtu.be/8N__Jl4EcBI

**System (please complete the following information):**
Plugin version: `23.1.1`
`serverType: SHARED`
Waterfall and pufferfish backends (not sure its versions matter.

**Comment by tomkeuper** [comment]
I put the code that removes the respawnSession protections (eg. picking up items) inside a short delay making sure that the protection gets removed after the player has been teleported, as this is done async.

**Comment by VladOliinyk** [comment]
Yep! Сan confirm, fixed!  (in the snapshot you sent)
waiting for the release <3
Thanks
