### ISSUE TITLE
[SUGGESTION] Some suggestions and/or implementations that could be added

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#672]
Giving you some suggestions:

> - Add the "emerald/upgrade" in the generators.yml so that you can edit the emerald generator of the player's island, also add the upgrade levels for "iron", "gold" and "emerald/upgrade" (as this is causing an very fast drop and an excessive accumulation of items, in this case the "delay:" would be per thousandth)

> - Allow us to edit the order and the minutes of the "next event-diamond/emerald (dragon and end)" of the arena (I say that globally and not by arena), because apparently it raises the level 2 and then the 3, first for the diamonds and then emeralds

> - Add PAPI support to make it possible to use in langs (currently only in bw1058's own chat)

> - Add placeholders "%bw1058_arena_status_[arenaName]%, %bw1058_arena_count_[arenaName]%" as well as "bw reload" for langs to BWProxy

> - Fix the bwproxy "problem" that causes any new player to have a null level instead of 0 or 1

**Comment by joohnaquino** [comment]
I also think it would be interesting if you could customize the store, I mean the categories and ~quick-buy items~ (the quick-buy/nether-star)*. I think it would be creative if you could place them at the bottom, or on the sides. Of course, on the sides it would be something that would require the reduction of categories in shop.yml

**Comment by tomkeuper** [comment]
> * Add the "emerald/upgrade" in the generators.yml so that you can edit the emerald generator of the player's island, also add the upgrade levels for "iron", "gold" and "emerald/upgrade" (as this is causing an very fast drop and an excessive accumulation of items, in this case the "delay:" would be per thousandth)

Im not really sure what you mean, spwan times are already customizable and also what items drop at each tier. Im also not sure what you mean with the delay? a delay per thousandth would be a bit overkill and possibly cause excessive lag.

 > * Allow us to edit the order and the minutes of the "next event-diamond/emerald (dragon and end)" of the arena (I say that globally and not by arena), because apparently it raises the level 2 and then the 3, first for the diamonds and then emeralds

The order of generators is already customizable, in the generator config you can change the start time in seconds meaning start: 300 would cause an event to be trigger 300 seconds after the game has started. In the default config it would mean that diamond tier II would be activated after 360 seconds and tier II emeralds 720 seconds after the game has started. For more info read: [generator configuration](https://wiki.andrei1058.dev/docs/BedWars1058/configuration/generators-configuration).

 > * Add placeholders "%bw1058_arena_status_[arenaName]%, %bw1058_arena_count_[arenaName]%" as well as "bw reload" for langs to BWProxy

Its better to report this in the BWProxy github page: [BWProxy](https://github.com/andrei1058/BedWarsProxy). Yes its less active than here but once the plugin is stable bwproxt will also be looked at.

**Comment by joohnaquino** [comment]
> Im not really sure what you mean, spwan times are already customizable and also what items drop at each tier. Im also not sure what you mean with the delay? a delay per thousandth would be a bit overkill and possibly cause excessive lag.

I referred to generators.yml as player island generators, but apparently it's in upgrades2.yml, I mentioned this because it generated an absurd amount of items (much more than the default)

**Comment by tomkeuper** [comment]
Aren't there more issues that needed to be fixed?
