### ISSUE TITLE
Tab in game

### ISSUE THREAD

**Issue by A1exey1337** [andrei1058/BedWars1058#673]
1. Group the players together based on color (or alphabetically)

R player
R player
B player
B player

2. And add tab kills final kills beds breaks to display

I apologize if the machine translation I used was inaccurate 
thank you :)

**Comment by tomkeuper** [comment]
All good, I changed it a little to make it a bit clearer.

I am not sure if 2. is already possible or not. But we could try to add placeholder support. But I am quite sure this will not be in the standard config so you would have to add it yourself.

**Comment by joohnaquino** [comment]
I don't know if I understood very well.
Do you want player stats during gameplay? like hypixel that shows how many kills, final kills and broken beds?

**Comment by A1exey1337** [comment]
> I don't know if I understood very well. Do you want player stats during gameplay? like hypixel that shows how many kills, final kills and broken beds?

ye ye ye That's it like hypixel I also need to line up the players on each team

**Comment by joohnaquino** [comment]
> > I don't know if I understood very well. Do you want player stats during gameplay? like hypixel that shows how many kills, final kills and broken beds?
> 
> ye ye ye That's it like hypixel I also need to line up the players on each team

Oh, that's pretty simple to do.
There is an extension called [BW1058Plus](https://api.extendedclip.com/expansions/bw1058plus/) you just need to use it in the TAB, I don't know if the TAB of the bw1058 supports PAPI, but it's good that you do the test

**Comment by A1exey1337** [comment]
OK i will try

**Comment by tomkeuper** [comment]
No the build in scoreboard does not support PAPI. Not as of now atleast

**Comment by A1exey1337** [comment]
I know So I wrote it in the tab plugin

**Comment by actuallySoheil** [comment]
I believe, he means tab sort system which sorts players in tab list for each individual player based on their color on team.

**Comment by actuallySoheil** [comment]
there is an addon for this thing, but it would be great that we have this built-in.

https://www.spigotmc.org/resources/bedwars1058-tabsorter.100842/ 

https://proxy.spigotmc.org/383d510e3dd2616d3c52571dd42c7fb77155770b?url=https%3A%2F%2Fi.imgur.com%2FyWBqcrI.png

**Comment by A1exey1337** [comment]
Thank you for your explanation
But this plugin will kick the player out when the game is over
So I had to give it up

**Comment by tomkeuper** [comment]
The kick issue is another issue and already being looked at. 
Can this issue be closed?

**Comment by andrei1058** [comment]
1. Was implemented whit the latest updates.
2. If you're asking for stats placeholders in tab header and footer that could be done

**Comment by A1exey1337** [comment]
> 1. Was implemented whit the latest updates.
> 2. If you're asking for stats placeholders in tab header and footer that could be done

ok thank you

**Comment by andrei1058** [comment]
We're going to keep trak of your request in #713
