### ISSUE TITLE
lobby scoreboard {wins} placeholder is not replaced

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#674]
**Describe the bug**
lobby scoreboard {wins} placeholder is not replaced

**To Reproduce**
Without any process, it just won't be replaced.

**Expected behavior**
X

**Screenshots**
https://imgur.com/a/yw1TOCn

**System (please complete the following information):**
 - OS: 
 - Server software Spigot
 - Server Version 1.8.8
 - Plugin Version 23.2

**Additional context**

**Comment by joohnaquino** [comment]
Change only the **w** to uppercase **"{Wins}"**
If it doesn't work, use PAPI with [these placeholders](https://wiki.andrei1058.dev/docs/BedWars1058/hooks/papi-hook)
If it still doesn't work, use a scoreboard plugin for this together with PAPI

**Comment by ImYenil** [comment]
Doesn't the lobby scoreboard support PlaceholderAPI?

**Comment by joohnaquino** [comment]
> Doesn't the lobby scoreboard support PlaceholderAPI?

I have no idea, that's why I don't use it

**Comment by tomkeuper** [comment]
duplicate of #658
Fixed in next release or download beta (available in discord)
