### ISSUE TITLE
[Bug] When purchasing a sword or bow in the shop, the item is not tagged as unbreakable

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#675]
**Describe the bug**
When purchasing a sword or bow in the shop, the item is not tagged as unbreakable

**To Reproduce**
X

**Expected behavior**
X

**Screenshots**
X

**System (please complete the following information):**
 - OS:  Windows
 - Server software  spigot
 - Server Version  1.8.8
 - Plugin Version   23.2

**Additional context**
 X

**Comment by tomkeuper** [comment]
Duplicate of #245
