### ISSUE TITLE
Server crashed after picking up more than 1 ore from the emerald or diamond generator

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#679]
**Describe the bug**
Yesterday I edited the ["generators.yml"](https://pastebin.com/KLGpVGLH) and ["upgrades2.yml"(just the generators)](https://pastebin.com/PJA7VNBr), and everything was ok after being edited, but today I came across this strange problem. I didn't edit anything else besides that

**To Reproduce**
Honestly, I don't even know what's causing this.

**Expected behavior**
I believe normally? or was it supposed to work the way it was edited

**Screenshots**
I couldn't upload the video directly on github, [I had to post it on youtube](https://youtu.be/h2N3jSaLLeg)

**System (please complete the following information):**
 - OS: windows10
 - Server software paperspigot-445
 - Server Version 1.8.8
 - Plugin Version 23.2

**Comment by tomkeuper** [comment]
No server log, no plugin list no timings. Havent seen this issue happen before to anyone so im quite sure its a different plugin causing issues.

**Comment by joohnaquino** [comment]
> No server log, no plugin list no timings. Havent seen this issue happen before to anyone so im quite sure its a different plugin causing issues.

Server log, bw1058 debug mode is active. No need to send another for the plugins as they all show up in the server log

[latest.log](https://github.com/andrei1058/BedWars1058/files/10772671/latest.log)

**Comment by tomkeuper** [comment]
I looked at the logs you sent and... im not sure what is is but you have sooooo many debug messages which arent bedwars1058 messages but they are from the arena maps. So you should either disable those first or figure out where they are comming from.

printing ~1000 lines within a seconds is not good.

Maybe you should also look at your timings and see whats causing the tps to drop. You should always start with eliminating plugins to see whats causing issues

**Comment by joohnaquino** [comment]
This issue is being caused by an addon called ["Bedwars1058 Cosmetics"](https://www.spigotmc.org/resources/bedwars1058-cosmetics.106685/)
And this was not happening until your version "1.2/1.2-HOTFIX"
I reported this issue on their Discord and hope they fix it.

I'm also having a "problem" with the generators, simply the "spawn-limit: <number>" is not being respected by bw1058, so it limits to 4 in diamond generators, and 3 in emerald generators (all levels ) and I set "spawn-limit: 2" on level 1 and 2, and "spawn-limit: 4" on level 3 for diamond and emerald spawners, and he still doesn't change

**Comment by joohnaquino** [comment]
@tomkeuper you said about generating a lot of lines over the maps, well, I don't know why, it only happens when debug mode is active and it only shows all that in the log file

**Comment by tomkeuper** [comment]
> I'm also having a "problem" with the generators, simply the "spawn-limit: " is not being respected by bw1058, so it limits to 4 in diamond generators, and 3 in emerald generators (all levels ) and I set "spawn-limit: 2" on level 1 and 2, and "spawn-limit: 4" on level 3 for diamond and emerald spawners, and he still doesn't change

Could you open a seperate issue about that? as its unrelated to the original subject.

**Comment by tomkeuper** [comment]
> > I'm also having a "problem" with the generators, simply the "spawn-limit: " is not being respected by bw1058, so it limits to 4 in diamond generators, and 3 in emerald generators (all levels ) and I set "spawn-limit: 2" on level 1 and 2, and "spawn-limit: 4" on level 3 for diamond and emerald spawners, and he still doesn't change
> 
> Could you open a seperate issue about that? as its unrelated to the original subject.

Possible duplicate of #198
