### ISSUE TITLE
[bug] Consumable items (and resources) can be used infinitely when in offhand

### ISSUE THREAD

**Issue by TrianglyRU** [andrei1058/BedWars1058#68]
**Description**
Items that are consumable (like fireball, milk bucket, spawn egg and even **ingots**, **emeralds** and **diamonds**) can be used infinitely when in offhand. It doesn't happen with bridge egg, however.

**Steps to reproduce**
Take the item(-s) in offhand, then just use it. Once there is one item left in offhand, It won't be consumed. If it is a resource like gold ingot and it equals to price of an item you plan to buy, you can buy it infinitely as well.

**Videos**
https://user-images.githubusercontent.com/45323263/140946481-9278a30b-6057-4a16-b171-02d05c019a66.mp4
https://user-images.githubusercontent.com/45323263/140946831-a5585694-700a-4e07-bd8a-34ebad72fb09.mp4

**Expected behavior**
Well, it should behave like in the primary hand?

**System**
- OS: Ubuntu
- Server software: Paper
- Server Version 1.12.2
- Plugin Version 21.11

**Comment by minhh2792** [comment]
I have the same issue here and have to temporary disable off hand
