### ISSUE TITLE
Player Health Under Name In Lobby

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#681]
**Describe the bug**
When a player joins the server, I can see player health under their nametag in the lobby.

**To Reproduce**
1. Go to server
2. Come closer to NPCs
3. See player health under name in lobby

**Expected behavior**
I'm not sure if this is a feature or not, however, it would make more sense if we don't have that in the lobby.

**Screenshots**
![image](https://user-images.githubusercontent.com/124730657/220077887-484e24eb-c867-4c39-af61-8b94398b6963.png)
![image](https://user-images.githubusercontent.com/124730657/220077955-e026d680-1dee-4f38-b305-ed0e482602ba.png)

**System (please complete the following information):**
 - OS: Windows
 - Server software: NachoSpigot
 - Server Version: 1.8.8
 - Plugin Version: v23.2

**Additional context**
If this is a feature in the lobby, please make a configuration option to disable this.

**Comment by tomkeuper** [comment]
Server log?

**Comment by Chalityst** [comment]
Go to Citizens config and try to set always-use-name-holograms from False to True

**Comment by tomkeuper** [comment]
Is this problem solved? @iWixii

**Comment by andrei1058** [comment]
> Go to Citizens config and try to set always-use-name-holograms from False to True

I'm not sure if that was the fix, but I l've seen this issue before when I had a server and I know for sure it's not from bedwars. It's something interfering with the sidebar. Could be TAB plugin as well.

**Comment by andrei1058** [comment]
We should add this to FAQ if we have one on the wiki

**Comment by Chalityst** [comment]
> > Go to Citizens config and try to set always-use-name-holograms from False to True
> 
> I'm not sure if that was the fix, but I l've seen this issue before when I had a server and I know for sure it's not from bedwars. It's something interfering with the sidebar. Could be TAB plugin as well.

Yep, I think it's will fix but i still have problem with bedwars1058 npc if i set False to True as i mentioned. All join npc will be remove after restart server.

**Comment by tomkeuper** [comment]
But citizens being removed after a server restart sounds like a citizens issue. I assume you are not adding them to an arena world atleast.

**Comment by tomkeuper** [comment]
@andrei1058 Since you added the bug tag, is this actually an issue? or does it just need to get added to the FAQ?

**Comment by actuallySoheil** [comment]
> > Go to Citizens config and try to set always-use-name-holograms from False to True
> 
> I'm not sure if that was the fix, but I l've seen this issue before when I had a server and I know for sure it's not from bedwars. It's something interfering with the sidebar. Could be TAB plugin as well.

I've tested with only two plugins; Citizens and BedWars1058 and still had this issue.

This bug has known since the new sidebar thing has released so I don't think that would be other plugins.
