### ISSUE TITLE
Sword disappear when you try to pick ut up

### ISSUE THREAD

**Issue by WitheredWinter** [andrei1058/BedWars1058#686]
**Describe the bug**

Sword disappear when you try to pick ut up.

**To Reproduce**

IF YOU DON'T UNDERSTAND MY DESCRIPTION,WATCH THE VIDEOS IN **Screenshots**

When there is a sword(except wooden sword) in your inv or hotbar and you try to pick up another sword on th ground,the one you try to pick up will disappear.
When there is a wooden sword in your inv or hotbar,drop another sword and click the wooden one and "hold the wooden one with your mouse pointer",then try to pick up the one you have dropped,you will find the drooped one disappear.

IF YOU DON'T UNDERSTAND MY DESCRIPTION,WATCH THE VIDEOS IN **Screenshots**

**Expected behavior**

**Screenshots**

VIDEOS(Don't forget to set it to 1080p)
except wooden sword:  [Click here](https://4gsknv-my.sharepoint.com/:v:/g/personal/owner_winarc_cn/ESsXEnzX_zlIgcF8Prs15D0BrQNaxSubPtJOizV1s3q-Ag?e=748gYw)
wooden sword: [Click here](https://4gsknv-my.sharepoint.com/:v:/g/personal/owner_winarc_cn/EQghpKiWAwtArUQMTYARPYYBRbWVUQ1zA5ZVuinLEWMweg?e=mmrBDs)

**System (please complete the following information):**
 - OS: Windows10
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version 23.2.1 BETA2

**Additional context**

**Comment by tomkeuper** [comment]
Will be fixed in the new release.

I removed the check if the damage of a picked up sword is higher or equal to the sword you have currently.
