### ISSUE TITLE
Invisibile player nametag visible after drinking potion on 1.8

### ISSUE THREAD

**Issue by tomkeuper** [andrei1058/BedWars1058#688]
**Describe the bug**
When running a 1.8.8 server 1.8.x clients can see the nametag of an invisible player

**To Reproduce**
1. Drink an invisbility potion
2. look at invisible player from 1.8 client

**Expected behavior**
Nametag doenst show on all clients

**Screenshots**
https://prnt.sc/nEBt_FVR0wzG

**System (please complete the following information):**
 - OS: Linux
 - Server software Paperspigot
 - Server Version 1.8.8
 - Plugin Version 23.2.1-BETA2

**Comment by andrei1058** [comment]
Minecraft ducks 🦆 🦆 🦆

**Comment by tomkeuper** [comment]
> Minecraft ducks 🦆 🦆 🦆

I ducking know 🦆

**Comment by tomkeuper** [comment]
Could it be related to: https://github.com/andrei1058/BedWars1058/blob/9d2f1adb98bd5cd11c466de3b474e2462d76af1e/bedwars-plugin/src/main/java/com/andrei1058/bedwars/sidebar/BwSidebar.java#L651-L660

As its still //todo

**Comment by tomkeuper** [comment]
hopefully this is fixed in the latest dev build
