### ISSUE TITLE
bedwars scoreboard issue

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
https://imgur.com/a/0K6vVgW
**System (please complete the following information):**
 - OS: 
 - Server software  Paper
 - Server Version  1.8.8
 - Plugin Version  23.2.1

**Additional context**

**Comment by tomkeuper** [comment]
Server log? plugins installed?
Does it always happen? how to reproduce?

**Comment by ImYenil** [comment]
https://pastebin.com/r0xQk0nP Only bedwars1058

**Comment by ImYenil** [comment]
> Server log? plugins installed? Does it always happen? how to reproduce?

and Yes it always happen

**Comment by d4uts** [comment]
Happens to me as well https://i.imgur.com/neVbbEh.png
Server is running 1.8

**Comment by andrei1058** [comment]
What Minecraft client is that? Window name is censured

**Comment by ImYenil** [comment]
> 

Lunar Client , Windows 11

**Comment by Chromaah** [comment]
It happens on all clients. (and even forge)

**Comment by tomkeuper** [comment]
Do you guys use multiarena? 
I just tested it on my local server and it seemed to only happen when using multiarena. and only when the player joins that triggers the game starting phase. 

In this case it sends a waiting scoreboard to the user and immediately after send the starting scoreboard.

I will be looking for a solution tommorow

**Comment by Chromaah** [comment]
yes, I am using multiarena

> In this case it sends a waiting scoreboard to the user and immediately after send the starting scoreboard.

ah i see

**Comment by tomkeuper** [comment]
Will be fixed in the next release

**Comment by ImYenil** [comment]
> Will be fixed in the next release

Thanks
