### ISSUE TITLE
Add NPC Geyser support with Left Click

### ISSUE THREAD

**Issue by Funasitien** [andrei1058/BedWars1058#691]
**Is your feature request related to a problem? Please describe.**
I run BEDWARS1058 in a geyser server and touch screen users must long tap 2 sec for open an npc (shop or upgrades)

**Describe the solution you'd like**
Make that if you punch an npc (left click) it open it

**Describe alternatives you've considered**
Maybe a Geyser extension for the plugin but it may be too complicated

**Additional context**
You can make this feature can be toggle in the config

**Comment by tomkeuper** [comment]
currenlty we dont support Geyser so make sure to put a thumbs up on #37

**Comment by Funasitien** [comment]
In fact, this is the only problem that I found with compatibility with Geyser, the rest of the plugin perfectly work with Geyser

**Comment by andrei1058** [comment]
#37

**Comment by Funasitien** [comment]
I redo the issue message with the issue #861
