### ISSUE TITLE
Error when using SlimeWorldManager

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#693]
**Describe the bug**
When I use SlimeWorldManager, none of my arenas load, however, slime worlds exists and also there is no config error.
Also when I tried to create an arena I got another error which it was similar to this.

**To Reproduce**
1. Console Error on startup

**Expected behavior**
Here is the console error:
```
[Server thread/WARN]: java.io.IOException: No such file or directory
[Server thread/WARN]: at java.io.UnixFileSystem.createFileExclusively(Native Method)
[Server thread/WARN]: at java.io.File.createNewFile(File.java:1023)
[Server thread/WARN]: at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.handleLevelDat(SlimeAdapter.java:400)
[Server thread/WARN]: at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorlds(SlimeAdapter.java:331)
[Server thread/WARN]: at com.andrei1058.bedwars.BedWars.loadArenasAndSigns(BedWars.java:590)
[Server thread/WARN]: at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:336)
```

**System (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Server software: PandaSpigot
 - Server Version: 1.8.8
 - Plugin Version: v23.2.1

**Comment by tomkeuper** [comment]
It looks like Bedwars is trying to enable an arena that doesnt exist anymore. This could be caused by corruption or if you have manually renamed/changed a map. SWM stores the world in a `slime_worlds` folder in the root of the server and it could be that the settings listed in your `BedWars1056/Arenas` folder of bedwars dont match. 

If I were you I would remove or backup the contents of the arena settings, and then remove the map from slime worlds and the arena folder and enter the setup mode again.

**Comment by iWixii** [comment]
> It looks like Bedwars is trying to enable an arena that doesnt exist anymore. This could be caused by corruption or if you have manually renamed/changed a map. SWM stores the world in a `slime_worlds` folder in the root of the server and it could be that the settings listed in your `BedWars1056/Arenas` folder of bedwars dont match.
> 
> If I were you I would remove or backup the contents of the arena settings, and then remove the map from slime worlds and the arena folder and enter the setup mode again.

that's not the case, I've tested on Windows and I haven't had that problem, however, I've copied everything and I touched none of my configs on Ubuntu. same error.

**Comment by actuallySoheil** [comment]
Thank you for your help. my problem has been fixed.
