### ISSUE TITLE
Health Tablist

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#699]
**Is your feature request related to a problem? Please describe.**
My server users are complaining that tablist health is displayed like that.

**Describe the solution you'd like**
make it display health like the picture.
![2023-03-05_20 18 02](https://user-images.githubusercontent.com/85287520/222957527-35bf2f75-da18-4a55-95dc-962aed01c280.png)

**Describe alternatives you've considered**
None

**Additional context**
I have attached a picture above

**Comment by andrei1058** [comment]
I'm not sure what you mean

**Comment by tomkeuper** [comment]
He is talking about the number showing the health of a player instead of the health bar behind someones name. 
We could just add 2 differnt options to show health.

**Comment by tomkeuper** [comment]
> Collaborator


wait no that doesnt make sence, I thougjt it

> He is talking about the number showing the health of a player instead of the health bar behind someones name. We could just add 2 differnt options to show health.

wait no that doesnt make sence, I thought it was something i used as an addon.

**Comment by porudev** [comment]
There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this

**Comment by ImYenil** [comment]
> There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this

Which options?

**Comment by porudev** [comment]
> > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> 
> Which options?

![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)

Close this if this fix your issue

**Comment by ImYenil** [comment]
> > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > 
> > 
> > Which options?
> 
> ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> 
> Close this if this fix your issue

But I want to display the health display like the picture I posted Even if I disale it, it won't show up as yellow numbers

**Comment by porudev** [comment]
> > > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > > 
> > > 
> > > Which options?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> > Close this if this fix your issue
> 
> But I want to display the health display like the picture I posted

have you tried disabling it?

**Comment by ImYenil** [comment]
> > > > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > > > 
> > > > 
> > > > Which options?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> > > Close this if this fix your issue
> > 
> > 
> > But I want to display the health display like the picture I posted
> 
> have you tried disabling it?

yes i tried

**Comment by Squesly** [comment]
> > > > > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > > > > 
> > > > > 
> > > > > Which options?
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> > > > Close this if this fix your issue
> > > 
> > > 
> > > But I want to display the health display like the picture I posted
> > 
> > 
> > have you tried disabling it?
> 
> yes i tried

Yea Its disappear. No health
![image](https://user-images.githubusercontent.com/105538755/223352767-86e8cbf2-19ed-4806-b59c-4445189dbc16.png)

**Comment by ImYenil** [comment]
> > > > > > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > > > > > 
> > > > > > 
> > > > > > Which options?
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> > > > > Close this if this fix your issue
> > > > 
> > > > 
> > > > But I want to display the health display like the picture I posted
> > > 
> > > 
> > > have you tried disabling it?
> > 
> > 
> > yes i tried
> 
> Yea Its disappear. No health ![image](https://user-images.githubusercontent.com/105538755/223352767-86e8cbf2-19ed-4806-b59c-4445189dbc16.png)

But I want to display yellow health numbers like the picture above?

**Comment by Squesly** [comment]
> > > > > > > > There should be an option to disable the 10 Hearts and only display the yellow numbers, please check the config before posting thing like this
> > > > > > > 
> > > > > > > 
> > > > > > > Which options?
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/81072838/223349418-83bf4f99-df54-4dd0-9dc3-3210e33ee8a6.png)
> > > > > > Close this if this fix your issue
> > > > > 
> > > > > 
> > > > > But I want to display the health display like the picture I posted
> > > > 
> > > > 
> > > > have you tried disabling it?
> > > 
> > > 
> > > yes i tried
> > 
> > 
> > Yea Its disappear. No health ![image](https://user-images.githubusercontent.com/105538755/223352767-86e8cbf2-19ed-4806-b59c-4445189dbc16.png)
> 
> But I want to display yellow health numbers like the picture above?

Yea me too.

**Comment by porudev** [comment]
There used to be yellow health numbers, i think it's because of the new SideBarLib

**Comment by tomkeuper** [comment]
So if I understand correctly, you would want an option to switch between the health in numbers and the health bar as it is now?

![image](https://user-images.githubusercontent.com/29728836/223379601-8be72c5e-b6b1-492f-8f24-221f3b00f76a.png)

**Comment by ImYenil** [comment]
> So if I understand correctly, you would want an option to switch between the health in numbers and the health bar as it is now?
> 
> ![image](https://user-images.githubusercontent.com/29728836/223379601-8be72c5e-b6b1-492f-8f24-221f3b00f76a.png)

Yes

**Comment by WitheredWinter** [comment]
Actually,you guys can use TAB plugin to control tablist before Bedwars1058 add the feature.In TAB you can set the yellow num next to name to health,ping or any other placeholders.

**Comment by ImYenil** [comment]
> Actually,you guys can use TAB plugin to control tablist before Bedwars1058 add the feature.In TAB you can set the yellow num next to name to health,ping or any other placeholders.

I hope this feature is added. without interacting with other plugins

**Comment by andrei1058** [comment]
so with the new sidebar you get heart icons instead of a number? what server version is that?

**Comment by ImYenil** [comment]
> so with the new sidebar you get heart icons instead of a number? what server version is that?

Yes my server version 1.8.9

**Comment by tomkeuper** [comment]
This is not fixed with the last commit.

**Comment by tomkeuper** [comment]
The issue was not to show or not show the health of a player or above their head but the issue was to replace the hearts by the yellow value as seen in the first screenshot

**Comment by ImYenil** [comment]
> The issue was not to show or not show the health of a player or above their head but the issue was to replace the hearts by the yellow value as seen in the first screenshot

Is what I described added as it is?
