### ISSUE TITLE
Tablist issue

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#700]
**Describe the bug**
The tab list changes during gameplay.
R PlayerName should be displayed like this, but sometimes Red PlayerName goes like this and then R PlayerName is displayed like this. Attached as a picture.
![2023-03-05_20 29 22](https://user-images.githubusercontent.com/85287520/222958071-7fbca68e-6fc8-41a1-8027-cab3a98734ac.png)
![2023-03-05_20 30 21](https://user-images.githubusercontent.com/85287520/222958072-7f7ebabd-2947-48b3-ad25-dba068590990.png)

**To Reproduce**
happen during game play

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 

**Additional context**

**Comment by tomkeuper** [comment]
Thats not a bug, thats a feature.
Open your language file and search for `format-sb-tab`. 
You can configure it all you want in there
