### ISSUE TITLE
The tablist is not reset when leaving the game after starting the game

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#701]
**Describe the bug**

The tablist is not reset when leaving the game after starting the game

**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.imgur.com/YtCTIzn.png

**System (please complete the following information):**
 - OS:  windows 11
 - Server software  paper
 - Server Version  1.8.8
 - Plugin Version  23.2.1

**Additional context**

**Comment by tomkeuper** [comment]
do you have a server log? or atleast some more info about your server config?

**Comment by ImYenil** [comment]
> do you have a server log? or atleast some more info about your server config?

no console issue

**Comment by itdoesnotmatterr** [comment]
> do you have a server log? or atleast some more info about your server config?

No errors are shown in the console, and the configuration is default - I haven't changed any settings for scoreboards and messages files, after reverting to version 22.3.4 with the same files everything works fine

**Comment by tomkeuper** [comment]
That could be but there is almost no info so you should send a server log

**Comment by ImYenil** [comment]
> That could be but there is almost no info so you should send a server log

my bedwars1058 config.yml
https://pastebin.com/cctC2iiY

**Comment by tomkeuper** [comment]
I believe this happens because when joining the server for the first time there is a listener that sends the lobby tab list but when a game ends there is no event that gets triggered when joining the lobby world.

**Comment by tomkeuper** [comment]
Will be fixed in the new update
