### ISSUE TITLE
Tab prefix from game to lobby

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#712]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software  Pufferfish version git-Pufferfish-60 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 52307ae on HEAD)
 - Server Version  1.19.3
 - Plugin Version  dev build

**Additional context**

**Comment by tomkeuper** [comment]
What is this about?
