### ISSUE TITLE
I made Chinese language, but displayed garbled code in the game. 

### ISSUE THREAD

**Issue by Sakura1618** [andrei1058/BedWars1058#716]
**Describe the bug**
I made Chinese language, but displayed garbled code in the game. 

**To Reproduce**
After complete translation, it is named messages_ cn.yml.
Switch the language in the game and find garbled code.
The language file is forced to transcode

**Expected behavior**
Normal display of Chinese

**Screenshots**
Exception text：
![image](https://user-images.githubusercontent.com/106215893/224970618-dc18b4d3-21d8-426b-986a-8b516a2100ef.png)
Normal text：
![image](https://user-images.githubusercontent.com/106215893/224970756-b04d85a7-37c3-4158-a94f-3238db80a104.png)
In game：
![image](https://user-images.githubusercontent.com/106215893/224971072-b4a97225-449a-4df8-b7fa-51f8726bebbb.png)
plugins：
![image](https://user-images.githubusercontent.com/106215893/224972085-015ecff2-c91a-4f37-80b3-3073c54c5a76.png)

**System (please complete the following information):**
 - OS: Windows 10 22H2
 - Server software: spigot
 - Server Version: 1.8.8
 - Plugin Version: bedwars-plugin-23.2.1.jar

**Comment by tomkeuper** [comment]
This is not a problem caused by bedwars. Its due to the encoding you are using when editing and saving the config files.
