### ISSUE TITLE
ERROR Could not pass event InventoryClickEvent to BedWars1058 v23.2

### ISSUE THREAD

**Issue by Ultroneoucs** [andrei1058/BedWars1058#719]
**Describe the bug**

The game does not want to start. Even if i do /bw start nothing happens. When one player joins 
**To Reproduce**

 - Server software spigot
 - Server Version 1.8.8
 - Plugin Version 23.2.1

**Additional context**
I try to run the plugin just by its self and nothing worked

**Comment by tomkeuper** [comment]
Use the discord server for support
