### ISSUE TITLE
Scoreboard Placeholder with colors does not work.

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#722]
**Describe the bug**
If the placeholder returns its color and value, the color does not on scoreboard.

**To Reproduce**
1. Go to Server
2. See Scoreboard Bug

**Expected behavior**
colors should work!

**Screenshots**
![image](https://user-images.githubusercontent.com/124730657/226135999-efc3c933-1be0-462b-a988-b7b9c8f9523c.png)

**System (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Server software: PandaSpigot (fork of NachoSpigot)
 - Server Version 1.8.8
 - Plugin Version: v23.2

**Additional context**

**Comment by tomkeuper** [comment]
Can you post your scoreboard config? so we can see what it should look like

**Comment by actuallySoheil** [comment]
> Can you post your scoreboard config? so we can see what it should look like

sure!

```
  lobby:
  - '&3&lBED WARS'
  - ''
  - '&fRank: %vault_rank%'
  - ''
  - '&fLevel: {level}'
  - ''
  - '&fProgress: &b{currentXp}&7/&3{requiredXp}'
  - '{progress}'
  - ''
  - '&fCoins: &3{money}'
  - ''
  - '&fWins:&b %bw1058_stats_wins%'
  - '&fKills: &b{kills}'
  - ''
  - '&a{server_ip}'
  ```
  
 _I use %bw1058_stats_wins% instead of {wins}, because that placeholder doesn't work._
  
  **EDIT:** I was told that I had to use {Wins} instead of {wins} "w" with uppercase. ignore that message.

**Comment by actuallySoheil** [comment]
@andrei1058
