### ISSUE TITLE
Kick all players in arena

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#723]
**Describe the bug**
Kick all players in arena when the game is finished or someone would win a game.

**To Reproduce**
1. Go to Server
2. Go to Arena
3. Win/Lose a game .
4. Get Kicked.

**Expected behavior**
Players shouldn't get kicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/124730657/226188040-cec45aa8-b0c0-49ac-a0d3-20ffdb95c585.png)

**System (please complete the following information):**
 - OS: Linux (Ubuntu 20.24)
 - Server software: PandaSpigot (Fork of NachoSpigot)
 - Server Version: 1.8.8
 - Plugin Version: v23.2

**Additional context**

**Comment by tomkeuper** [comment]
Use the latest version of the plugin. You can always join the discord for support or questions.
