### ISSUE TITLE
When Polish language is selected, Teams Upgrade menu won't open.

### ISSUE THREAD

**Issue by MajliTech** [andrei1058/BedWars1058#724]
**Describe the bug**

When Polish language is selected, Teams (or solo) Upgrades menu won't open. 

**To Reproduce**

1. Change `language` in `config.yml` to `pl`
2. (Re)start the server
3. Start a game of BedWars
4. Try clicking on Teams (or Solo) Upgrades

**Expected behavior**

The menu should open letting players upgrade their base.
**Screenshots**

Doesn't apply
**System (please complete the following information):**
 - OS: Ubuntu Server Linux
 - Server software Spigot
 - Server Version 1.18.2
 - Plugin Version 23.2.1

**Additional context**

I have lost the logs to my server, so i won't attach the error log, but it said something with a wrongly-formated string. The error on top just said "null"

**Comment by tomkeuper** [comment]
This will be fixed in the next release

**Comment by MajliTech** [comment]
Any temporary workaround?

**Comment by tomkeuper** [comment]
> Any temporary workaround?

Correct the tier update lores. (forge tier 4, swords tier 1)
