### ISSUE TITLE
The `/bw build` feature doesn't save the world upon changes

### ISSUE THREAD

**Issue by MajliTech** [andrei1058/BedWars1058#725]
**Is your feature request related to a problem? Please describe.**
The `/bw build` feature doesn't save the world upon changes

**Describe the solution you'd like**
Add a warning to all string that changes built whit this are not saved

**Describe alternatives you've considered**
When a opertator with a permission joins the server, the plugin shoud send him/her a message encouraging to read the documentation

**Additional context**
Didn't read the docs, built the map using `/bw build`, and now it's gone.

**Comment by tomkeuper** [comment]
BW build is not ment to save any changes to the map. You should make changes to an arena when using /bw setup. 
you should only use finalised arenas

**Comment by MajliTech** [comment]
Yea, but for the players it isn't clear, when they do /bw build Minecraft should automatically saves the changes.

**Comment by tomkeuper** [comment]
bw build is only ment if you need to make edits to the lobby. And NOT the arena.

**Comment by MajliTech** [comment]
For mez it doesnt even save the arena, but adding a string like that could make life of us easier.

**Comment by MajliTech** [comment]
C'mon, i will make a pull request with this change.

**Comment by tomkeuper** [comment]
You dont understand what im saying. 
bw build is for the lobby. It does not do anything in bedwars arenas and shouldnt be used there either. Bedwars arenas are not ment to be changed when you import them and this will most likely break the worldloader/swm integration

/bw build enables server owners to place blocks in the lobby world. because normal behaviour is to cancel block place/break events.

**Comment by MajliTech** [comment]
I know and I understand you, so I say that you should add a warning to a player when they do /bw build so that they dont lose their whole map

**Comment by tomkeuper** [comment]
And where / when should we add that warning? It clearly says on the wiki that bw build allows players to build in the lobby

**Comment by MajliTech** [comment]
But people don't read the Wiki,.so maybe encourage them to?
Also, I'm using players but I'm referring to operators.

**Comment by MajliTech** [comment]
> And where / when should we add that warning? It clearly says on the wiki that bw build allows players to build in the lobby

Upon running /bw build, for example:
Building enabled! WARNING: this is not for building maps.please only import them using /bw setupArena instead.

**Comment by tomkeuper** [comment]
I can add a warning on the wiki. But poeple shoulld just read the wiki imo. 
I dont think its a good solution to add all that to the bw build command as 95% of the poeple using this plugin do know how to use it. I also dont know if its possible to check if a world is an arena when its just been added either.

**Comment by MajliTech** [comment]
But well, the lobby doesn't save, even with /bw build. That's the point.

**Comment by MajliTech** [comment]
> I can add a warning on the wiki. But poeple shoulld just read the wiki imo. I dont think its a good solution to add all that to the bw build command as 95% of the poeple using this plugin do know how to use it. I also dont know if its possible to check if a world is an arena when its just been added either.

Well, then at least encourage people to read the wiki, like I've described in my alternatives solution:
> When a opertator with a permission joins the server, the plugin shoud send him/her a message encouraging to read the documentation

**Comment by tomkeuper** [comment]
> But well, the lobby doesn't save, even with /bw build. That's the point.

The lobby should be saved by your server thats not up to bedwars. Bedwars doesnt do any saving of worlds it only loads arena worlds. Its up to the server to save a world when it shuts down or a save gets triggered.



About the second part: 
If you want you can create a feature request about prompting to read the wiki, but in my opinion people should always read the wiki before even trying to use the plugin xD. I noticed lots of customers that have never looked at the wiki but none gives us feedback about it.

**Comment by MajliTech** [comment]
So it's my server problem?

**Comment by tomkeuper** [comment]
For the lobby not saving yes but you should use the support discord server if you need help

**Comment by MajliTech** [comment]
Will look into it thanks. Should now close, but it's already closed.
