### ISSUE TITLE
spigot1.8 invisibility bug

### ISSUE THREAD

**Issue by RedCarl** [andrei1058/BedWars1058#727]
**Describe the bug**
You can still see the player's nametag after invisibility

**To Reproduce**
invisibility potion

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software spigot
 - Server Version 1.8.9
 - Plugin Version latest

**Additional context**

**Comment by tomkeuper** [comment]
Duplicate of #688

**Comment by tomkeuper** [comment]
Also your bug report is invallid as you dont provide enough info like what exact version you are using (dont say latest) and  no steps to reproduce, no evidence.
