### ISSUE TITLE
v1_19_R3 Support...

### ISSUE THREAD

**Issue by RockyStan** [andrei1058/BedWars1058#729]
**Describe the bug**
Bedwars will not start on paper mc v1_19_R3
**To Reproduce**
Install bedwars1058 on a paper v1_19_R3 server
Start the server
**Expected behavior**
The plugin starts normally

**System (please complete the following information):**
 - OS: Linux
 - Server software paper
 - Server Version 1.19.4
 - Plugin Version 23.2.1

**Comment by tomkeuper** [comment]
This is not a bug, just not yet implemented.

**Comment by ImYenil** [comment]
> **Describe the bug** Bedwars will not start on paper mc v1_19_R3 **To Reproduce** Steps to reproduce the behavior: Install bedwars1058 on a paper v1_19_R3 server Start the server **Expected behavior** The plugin starts normally
> 
> **System (please complete the following information):**
> 
> * OS: Linux
> * Server software paper
> * Server Version 1.19.4
> * Plugin Version 23.2.1

im working it
