### ISSUE TITLE
Wooden sword during respawn

### ISSUE THREAD

**Issue by tomkeuper** [andrei1058/BedWars1058#732]
**Describe the bug**

When a player is in a respawnsession It can get the default sword by opening the inventory. 

**To Reproduce**

**Expected behavior**
No sword is given

**Screenshots**
https://4gsknv-my.sharepoint.com/:v:/g/personal/owner_winarc_cn/EX2tOrARuy1Ejkk2fJ2sxsgBQ_aEM3Bf0uAVWBBl-To_iA?e=k6C6iR

**System (please complete the following information):**
 - OS: linux
 - Server software paper
 - Server Version 1.8.8
 - Plugin Version 23.2.1-BETA-3

**Additional context**

**Comment by MajliTech** [comment]
That's good.

**Comment by tomkeuper** [comment]
Closing as completed
