### ISSUE TITLE
After death, the players get kicked to lobby

### ISSUE THREAD

**Issue by MajliTech** [andrei1058/BedWars1058#733]
**Describe the bug**

After death (final or not), the players get kicked to lobby
**To Reproduce**

Just kill a plyer in a game, it should kick him out (sometimes it doesnt)
**Expected behavior**

**Screenshots**

Logs:
```
[20:37:13] [Server thread/INFO]: [BedWars1058] DEBUG: removePlayer debug1
[20:37:13] [Server thread/INFO]: [BedWars1058] DEBUG: ReJoin getPlayer 28b0b1d9-e98f-313d-8717-b31261d86b98
[20:37:13] [Server thread/INFO]: [BedWars1058] DEBUG: Created ReJoin for kozaczekmaks 28b0b1d9-e98f-313d-8717-b31261d86b98 at ulubione
[20:37:13] [Server thread/INFO]: [BedWars1058] DEBUG: kozaczekmaks was removed from Ulubione because he was teleported outside the arena.
```

**System (please complete the following information):**
 - OS Linux
 - Server software Spigot
 - Server Version 1.18.2
 - Plugin Version 23.2..1

**Additional context**
Player are not able to respawn ,even with bed.
Plugins (9): LuckPerms, EasyWhitelist, FastAsyncWorldEdit (WorldEdit), ServersNPC, Bedwars1058-AdminAddon, BedWars1058, WorldGuard, FlyPerms, ExtraContexts

**Comment by tomkeuper** [comment]
Im 99% sure this is not caused by bedwars1058. Maybe one of your plugins is handling respawn events. 
You could try with only bedwars installed. 

By looking at your plugins it might be worldguard. Why are you using this anyways? Bedwars1058 already stops certain actions in lobby etc.

**Comment by MajliTech** [comment]
WorldGuard is used for flight in lobby. If yjere

**Comment by MajliTech** [comment]
Misclick with closing. WorldGuard is used for flying in lobby. Is there a way to do it with only BedWars1058?

**Comment by MajliTech** [comment]
I will try and delete WorldEdit and do fly with server: bedwars and world:world (since I have luckperms)

**Comment by MajliTech** [comment]
Update: WorldGuard was the issue (for my small testing), will reopen if it occures again.
