### ISSUE TITLE
Player team tag in lobby

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#739]
**Describe the bug**
I can see my in-game team tag in the lobby when the game is finished.

**To Reproduce**
1. Finish game
2. Go to lobby
3. see the bug

**Expected behavior**
X

**Screenshots**
![image](https://user-images.githubusercontent.com/124730657/227745831-67bfb9c1-1ad4-44a8-aa95-89218779ec9f.png)

**System (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Server software: BurritoSpigot (fork of TacoSpigot)
 - Server Version 1.8.8
 - Plugin Version 23.2.1

**Comment by tomkeuper** [comment]
server log?

**Comment by actuallySoheil** [comment]
Nothing special was on log, don't worry! this is not an error.

**Comment by actuallySoheil** [comment]
Duplicate of #712. closing the ticket.
