### ISSUE TITLE
Implement Per Group Stats in code.

### ISSUE THREAD

**Issue by actuallySoheil** [andrei1058/BedWars1058#743]
**Is your feature request related to a problem? Please describe.**
It's so lame to have an addon for a stats placeholder. please add it to the code.

**Describe the solution you'd like**
There is an addon which can do this, but it would be better if we had it in the BedWars1058

**Describe alternatives you've considered**
Here is the addon: https://www.spigotmc.org/resources/105279/

**Additional context**
X

**Comment by Chromaah** [comment]
well since its an addon, not sure why you would want it into the code

plus that dev probably spent some time on that addon lol

**Comment by actuallySoheil** [comment]
when we have something like this placeholder "%bw1058_group_count_[groupName]%", why wouldn't we have something like, lets say "%bw1058_stats_wins_[groupName]%"?

**Comment by Chromaah** [comment]
well its already a thing as an addon, why would you need to implement it

**Comment by actuallySoheil** [comment]
to have less plugins

**Comment by andrei1058** [comment]
Plugin count does not impact implicitly on the server performance.

You would need to give us a better reason to prioritize your request xD

**Comment by Xxyuri2005xX** [comment]
#568
