### ISSUE TITLE
header & footer bug + and some minors

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#745]
**Describe the bug**
when updating bw1058 to version 23.3 the "header & footer" function is simply replacing the TAB (neznamy), which clearly shouldn't happen as this function is disabled

**To Reproduce**
upgrade to 23.3 and use TAB (neznamy) in proxy?

**Expected behavior**
Clearly bw1058 shouldn't replace the header & footer of the TAB(neznamy) as it is disabled

**Screenshots**
[github doesn't allow uploading videos so I uploaded to youtube :) - (https://youtu.be/bDWFB0zT5F4) - ](https://youtu.be/bDWFB0zT5F4)

**System (please complete the following information):**
 - OS: windows (test server)
 - Server software: paper-1.8.8
 - Server Version: 1.8.8
 - Plugin Version: 23.3

**Additional context**
another thing that I will be reporting here, you can see in the video that I use the subtitle for the seconds and when the match starts, you can see that the subtitle for that part continues to be "Prepare-se" when in fact it should be the same as the image below

![image](https://user-images.githubusercontent.com/120399502/228102857-eb289237-2911-4eb7-a3a3-b0e1e3616786.png)

you can also see that "arena-start-tutorial" is not shown

**Comment by Lsy-291** [comment]
The implementation of the section on the tab column in 1058 is simply terrible, unreadable, and the names of various methods, variables, and configurations are chaotic. You can't even sort out its execution logic, silly code

**Comment by andrei1058** [comment]
> The implementation of the section on the tab column in 1058 is simply terrible, unreadable, and the names of various methods, variables, and configurations are chaotic. You can't even sort out its execution logic, silly code

You even have comments here.. not sure what's silly from your point of view
https://github.com/andrei1058/BedWars1058/blob/c5eec9bdb51224622e9c137ff16302dae081a770/bedwars-plugin/src/main/java/com/andrei1058/bedwars/sidebar/BwSidebar.java#L383

**Comment by andrei1058** [comment]
start tutorial works fine

**Comment by joohnaquino** [comment]
> start tutorial works fine

For me it still doesn't work, is it the format in which it is defined?

I tested the latest beta version of the plugin, it still didn't work
