### ISSUE TITLE
Initial SHOP configuration of the tower gets wrong.

### ISSUE THREAD

**Issue by WitheredWinter** [andrei1058/BedWars1058#746]
**Describe the bug**

The default shop config has tower set wrongly.When u use default config,in game u buy a tower but u will get a bedrock.
**To Reproduce**

just use the original generated shop config and buy the tower in game

**Expected behavior**

u will get a chest with custom name when u buy that.
**Screenshots**

![image](https://user-images.githubusercontent.com/123742753/228236618-2c6810b5-0a23-4eaa-bd79-dab0aae41e2d.png)
![image](https://user-images.githubusercontent.com/123742753/228236736-55576c36-2aae-4d4b-b3d3-ec9ff3a0572e.png)
![image](https://user-images.githubusercontent.com/123742753/228236759-ee934c7e-1e6f-4e37-9fbe-39f09678ef49.png)

**System (please complete the following information):**
 - OS: Win10
 - Server software Paper
 - Server Version 1.8.8
 - Plugin Version 23.3

**Comment by EvilG-MC** [comment]
Is there a solution for this problem?

**Comment by Lsy-291** [comment]
In theory, this is a problem with your configuration. The material in buy items should be the one in minecraft, and the tower does not exist in the original minecraft. Bedwars1058 will provide the player with bedrock after discovering this error, which should be CHEST

**Comment by andrei1058** [comment]
**ShopManager#355**

```java
addBuyItem(ConfigPath.SHOP_PATH_CATEGORY_UTILITY, "tower", "tier1", "tower", BedWars.getForCurrentVersion("TOWER", "TOWER", "TOWER"),
                    0, 1, "", "", "", false);
```
