### ISSUE TITLE
Translations!😀

### ISSUE THREAD

**Issue by SilianZ** [andrei1058/BedWars1058#755]
**Is your feature request related to a problem? Please describe.**
Can we add a translation project on Crowdin to translate language files and github guidelines?

**Describe the solution you'd like**
Create new project on Crowdin

**Comment by andrei1058** [comment]
We do not have the budget for crowdin

**Comment by andrei1058** [comment]
We asked for an open source license to Crowdin. We'll let you guys know if they accept our request :)

**Comment by andrei1058** [comment]
We got it!

**Comment by SilianZ** [comment]
NICE!
