### ISSUE TITLE
Can Added version 1.19.4?

### ISSUE THREAD

**Issue by AbeAzka** [andrei1058/BedWars1058#759]
**Is your feature request related to a problem? Please describe.**
Uhm, i need support version for 1.19.4

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tom18314** [comment]
@AbeAzka take a look at my PR: https://github.com/andrei1058/BedWars1058/pull/761

**Comment by AbeAzka** [comment]
thanks
