### ISSUE TITLE
error when get kill

### ISSUE THREAD

**Issue by BLACKGAMER1221** [andrei1058/BedWars1058#760]
**Describe the bug**
when players get kill show this error on console
log: https://mclo.gs/y9Xj5tf

**To Reproduce**
1. Go to bedwars
2. start a match 
3. get a kill 

**Expected behavior**
https://mclo.gs/y9Xj5tf

**Screenshots**
https://mclo.gs/y9Xj5tf

**System (please complete the following information):**
 - OS: linux
 - Server software: paper
 - Server Version: 1.12.2
 - Plugin Version: 23.3

**Comment by andrei1058** [comment]
Any add-ons?

**Comment by BLACKGAMER1221** [comment]
leave delay 
map selector 
cosmetic ( by Iam TheDefender)
play again 
team selector 
voidless 
winstreak 
xpbar 
anti drop 
pop up tower 
sponge
