### ISSUE TITLE
Player's team on the teleporter

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#766]
Add a placeholder (or make current ones compatible) to show player's team/color when using teleporter in spectator mode

example:
![image](https://user-images.githubusercontent.com/120399502/233503790-2a8a1e34-fa31-4ca9-8793-c23d07b72e3c.png)

the "BLAZE" is the player's rank

**Comment by andrei1058** [comment]
Fixed with #796
