### ISSUE TITLE
Improvements to the inner tab

### ISSUE THREAD

**Issue by joohnaquino** [andrei1058/BedWars1058#768]
Honestly, I don't see a good reason why they added this, but I understand why it was, and since it's been added, it's causing some serious problems (#745)

it does not support the placeholderAPI (not even its own internal placeholders), it is not possible to add more than one line (???), even if it is disabled, it is shown...

**Comment by andrei1058** [comment]
Isn't this just another copy of your other reports?

**Comment by joohnaquino** [comment]
> Isn't this just another copy of your other reports?

maybe if you want to see it that way

I did it this way because I think it would be more organized, sorry for the spam
