### ISSUE TITLE
game end scoreboard issue & playing tablist issue

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#774]
**Describe the bug**

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/85287520/235189492-489ebfb0-1001-49a6-a24b-cc4de63c5415.png)
You will see your server date under yourServer.com

![2023-04-29_00 28 40](https://user-images.githubusercontent.com/85287520/235189891-2586c20a-f844-49a4-b115-5514eb86740b.png)

**System (please complete the following information):**
 - OS:  Windows
 - Server software  paper
 - Server Version  1.8.9
 - Plugin Version  23.3-SNAPSHOT

**Additional context**

**Comment by ImYenil** [comment]
Look the viedo

https://youtu.be/5ddrlIRKR8g

**Comment by andrei1058** [comment]
I'm working on it!

**Comment by andrei1058** [comment]
Found it,

It's called twice on restart
![image](https://github.com/andrei1058/BedWars1058/assets/13315829/9336ac23-83bc-4968-b136-a9328c2ea474)
