### ISSUE TITLE
A real gamemode 3 for spectator

### ISSUE THREAD

**Issue by liquidman228** [andrei1058/BedWars1058#776]
Hello
I have a superpowers plugin on my bedwars server to make it more fun, but when a player is spectating, he still can use his powers, because he is in survival gamemode, which makes him able to ruin others gameplay

Would be great if we have a option to make spectators be in spectator gamemode
For example, add in config:
gm3ForSpectators: true

**Comment by andrei1058** [comment]
No

**Comment by andrei1058** [comment]
The best solution is to ask the author to use the bedwars api and check when a player is in a bedwars game and he is spectating.
