### ISSUE TITLE
*URGENT* Obtaining items like bedrock through upgrade shop

### ISSUE THREAD

**Issue by ZodiussDev** [andrei1058/BedWars1058#786]
**Describe the bug**
When playing on a server with GeyserMC _(bedrock support)_ on a mobile device _(I don’t know if it happens on a desktop device)_ you can obtain an iron chestplate by taking the iron chestplate in the upgrade shop and putting it into one of your hot bar slots and then holding down your screen to swap the default leather tunic with the iron chestplate. You can also do this with some of the blocks, but they dissapear most of the time.

**To Reproduce**
1.) Create a Minecraft 1.17.1 server with Bedwars1058, Geyser, and ViaVersion
2.) Join on your bedrock mobile _(or desktop of it happens on a desktop device)_ device
3.) Start a game without collecting any diamonds
4.) Go into the upgrade shop
5.) Click the iron chestplate _(the upgrade for armor protection)_ and then tap a spot in your hotbar to place the iron chestplate in that slot
6.) It will take you out of the shop and tell you that you do not have enough diamonds to purchase the upgrade
7.) Hold the slot that the chestplate is in
8.) Long-press the screen to equip the chestplate

**Expected behavior**
The iron chestplate / blocks should not be able to be taken out of the upgrade shop and it will just kick you out of the upgrade menu

**System:**
 - Device: _Any mobile device that runs Minecraft Bedrock Edition_
 - Server software: _Paper_
 - Server Version: _1.17.1_
 - Plugin Version: _23.3_

**Comment by andrei1058** [comment]
this plugin is for minecraft java edition. if you want us to invest in adding support for bedrock clients considering investing in this project :)
