### ISSUE TITLE
dont work for 1.17.1

### ISSUE THREAD

**Issue by blueApple12** [andrei1058/BedWars1058#787]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software 
 - Server Version 
 - Plugin Version 

**Additional context**

**Comment by ImYenil** [comment]
1.17.1 no longer supported

**Comment by JT122406** [comment]
1.17.1 is supported but we need more info to help

**Comment by andrei1058** [comment]
What does it say in your server console?
