### ISSUE TITLE
Custom map cannot be loaded by plugin

### ISSUE THREAD

**Issue by Lsy-291** [andrei1058/BedWars1058#789]
I have a map named Lexus, and I created a file named lectusyml in the Arenas folder under the bedwars1058 plugin. I am sure it is okay, and its content is as follows

group: Solo
display-name: lectus
minPlayers: 2
maxInTeam: 4
allowSpectate: true
spawn-protection: 5
shop-protection: 1
upgrades-protection: 1
generator-protection: 1
island-radius: 17
worldBorder: 300
y-kill-height: -1
max-build-y: 180
disable-generator-for-empty-teams: false
disable-npcs-for-empty-teams: true
vanilla-death-drops: false
use-bed-hologram: true
allow-map-break: false
game-rules:
- doDaylightCycle:false
- announceAdvancements:false
- doInsomnia:false
- doImmediateRespawn:true
- doWeatherCycle:false
- doFireTick:false
- doMobSpawning:false
waiting:
  Loc: 0.0,118.0,0.0,-180.0,0.0
  Pos1: 2.0,118.0,2.0,-88.0,2.0
  Pos2: -3.0,118.0,3.0,0.0,2.0
Team:
  Yellow:
    Color: YELLOW
    Spawn: -46.0,66.0,47.0,132.9,-2.7
    Bed: 40.0.66.0,42.0,0.0,0.0
    Iron:
    - 45.0,65.0,53.0,0.0,0.0
    Gold:
    - 45.0,65.0,53.0,0.0,0.0
    Emerald:
    - 45.0,65.0,53.0,0.0,0.0
    Upgrade: 52.0,65.0,47.0,89.7,-2.1
    Shop: 52.0,65.0,45.0,89.7,-2.1
  Green:
    Color: GREEN
    Spawn: 47.0,66.0,-45.0,43.0,-2.5
    Bed: 42.0,66.0,-39.0,0.0,0.0
    Iron:
    - 53.0,65.0,-44.0,0.0,0.0
    Gold:
    - 53.0,65.0,-44.0,0.0,0.0
    Emerald:
    - 53.0,65.0,-44.0,0.0,0.0
    Shop: 45.0,65.0,-51.0,0.0,0.0
    Upgrade: 47.0,65.0,-51.0,0.0,0.0
  Red:
    Color: RED
    Spawn: -45.0,66.0,-46.0,-45.3,-1.0
    Bed: -39.0,66.0,-41.0,0.0,0.0
    Shop: -51.0,65.0,-44.0,-92.4,-1.6
    Upgrade: -51.0,65.0,-46.0,-92.4,-1.6
    Iron:
    - -44.0,65.0,-52.0,0.0,0.0
    Gold:
    - -44.0,65.0,-52.0,0.0,0.0
    Emerald:
    - -44.0,65.0,-52.0,0.0,0.0
  Blue:
    Color: BLUE
    Spawn: -46.0,66.0,46.0,-138.2,0.9
    Bed: -41.0,66.0,40.0,0.0,0.0
    Iron:
    - -52.0,65.0,45.0,0.0,0.0
    Gold:
    - -52.0,65.0,45.0,0.0,0.0
    Emerald:
    - -52.0,65.0,45.0,0.0,0.0
    Upgrade: -46.0,65.0,52.0,178.0,-2.5
    Shop: -44.0,65.0,52.0,178.0,-2.5
generator:
  Diamond:
  - -53.0,65.0,0.0,0.0,0.0
  - 0.0,65.0,-53.0,0.0,0.0
  - 54.0,65.0,0.0,0.0,0.0
  - 0.0,65.0,54.0,0.0,0.0
  Emerald:
  - -13.0,65.0,0.0,0.0,0.0
  - 14.0,65.0,0.0,0.0,0.0

After completing, I received this prompt when I started the server
[BedWars1058] Arena lectus ws added to the enable queue.
But in reality, after I entered the server and used the command/bw arenaList to view all available maps, I found that this map was not loaded. How should I solve it

I am using Java11 to open the server, and the bedwars1058 version is 23.3

**Comment by andrei1058** [comment]
What MC version was it built on? Does it load in single player?

**Comment by Lsy-291** [comment]
> *
I'm sorry for replying so late. The server version I'm using is spot 1.8.8, and I need to load the map. I have tested it and it can be opened normally in single player games

**Comment by Lsy-291** [comment]
And could you please review another question I raised and help me successfully build this project? I would greatly appreciate it

**Comment by Lsy-291** [comment]
And could you please review another question I raised and help me successfully build this project? I would greatly appreciate it

**Comment by andrei1058** [comment]
@Lsy-291 did you manage to fix it?
