### ISSUE TITLE
NPCS not spawning

### ISSUE THREAD

**Issue by tehsuff** [andrei1058/BedWars1058#799]
![2023-06-04_02 42 17](https://github.com/andrei1058/BedWars1058/assets/89362518/198559fd-05d3-4822-9fba-3fb0b9049ea1)

**Comment by Lsy-291** [comment]
Please provide more relevant information
For example, server logs, arena configuration, etc

**Comment by DaddySuff** [comment]
Logs:
- https://pastebin.com/USRgcE4g
Arena:
- https://pastebin.com/VvweB81a
Plugins:
![image](https://github.com/andrei1058/BedWars1058/assets/89362518/e5e9478b-5056-4cd8-b04b-7fcacd3b5699)

**Comment by TehJays** [comment]
@Lsy-291 how do i fix this

**Comment by DaddySuff** [comment]
@Lsy-291 i have given the wanted info, please help me out.
