### ISSUE TITLE
Player hearts on bungeemode bug

### ISSUE THREAD

**Issue by Askarionn** [andrei1058/BedWars1058#8]
Bug: If the game ends and you have for example 2 hearts and you rejoin on same mode you will still have 2 hearts. It doesn't reset
Plugin version: 21.10.1
Server version: 1.8.8

Reproduce:
x1 bedwarsproxy lobby, x1 server for solo mode (it doens't matter the mode)

**Comment by marioded** [comment]
Please describe better or make a video about it because the description is confusing.

**Comment by Askarionn** [comment]
https://www.youtube.com/watch?v=skv_8g-5f3g

**Comment by marioded** [comment]
Will fix this when I'll be home.

**Comment by Askarionn** [comment]
can anyone fix this?
