### ISSUE TITLE
Server crashes when a bedwars game starts (normally and with start debug)

### ISSUE THREAD

**Issue by QuantaNeon** [andrei1058/BedWars1058#80]
**Describe the bug**
I am **running a bungeecord network and the bedwars server crashes** as soon as i do start debug or start normally
I tried **running it without bungeecord and that way it starts corrctly**
 
![image](https://user-images.githubusercontent.com/84242952/141254943-e57139d2-5d83-46be-8347-41f334129ff5.png)

**System:**
 - OS: ubuntu ( running on arm architecture )
 - Server software spigot
 - Server Version 1.17.1
 - Plugin Version - 21.11

My config - https://pastebin.com/Mxmx9FR3
Logs - https://pastebin.com/2204aiwg

**Comment by ajgeiss0702** [comment]
Your log doesnt seem to have the crash in it. Please send the log from when the server crashed, and/or send the crashlog.

Also note that 1.17 isnt fully supported yet, and this may not be resolved until it is.
