### ISSUE TITLE
format-sb-tab-prefix spectator doesn't work

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#806]
**Describe the bug**

![image](https://github.com/andrei1058/BedWars1058/assets/85287520/6828f34f-63d4-4780-9995-27843c527226)
This option doesn't work.

**To Reproduce**

**Screenshots**
 Windows 11
 - Server software  Paper
 - Server Version  1.8.8
 - Plugin Version  23.3
 
**Additional context**

**Comment by ImYenil** [comment]
![image](https://github.com/andrei1058/BedWars1058/assets/85287520/4d3d1cf5-25ec-412a-9974-4ddf3616c05c)

**Comment by ImYenil** [comment]
Need more information? I think it's good enough for photos. If not you try testing

**Comment by andrei1058** [comment]
happens on 1.12 as well.
