### ISSUE TITLE
1.20 Version Support

### ISSUE THREAD

**Issue by Bensonheimer992** [andrei1058/BedWars1058#808]
Please add 1.20 Version Support. This plugin is great i live This plugin but 1.20 is out and i want to Update my server

**Comment by redbluewisper** [comment]
any update on this?

**Comment by ssdrive-flaktra** [comment]
guess not

**Comment by Lsy-291** [comment]
Andrei stated that he expects to add support for 1.20 in a month, as now 'We don't even have stable spot builds for that version'

**Comment by andrei1058** [comment]
I see there's a bit of demand for this update LOL

**Comment by ssdrive-flaktra** [comment]
Yeah, we really don’t want to run on 1.19.4 since we need to use the new blocks. Hopefully you can make NMS work

**Comment by andrei1058** [comment]
Will do this weekend

**Comment by ssdrive-flaktra** [comment]
> Will do this weekend

thanks :)

**Comment by Bensonheimer992** [comment]
> Will do this weekend

Update to 1.20 ?
