### ISSUE TITLE
Crowdin Translations

### ISSUE THREAD

**Issue by SilianZ** [andrei1058/BedWars1058#809]
This bug comes from Crowdin. We refer to it as' translation mismatch ', which means that the translated content does not match the original text due to Crowdin's use of a certain method when reading the yml configuration file.

For example, the following paragraph takes up 3 lines of space in the original text, but when translated into Chinese, only one line is used, resulting in the remaining 2 lines being unable to be translated.

![image](https://github.com/andrei1058/BedWars1058/assets/113701655/2f4c3c83-b4a8-41e7-8515-fb0b6779ade9)
![image](https://github.com/andrei1058/BedWars1058/assets/113701655/cbe7d477-e735-45a2-853a-4845e237e72f)
![image](https://github.com/andrei1058/BedWars1058/assets/113701655/0207a8e0-ec7f-488a-aeab-2bd90817bc1e)
![image](https://github.com/andrei1058/BedWars1058/assets/113701655/9e86caf0-b3a4-4247-ad94-e323ad09173b)

In the fourth image, due to the fact that the Chinese configuration file only occupies one line of space, the content that should have existed in the next line does not match the original text, and even matches the content that needs to appear in the next two lines.

![image](https://github.com/andrei1058/BedWars1058/assets/113701655/8bf6de2d-7fef-422f-ac48-2e952d739b01)

In order to better assist in understanding, I will put it another way.

Now I am translating a new language - Chinese. I have opened the editor and made the original code changes as follows:

```yml
1  upgrades-upgrade-lore-swords-tier-1:
2  - '&7Your team permanently gains'
3  - '&7Sharpness I on all swords and'
4  - '&7axes!'
5  - ''
6  - '&7Cost: &b{cost} {currency}'
7  - ''
```
↓↓↓ Post-translational ↓↓↓

```yml
1  upgrades-upgrade-lore-swords-tier-1:
2  - '&7你的队伍将永远在所有的剑和斧头上获得锋利 I'
3  - ''
4  - '&7花费：&b{cost} {currency}'
5  - ''
```

After translation, it can be seen that this code has changed from 7 lines to 5 lines, and after Crowdin recognizes it, it will look like this:

|Line|Before translation|After translation|
|:----:|:----:|:----:|
|2|`'&7Your team permanently gains'`|`'&7你的队伍将永远在所有的剑和斧头上获得锋利 I'` (Should correspond to the translation of the first, second, and third lines) |
|3|`'&7Sharpness I on all swords and'`|Untranslated|
|4|`'&7axes!'`|`'&7花费：&b{cost} {currency}'` (Should correspond to the translation of the sixth line) |
|5|Empty, no translation required|Empty, no translation required|
|6|`'&7Cost: &b{cost} {currency}'`|Untranslated
|7|Empty, no translation required|Empty, no translation required|

To solve these problems, you can use `JSON` instead of `YAML`, or change the content that needs to be wrapped to `\n`.

*I have translated all the above content using translation software, and there may be errors.

**Comment by Lsy-291** [comment]
Version 23.3 has added support for Simplified Chinese, please use language zh_cn
#628

**Comment by andrei1058** [comment]
@Lsy-291 can you confirm he is not translating into semplified chinese?
<img width="701" alt="image" src="https://github.com/andrei1058/BedWars1058/assets/13315829/06fda760-582c-49e4-a3b6-bc5feb2f37e1">
