### ISSUE TITLE
Get Coins when you kill yourself

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#81]
**Describe the bug**
So when you use TNT or Fireball on yourself you get little bit damage and if you die in void you will get coines.

**To Reproduce**
1. Go to 'Shop Buy TNT'
2. Try TNT jumping in Void. 
3. When you are waiting for respawn check chat.
4. Run '/bal' you will have that coins

**Screenshots**
[This is the image](https://i.imgur.com/RjCL2H0.png)

**System (please complete the following information):**
 - OS: [Ubuntu 20.04 Form A Host]
 - Server software [Paper]
 - Server Version [1.8.8]
 - Plugin Version [v21.11]

**Comment by ajgeiss0702** [comment]
This was fixed
