### ISSUE TITLE
Error: java.lang.NullPointerException: Cannot invoke "com.andrei1058.bedwars.proxy.libs.MaterialSupport.getForCurrent(String, String, String)" because the return value of "com.andrei1058.bedwars.proxy.BedwarsProxy.getMaterialAdapter()" is null

### ISSUE THREAD

**Issue by deezed420** [andrei1058/BedWars1058#810]
**Describe the bug**

**To Reproduce**
1. use purpur
2. start server
3. See error

**Expected behavior**

It working

**System (please complete the following information):**
 - OS: Chromebook
 - Server software purpur (fork of paper)
 - Server Version 1.18.2
 - Plugin Version 23.3

**Comment by andrei1058** [comment]
This is not a BedWars1058 issue. 

In conclusion, BedWarsProxy does not support your server version.
