### ISSUE TITLE
Duplicated scoreboard bug after game ends.

### ISSUE THREAD

**Issue by LOCNetwork** [andrei1058/BedWars1058#823]
**Describe the bug**

In 1.8 using version 23.3, for some reason, when using the PlayAgain addon (tested without the PlayAgain addon and it also happens) and when a game finishes and I get TPed to another game, the scoreboard bugges out displaying a duplicated scoreboard.
![bug2](https://github.com/andrei1058/BedWars1058/assets/77237451/25b76afd-a6ca-45c2-b868-12f07f7e179f)

It is the lobby scoreboard merged with the game scoreboard

If it TPes you to the lobby this is shown instead (you can see the level duplicated below the server IP):
<img width="233" alt="bug1" src="https://github.com/andrei1058/BedWars1058/assets/77237451/4faeb395-3613-4d0a-8ceb-aa5f065968d8">

**To Reproduce**
1. Finish a game
2. Get TPed to another game using the PlayAgain addon or if the server does not have that addon, get TPed to the lobby. (For some reason, only the loser will see the duplicated scoreboard and the winner will see the scoreboard working correctly)
3. You will see the bugged scoreboard.

**Expected behavior**

That the scoreboard does not get duplicated.

**System (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Server software: PandaSpigot
 - Server Version: 1.8.8
 - Plugin Version: 23.3

**Comment by andrei1058** [comment]
#774
