### ISSUE TITLE
Function Request: Add a switch for bed-hologram

### ISSUE THREAD

**Issue by zzj2039** [andrei1058/BedWars1058#849]
As the title says, I'd like to turn this feature off

**Comment by zzj2039** [comment]
补充一下，它在语言文件中的键值为：`bed-hologram-defend: bed-hologram-destroyed: `

**Comment by zzj2039** [comment]
In addition, its key value in the language file is:
``

**Comment by zzj2039** [comment]
In addition, its key value in the language file is:
`bed-hologram-defend: 
bed-hologram-destroyed: `

**Comment by PixelEast** [comment]
It can be edited in arena's configuration file

**Comment by zzj2039** [comment]
> 可以在竞技场的配置文件中进行编辑

Ok, thank you very much!
