### ISSUE TITLE
Version changer

### ISSUE THREAD

**Issue by craciu25yt** [andrei1058/BedWars1058#86]
Hi. When I update, I see in the Scoreboard say Version: 21.11. And I think to suggest one thing for use custom version. Like the version of you bedwars (I know you can change in the lang or with winrar you modify the pl version but like this can are more easy)

**Comment by Xxyuri2005xX** [comment]
You can edit the scoreboards.

**Comment by ajgeiss0702** [comment]
Yeah, you should edit the scoreboard in the language file. Being able to change the plugin version would unnecessarily complicate debugging issues
