### ISSUE TITLE
Plugin isnt loading on 1.8.8

### ISSUE THREAD

**Issue by nopgatk** [andrei1058/BedWars1058#868]
Hello, i am trying to load bedwars1058 on spigot 1.8.8, i tried also on paper 1.8.8 but isnt working, i dont understand why isnt loading, older versions is working but newest one isnt, i am using java 8, i tried also with java 11, the same error.

**Comment by andrei1058** [comment]
and where's the error mate?

**Comment by PERO1999ita** [comment]
io ho il stesso problema ecco error  ( I have the same problem here is the error )
![Immagine 2023-09-25 204705](https://github.com/andrei1058/BedWars1058/assets/146025434/774b4437-f7f4-4e27-82bd-ca49eeadacb9)

**Comment by andrei1058** [comment]
update your java version

**Comment by nopgatk** [comment]
> update your java version

if i do this, i will have errors on spigot, cause its 1.8.8 and the java maybe 16..
