### ISSUE TITLE
ARENA BUGS IN 1.8.8

### ISSUE THREAD

**Issue by Nukecraft5419** [andrei1058/BedWars1058#870]
**Describe the bug**
If two people enter an arena and one of them exits, the timer will continue to run until the arena is started, leaving you in the game alone.

**Expected behavior**
It should take off the timer being that there is only one player in the arena

**Screenshots**
![2023-09-27_18 24 56](https://github.com/andrei1058/BedWars1058/assets/72621737/3abdf4d0-c8db-4d42-a866-83eada4e47a5)
![2023-09-27_18 33 29](https://github.com/andrei1058/BedWars1058/assets/72621737/ae6d2a4b-ba88-49f6-87f4-2a0f5be1d672)
![image](https://github.com/andrei1058/BedWars1058/assets/72621737/f5442d2f-67c6-4892-8c26-231addf15f7b)

**System (please complete the following information):**
 - OS: Linux -->
 - Server software: paper
 - Server Version: 1.8.8
 - Plugin Version: 23.3

**Additional context**

**Comment by joohnaquino** [comment]
this is probably not a bug.
check that "plugins/bw1058/arenas/arena.yml -> minplayers" is not set to 1, if so, the arena will always start with 1 player

**Comment by Nukecraft5419** [comment]
all 174 arenas are set up right with the minplayers like the only one takes 2 but if one leaves the timer continues so it doesn't go to check if the arena still meets the minplayers

**Comment by joohnaquino** [comment]
> all 174 arenas are set up right with the minplayers like the only one takes 2 but if one leaves the timer continues so it doesn't go to check if the arena still meets the minplayers

try using debug mode, you also have several addons that are completely useless and not compatible with version 23.3 of bw1058. try to remove these addons, bw1058 has already included some of these addons and others can be done via server config or with others plugins

**Comment by Nukecraft5419** [comment]
Which addons should I remove

**Comment by Nukecraft5419** [comment]
I tried Also remove all addons and see if the bug shows up and without addons only with bw1058 the bug is there anyway

**Comment by Nukecraft5419** [comment]
Excuse me but BedWars1058 was tested in 1.8.8 write that it is for versions 1.8, 1.12, 1.16, 1.17, 1.18, 1.19

**Comment by joohnaquino** [comment]
> Excuse me but BedWars1058 was tested in 1.8.8 write that it is for versions 1.8, 1.12, 1.16, 1.17, 1.18, 1.19

bw1058 is being tested even in 1.20, this does not mean it will be fully compatible. version 1.8 is one of the most stable for the bw1058, I referred to addons that received their last update in 2021 or 2022, I run my server with 12 servers dedicated to bw1058, all on 1.8 and I had no problems with the count and number of players

my recommendation is that you test all the arenas on a server where there is only bw1058, then the additional plugins or just the addons, the most obvious thing I thought was that you set "minplayers" to 1, but since it isn't, just test all the plugins gradually, debug mode can help look for bugs

andrei's discord is also a great place to ask for help and show bugs

**Comment by Nukecraft5419** [comment]
Look it's not a competition who has more servers but to solve the problems that this plugin presents, most addons are to solve problems or to add new modes, I have this as maps https://polymart.org/resource/hypixel-maps-setup-bw-1058.4400 besides 4 made by me I don't use SWM because it doesn't load all the maps for me and then bedwars1058 creates worlds with the name of bw_temp_ and all codes

**Comment by joohnaquino** [comment]
> Look it's not a competition who has more servers but to solve the problems that this plugin presents, most addons are to solve problems or to add new modes, I have this as maps https://polymart.org/resource/hypixel-maps-setup-bw-1058.4400 besides 4 made by me I don't use SWM because it doesn't load all the maps for me and then bedwars1058 creates worlds with the name of bw_temp_ and all codes

Oh, I'm sorry if it sounded like a competition, I didn't mean to say that. I cited the 12 servers as an example, as there are many and with different configurations (2x solo, 2x duo...) What most occurred to me were problems with the lang, item generator, player spawn, void worlds with swm, the colors of the islands/teams being changed in the config, some bw1058 mobs didn't work correctly (dream defender) and this current problem #769, well this problem maybe something in the world file, try activating the debug and looking for traces of possible bugs, maybe they are very annoying with the debug, but it can help

Again I apologize if I gave the impression of wanting to compete

**Comment by Nukecraft5419** [comment]
Hi no big deal and that the post sounded like a challenge, leaving that aside I did some testing and it works if I put in MULTIARENA but if I put BUNGEE so the Lobby on one server and the arenas all on another with a database etc. it doesn't work the timer has the bug I said

**Comment by joohnaquino** [comment]
> Hi no big deal and that the post sounded like a challenge, leaving that aside I did some testing and it works if I put in MULTIARENA but if I put BUNGEE so the Lobby on one server and the arenas all on another with a database etc. it doesn't work the timer has the bug I said

Hmm, from what I understand, the timer works normally in MULTIARENA mode, but if you put it in BUNGEE mode it doesn't work? or is it the other way around? well that's strange, how is your "config.yml -> countdowns" configured?

**Comment by Nukecraft5419** [comment]
In MULTIARENA everything works and in BUNGEE mode that doesn't go this is the timer config 

```
countdowns:
  game-start-regular: 40
  game-start-half-arena: 25
  game-start-shortened: 5
  game-restart: 15
  player-re-spawn: 5
  next-event-beds-destroy: 360
  next-event-dragon-spawn: 600
  next-event-game-end: 120
```
