### ISSUE TITLE
Issue with Party and Friends plugin integration

### ISSUE THREAD

**Issue by Mateyoo** [andrei1058/BedWars1058#898]
**Describe the bug**
Whenever I create a party with the **Party and Friends** plugin, and I join into a BedWars game with another party member only I, the party leader get connected to the arena, the other member is in the arena server's default world. In the end, me and the party member are on the same server, but I am in the arena, and the other member isn't.

**To Reproduce**

1. Use BW1058 in BUNGEE mode with BedWarsProxy
2. Use the [PAF **EXTENDED Edition**](https://www.spigotmc.org/resources/party-and-friends-extended-edition-for-bungeecord-velocity-supports-1-7-1-20-x.10123/) plugin 
3. Make sure Player API and Friends API is installed and configured, like in the [docs](https://wiki.andrei1058.dev/docs/BedWars1058/hooks/parties-hook/#party--friends-extended-edition-for-bungeecordvelocity)
4. Create a party, invite somebody
5. Enter an arena, with **/bw join solo** for example
6. See the bug

**Expected behavior**
When you join the arena with the other party member only you will be in the arena.

**Screenshots**
[Party Leader POV](https://i.mateyo.hu/7aa8707223a4.png) - [Party Member POV](https://i.mateyo.hu/d03569700607.png)

**System**
 - OS: Linux
 - Server software: Paper
 - Server Version: 1.8.8
 - Plugin Version: 23.3

**Additional context**
Maybe the problem is that I'm not using Redis to synchronise between the BW1058 and BWP server or idk 
I have also checked if it works with Duo mode: it doesn't.

**Comment by andrei1058** [comment]
Very well documented, I'll get in touch once I reproduce it.

**Comment by andrei1058** [comment]
Also try using our latest version 23.10.1-SNAPSHOT from Discord.

**Comment by Mateyoo** [comment]
> Also try using our latest version 23.10.1-SNAPSHOT from Discord.

![image](https://github.com/andrei1058/BedWars1058/assets/44142668/82545f4d-9629-4ca3-82a9-83273668ca4d)

It does the same unfortunately.
I don't know if I messed up the Player & Party API part.
If I have energy I'll try to set it up with Redis, and also use RedisBungee.

Let me know if y'all want to check my config files.

**Comment by Mateyoo** [comment]
Update:
I tried with an another account with no permissions, the reason why the other account saw the default world is that it had bw.setup permission.
If I don't have the bw.setup permission I get this on joining:
![image](https://github.com/andrei1058/BedWars1058/assets/44142668/16f196e1-2dbb-4ff9-96a4-94ba7bbcbec3)

**Comment by andrei1058** [comment]
Follow bedwars proxy setup documentation

Il Gio 2 Nov 2023, 08:36 Mateyoo ***@***.***> ha scritto:

**Comment by Mateyoo** [comment]
I have BWP set up correctly, I only get this when joining with a party.

**Comment by Mateyoo** [comment]
**Problem solved**
The way I solved the problem is the following:
- Use JT122406's BedWarsProxy that has PAF support integrated. You can download it [here](https://cdn.discordapp.com/attachments/348088106546757653/995135933936574486/proxy-plugin-1.2.4-PAF-1.19Support.jar). If you don't trust the link, [here](https://canary.discord.com/channels/201345265821679617/348088106546757653/995135934150479952) is the Discord Message Link.
- Make sure that you have **allow-parties** set to *true*, and **enable-party-cmd** set to *false* (this is needed in order to disable the built-in party system) in your BedWarsProxy config.
- Also make sure that you have the same party-settings in your BedWars server instance, in the BedWars1058 folder.
- Configure Player API and Party API **correctly**, as it is in the docs.

It didn't work for me because I disabled **allow-parties** in both configs, since I thought that disables the internal party system aswell.
