### ISSUE TITLE
...... doesn't exits! error

### ISSUE THREAD

**Issue by Etemiz2255** [andrei1058/BedWars1058#900]
I opened the server in Aternos. I opened it with PaperMc 1.8.8. I setted the loby and I created a new world for arena. I created teams, shops, upgrades, generators and I setted arena to solo then ı saved arena. Afer this I tried to enable arena but it said .....(arena name) doesn't exits! I can't teleport the world with multiverse core. I tryied all versions of plugin. Please help me if the versions of the plugins are wrong. These are the all files in the plugins folder:
bedwars-plugin-21.10.1-SNAPSHOT.jar
[BedWars1058]
[bStats]
[Multiverse-Core]
Multiverse-Core-2.5.0.jar
[Multiverse-Inventories]
Multiverse-Inventories-2.5.0-SNAPSHOT.jar
[PluginMetrics]
[SkinsRestorer]
SkinsRestorer.jar
[WorldEdit]
worldedit-bukkit-6.1.3.jar
[WorldGuard]
[worldguard-6.2.jar]
Note: My English is bad, please excuse me.

**Comment by andrei1058** [comment]
remove multiverse.
