### ISSUE TITLE
Upgrade shop does not working/can't purchase anything from it

### ISSUE THREAD

**Issue by SunshroomChan** [andrei1058/BedWars1058#904]
**Describe the bug**

So when i upgrade to version 23.11 so the plugin kinda weird, but keep good work at sidebar and tab work (rework) but after that i found that the upgrade shop you can't purchase it

**To Reproduce**
1. Go to 'Upgrade NPC'
2. Click on any upgrade item on it
3. See error: There's no error i saw in console

**Screenshots**

https://drive.google.com/file/d/1QDbTDKkhctbGxGk_6eHM3ty0byhLBgcN/view?usp=sharing

**System (please complete the following information):**
 - OS: Windows Server 2019 Datacenter
 - Server software: PaperMC
 - Server Version: 1.8.8
 - Plugin Version: 23.11

**Additional context**

Only item shop works normally while upgrade shop does not purchase it + I tried by remove upgrade2.yml but this error still occur and i dropped to version 23.3 so upgrade shop still work normally as well!

**Comment by andrei1058** [comment]
I've been told you fixed this on our Discord and the problem was the leave delay addon.

**Comment by SunshroomChan** [comment]
> I've been told you fixed this on our Discord and the problem was the leave delay addon.

ok sorry i don't know about it, when i removed it, upgrade shop working normally
