### ISSUE TITLE
Can't work with Citizens

### ISSUE THREAD

**Issue by LeviLovie** [andrei1058/BedWars1058#920]
Your plugin provide support for te Citizens plugin, so i tryed to use it.
Last version of server what you support - 1.19.3, so I ave installed that, but the Citizens pluign works on 1.19.4. And this two plugins don't work together, because one of them running on different versions. How can i use Citizens to work with Bedwars?
(ZNPCs uses 1.19 so I can't use that too)

**Comment by LeviLovie** [comment]
(1.19.4 log):
```
[19:44:31 INFO]: Loading server plugin BedWars1058 v23.3
[19:44:31 ERROR]: I can't run on your version: v1_19_R3
```

**Comment by andrei1058** [comment]
Try with Bedwars1058 v23.11 from Polymart.org

**Comment by Melon-Oof** [comment]
for 1.19.3 use Citizens build 2972

**Comment by andrei1058** [comment]
I assume this was fixed on your side
