### ISSUE TITLE
spectator not working and dont spawn on team

### ISSUE THREAD

**Issue by moritxiuss** [andrei1058/BedWars1058#921]
**Describe the bug**
After being killed, you respawn at the spect location but your not spectator and you dont spawn at your team.

**Expected behavior**
You spawn as spectator and after 5 seconds at the team with armor and sword.

**System:**
 - OS: Windows 
 - Server software: Spigot 
 - Server Version: 1.12 
 - Plugin Version: 23.3

**Comment by andrei1058** [comment]
Any plugins installed? Also try with bedwars 23.11 from Polymart

**Comment by andrei1058** [comment]
bump
