### ISSUE TITLE
1.20.1 not working with Java 17

### ISSUE THREAD

**Issue by Melon-Oof** [andrei1058/BedWars1058#926]
Pl ver: 23.11.2
Server ver: 1.20.1
Java ver: 17.0.9 temurin
[bw bug.txt](https://github.com/andrei1058/BedWars1058/files/13531155/bw.bug.txt)

BW1058 not starting with Java 17

**Comment by Melon-Oof** [comment]
Only plugins on the server: ViaVersion 4.8.1 and Bedwars1058 23.11.2

**Comment by andrei1058** [comment]
I have sent a new snapshot on discord. LMK if it works with java 17.

**Comment by Melon-Oof** [comment]
yep, can close
