### ISSUE TITLE
After Join i fall into Void | Paper 1.19.3 Only Bedwars1058 installed

### ISSUE THREAD

**Issue by DawidDe** [andrei1058/BedWars1058#927]
**Describe the bug**
Hi, everyone. I have a Paper 1.19.3 server running BedWars1058, and I've set up an arena. However, when I attempt to join, I end up falling into the void. I don't have Multiverse or any similar plugins installed, only one plugin. Please assist me with this issue. Thank you.

**To Reproduce**
Clean Paper 1.19.3 Install.
One Plugin installed (Bedwars1058)

**Expected behavior**

**Screenshots**

**System**
 - OS: Windows
 - Server paper
 - Server Version 1.19.3
 - Plugin Version 23.3

**Additional context**

**Comment by andrei1058** [comment]
is it a pre-made server setup? or did you take a bedwars configuration from a pre-made setup?

**Comment by DawidDe** [comment]
No, I didn't use any premade server or premade config. I created a Paper server, placed the bedwars.jar file in the plugins folder, started the server, set up the lobby, and created the arena. However, when I tested it, the bug started.
