### ISSUE TITLE
Stats bug

### ISSUE THREAD

**Issue by Creeperz653** [andrei1058/BedWars1058#93]
**Describe the bug**

**To Reproduce**
1. use 1.17.1 spigot or forks
2. type /bw stats
3. try to take the items out

**Expected behavior**
you not supposed to take the items out and keep them
**video**
https://cdn.discordapp.com/attachments/348088106546757653/910413509085511680/Minecraft__1.17.1_-_Multiplayer_3rd-party_Server_2021-11-16_22-16-49.mp4

**System**
 - server software Purpur
 - Server Version 1.17.1
 - Plugin Version newest

**Additional context**

**Comment by Creeperz653** [comment]
no its not purpur bug i tested with paper

**Comment by ajgeiss0702** [comment]
Theres probably errors in the console, can you send them?

Also note 1.17 is not fully supported yet, so this might not be resolved until it is.

**Comment by Creeperz653** [comment]
ill be waiting until it is
