### ISSUE TITLE
Fireballs Break Endstone on 1.8.8

### ISSUE THREAD

**Issue by ushereats** [andrei1058/BedWars1058#936]
**Describe the bug**

When you shoot a fireball at endstone it breaks the endstone

**To Reproduce**

1. Get fireballs
2. Shoot them at the endstone

**Expected behavior**

It will break the endstone

**Screenshots**

No screenshoots

**Additional context**

I'm 100% sure it's not a issue with my os or plugins because i have tried this locally with no plugins and still got the same bug.

**Comment by andrei1058** [comment]
Server software and MC version

**Comment by andrei1058** [comment]
Plugin version?

**Comment by andrei1058** [comment]
Respect the issue template FFS..

**Comment by ushereats** [comment]
Plugin version: Latest/21.12
Server Software: Pterodactyl on Ubuntu 22.04
MC Version: 1.8.9

**Comment by andrei1058** [comment]
MC server software? Is it a paper fork?

**Comment by tomkeuper** [comment]
With the new BlastProtectionUtil the entity and blockType for Endstone is never checked

**Comment by andrei1058** [comment]
No one reported it in development builds. I had no clue.

**Comment by andrei1058** [comment]
Well, I did some tests and quick test. It does not happen on 1.20, but does on 1.8.8.

**Comment by andrei1058** [comment]
> BlastProtectionUtil

We achieve block blast protection by altering NBTTags with VersionSupport#registerTntWhitelist.
The mentioned Util is meant for explosion ray tracing so we can protect blocks behind glass blocks.

**Comment by andrei1058** [comment]
@ushereats you can go in config.yml and set blast-protection.end-stone to 69 for now

**Comment by andrei1058** [comment]
I'm not sure how I did reproduce this the first time, but it is no longer happening even on 1.8.8.
I reverted code changes and regenerated the config. Blast protection set to 12.

**On 1.20 tho, tnt does not do damage at all to end stone.**

**Comment by andrei1058** [comment]
So yeah,

For 1.8.8
```yaml
blast-protection:
  end-stone: 69
```

For 1.18
```yaml
blast-protection:
  end-stone: 12
```

For 1.20
```yaml
blast-protection:
  end-stone: 12
```
