### ISSUE TITLE
Deprecate 1.8.8, 1.17.1, 1.19.1 and 1.20

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/BedWars1058#938]
Add deprecation warning

**Comment by Melon-Oof** [comment]
sob

**Comment by MotikaCraft-TheJoshua** [comment]
please not 1.8.8:(

**Comment by MotikaCraft-TheJoshua** [comment]
just make it only java17+, there are already 1.8.8 forks that work with java17

and for 1.8.8 support, why not just leave it and stay there, no touches to it and if it breaks over time, who cares, just do not remove it from the code, i bet it will work (no feature updates to its specific parts)

**Comment by PixelEast** [comment]
I think 1.8.8 is still the mainstream version of Bedwards, and I am saddened to see that it will no longer support it :(

**Comment by Lsy-291** [comment]
why?

**Comment by andrei1058** [comment]
> why?

It is time consuming keeping compatibility with many MC versions, especially between newer like 1.20.3 and the oldest 1.8.8. MC code has changed  a lot and with every update we make there's a high risk that new bugs will appear in 1.8.8 implementation. Besides that it is also holding us back from adding new and unique features.

That being stated, I am no longer committed to keep support for 1.8.8 since we don't have an active contributors community to help me and I personally get 0 donations form my investment.

**Comment by MotikaCraft-TheJoshua** [comment]
> > why?
> 
> It is time consuming keeping compatibility with many MC versions, especially between newer like 1.20.3 and the oldest 1.8.8. MC code has changed a lot and with every update we make there's a high risk that new bugs will appear in 1.8.8 implementation. Besides that it is also holding us back from adding new and unique features.
> 
> That being stated, I am no longer committed to keep support for 1.8.8 since we don't have an active contributors community to help me and I personally get 0 donations form my investment.

Understood legend.

Tell me 1 thing — who even host latest MC version of bedwars/any minigames ever? except block building games
What is there that is very important from new versions that we will need in fast-paced minigames such as bedwars/skywars — 1.9+ cooldown in pvp? Where you go to player and attack them 1 click per second to be able to kill them? that is not fast-paced then, that is then Slow-BedWars, brand new minigame mode

Nobody who plays minigames like bedwars even care for blocks from newer versions, we have colored wool, that is enough, everything else can be done with custom textured blocks if you really need them or custom playerheads

**Comment by MotikaCraft-TheJoshua** [comment]
I personally think there should be 1.8.8 support until Folia reach stable builds, then move to folia support, remove paper fully and only leave legacy builds, or just latest paper version support + folia and that's it

**Comment by andrei1058** [comment]
I'm aware of those issues, my decision comes after ViaVersion's deprecation notice for 1.8.8.
```
[10:31:33 INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x (47)
[10:31:33 WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
```
Keeping 1.8.8 support with deprecated ViaVersion will result in people complaining for bugs that don't actually exist in BedWars. This is a behaviour I've already seen trough the years with other plugins. The regular user won't understand that and is going to leave bad reviews on spigot and so on.

We are not going to remove 1.8.8 anytime soon, I just want to inform my users and be transparent without cutting it of out of nowhere. Take a look at [compatibility](https://wiki.andrei1058.dev/docs/compatibility/).

**Comment by MotikaCraft-TheJoshua** [comment]
You already know that even if they stop supporting it (but not remove it from the code, just not support and fix things for it)
They will not **enforce** others to not contribute for fixes
I am sure someone who knows coding will work on ViaRewind, there is no doubt and there is no reason to prevent anyone from doing so and contributing to main project of viaversion to still support 1.8

But i understand what you said and i understand the decision, if you make it, there will still be a playable build from before of Bedward1058 that will eventually someone fork when 1.8 gets dropped... too much thinking in future, we'll see what happens

**Comment by actuallySoheil** [comment]
> I'm aware of those issues, my decision comes after ViaVersion's deprecation notice for 1.8.8.
> 
> ```
> [10:31:33 INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x (47)
> [10:31:33 WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
> ```
> 
> Keeping 1.8.8 support with deprecated ViaVersion will result in people complaining for bugs that don't actually exist in BedWars. This is a behaviour I've already seen trough the years with other plugins. The regular user won't understand that and is going to leave bad reviews on spigot and so on.
> 
> We are not going to remove 1.8.8 anytime soon, I just want to inform my users and be transparent without cutting it of out of nowhere. Take a look at [compatibility](https://wiki.andrei1058.dev/docs/compatibility/).

If you run 1.8 on Java 17, you won't get that message.

**Comment by andrei1058** [comment]
> > I'm aware of those issues, my decision comes after ViaVersion's deprecation notice for 1.8.8.
> > ```
> > [10:31:33 INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x (47)
> > [10:31:33 WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Keeping 1.8.8 support with deprecated ViaVersion will result in people complaining for bugs that don't actually exist in BedWars. This is a behaviour I've already seen trough the years with other plugins. The regular user won't understand that and is going to leave bad reviews on spigot and so on.
> > We are not going to remove 1.8.8 anytime soon, I just want to inform my users and be transparent without cutting it of out of nowhere. Take a look at [compatibility](https://wiki.andrei1058.dev/docs/compatibility/).
> 
> If you run 1.8 on Java 17, you won't get that message.

It says "server version", not "java version"... here my java version since you know better
![image](https://github.com/andrei1058/BedWars1058/assets/13315829/a807d849-245e-4a01-bcf3-1c9ea8ec2789)

**Comment by xanthacreator** [comment]
real like no one is gonna use this plugin if it doesnt support 1.8..... theres many 1.8.8 forks that support java 17+ so removing 1.8.8 support was just stupid.. most bedwars servers have some type of 1.8.8 spigot fork
