### ISSUE TITLE
SlimeWorldManager Hook issue

### ISSUE THREAD

**Issue by AidinShekari** [andrei1058/BedWars1058#94]
**SlimeWorldManager Hook issue**

Arena's On Disable Doesnt get Enable Again ! ( And Reset To Old Map ) - Server Should Restart To It get Fix ! ( Enable Arenas & Reset Worlds )

``
[Server thread/WARN]: java.io.IOException: No such file or directory
[Server thread/WARN]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[Server thread/WARN]: 	at java.io.File.createNewFile(File.java:1023)
[Server thread/WARN]: 	at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.handleLevelDat(SlimeAdapter.java:400)
[Server thread/WARN]: 	at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorlds(SlimeAdapter.java:331)
[Server thread/WARN]: 	at com.andrei1058.bedwars.BedWars.loadArenasAndSigns(BedWars.java:583)
[Server thread/WARN]: 	at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:335)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:549)
[Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
``

**Server Information**

1.8.8 [ FlamePaper ] 
BedWars1058 21.11.1
Slimeworldmanager 2.3v

**Comment by Askarionn** [comment]
try to use paperspigot/spigot maybe it's a problem related to flame fork

**Comment by andrei1058** [comment]
Give the right permissions to your user
