### ISSUE TITLE
Scoreboard Bug

### ISSUE THREAD

**Issue by Squesly** [andrei1058/BedWars1058#941]
**Describe the bug**
Scoreboard bug when you join server after server boot finished.

**To Reproduce**
1.Boot server
2.Join server after boot
3.Your scoreboard bug ezez

**Screenshots**
![image](https://github.com/andrei1058/BedWars1058/assets/105538755/ee797775-2fdc-4ff5-b873-24a9af9a7cc9)

**System (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - Server software: Paper
 - Server Version: 1.8.8
 - Plugin Version: 23.1.2

**Comment by Squesly** [comment]
Its happen randomly

**Comment by andrei1058** [comment]
Try using the latest bedwars update.. **v23.12**

**Comment by Squesly** [comment]
I'm using that but I'll change ver sidebar lib in pom.xml to 23.12 like ur cuz mine is 23.10

**Comment by Squesly** [comment]
and this still bug. the scoreboard is duplicate lines
![image](https://github.com/andrei1058/BedWars1058/assets/105538755/41ee2c69-7f7f-46f9-8b13-7d45b8adc939)

**Comment by andrei1058** [comment]
Sorry, but we do not provide support for BedWars1058 forks.

**Comment by Squesly** [comment]
Brother, even I'm using forked or not the scoreboard duplicate still happens when gamestate change immediately from waiting to starting when player join map

**Comment by Squesly** [comment]
https://github.com/andrei1058/BedWars1058/issues/823

**Comment by andrei1058** [comment]
Allign to master brodha

**Comment by Squesly** [comment]
Wat
