### ISSUE TITLE
Death screen when fall into the void

### ISSUE THREAD

**Issue by FabrisNick** [andrei1058/BedWars1058#95]
**Describe the bug**
When I fall into the void I see the death screen for a few milliseconds, i know it's a minor bug, but it's a bit annoying

**To Reproduce**
Just fall into the void

**Expected behavior**
An instant respawn without the death screen

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: NachoSpigot
 - Server Version: 1.8.8
 - Plugin Version: 21.11.1

**Comment by iiAhmedYT** [comment]
That's not a bug that's kinda of how the plugin works

**Comment by ghost** [comment]
use instant respawn plugin to solve that issue
