### ISSUE TITLE
When watching a game, the placeholder is not replaced like in the picture.

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/BedWars1058#950]
When watching a game, the placeholder is not replaced like in the picture.

**Screenshots**

![image](https://github.com/andrei1058/BedWars1058/assets/85287520/9ed060ec-d85d-4471-9ab8-b4c469aa2d3c)

**System (please complete the following information):**
 - OS:  Windows 11 Pro
 - Server software  Paper
 - Server Version  1.8.8
 - Plugin Version  23.12.2

**Additional context**

**Comment by andrei1058** [comment]
It happens when the spectator never played in a team in that game. This kind of spectator has a configurable sidebar in messages where you have to remove those placeholders.  
The spectator which is a player that has been eliminated from a team has a custom sidebar as well, but you'll get you placeholders replaced in that case.

**Comment by ImYenil** [comment]
> It happens when the spectator never played in a team in that game. This kind of spectator has a configurable sidebar in messages where you have to remove those placeholders. The spectator which is a player that has been eliminated from a team has a custom sidebar as well, but you'll get you placeholders replaced in that case.

Is there any way to fix it? This is because the scoreboard for each group is different.

**Comment by andrei1058** [comment]
You have to fix your messages.

**Comment by andrei1058** [comment]
I found out I forgot to make a custom scoreboard for that.
Fixed in https://github.com/andrei1058/BedWars1058/pull/953

**Comment by andrei1058** [comment]
Copy your sidebar content from `spectator` to `eliminated` and remove session stats placeholders under `spectator`.
