### ISSUE TITLE
Team color based on vanilla color

### ISSUE THREAD

**Issue by SQEngine** [andrei1058/BedWars1058#958]

**Comment by andrei1058** [comment]
What do you mean they have not been added? Where exactly?

**Comment by SQEngine** [comment]
![2024-01-07_04 10 21](https://github.com/andrei1058/BedWars1058/assets/43875951/94aec780-72b9-4774-9043-3b5f02bc8c9e)
When creating a team, there are only 10 colors. Where are the other 6 colors from Vanilla?
