### ISSUE TITLE
The names of Iron Golem and Silverfish in version 1.20.4 are incorrect

### ISSUE THREAD

**Issue by Lsy-291** [andrei1058/BedWars1058#987]
**Describe the bug**
The placeholders for the names of Iron Golem and Silverfish in version 1.20.4 have not been replaced

**To Reproduce**
Running version 1.20.4 of the server, purchasing summoning eggs, the situation shown in the figure occurs

**Expected behavior**
Name placeholder replaced correctly

**Screenshots**
![screenshot](https://media.discordapp.net/attachments/348088106546757653/1213512916490395689/2024-03-02_15.45.47.png?ex=65f5bef9&is=65e349f9&hm=8b68ce3c0816c0598da4a09b4134b2d619ab77c390c71323768c5a9cda03c7b9&=&format=webp&quality=lossless&width=1202&height=676)

**System (please complete the following information):**
 - OS: Windows Server
 - Server software: spigot 
 - Server Version: 1.20.4
 - Plugin Version: 23.12.2

**Comment by ImYenil** [comment]
> **Describe the bug** The placeholders for the names of Iron Golem and Silverfish in version 1.20.4 have not been replaced
> 
> **To Reproduce** Steps to reproduce the behavior: Running version 1.20.4 of the server, purchasing summoning eggs, the situation shown in the figure occurs
> 
> **Expected behavior** Name placeholder replaced correctly
> 
> **Screenshots** ![screenshot](https://camo.githubusercontent.com/4642840a7bbba1b7a868554dffc7aee18bf2890954dcf764c69e58ce29ce3acc/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3334383038383130363534363735373635332f313231333531323931363439303339353638392f323032342d30332d30325f31352e34352e34372e706e673f65783d36356635626566392669733d363565333439663926686d3d38623638636533633038313663303539386461346130396234313334623264363139616237376333393063373133323337363863356139636461303363376239263d26666f726d61743d77656270267175616c6974793d6c6f73736c6573732677696474683d31323032266865696768743d363736)
> 
> **System (please complete the following information):**
> 
> * OS: Windows Server
> * Server software: spigot
> * Server Version: 1.20.4
> * Plugin Version: 23.12.2

Fixed https://github.com/andrei1058/BedWars1058/pull/994
